// Code generated by contractgen; DO NOT EDIT.

package codex

import (
	"encoding/json"
	"fmt"
	"github.com/wspl/demi/internal/contract"
	core "github.com/wspl/demi/internal/core"
	provider "github.com/wspl/demi/internal/provider"
)

func decodeAccountID(data []byte) (accountID, error) { return contract.Decode[accountID](data) }
func (v accountID) Validate() error                  { return contractValidateAccountID(v, 0) }
func contractValidateAccountID(v accountID, depth int) error {
	if depth > 1000 {
		return fmt.Errorf("validation nesting exceeds 1000")
	}
	if err := contract.Text(string(v), 0, -1, ""); err != nil {
		return contract.At("", err)
	}
	if err := validateAccountID(v); err != nil {
		return err
	}
	return nil
}
func (v *accountID) UnmarshalJSON(data []byte) error {
	value, err := contract.Decode[string](data)
	if err != nil {
		return err
	}
	next := accountID(value)
	if err := next.Validate(); err != nil {
		return err
	}
	*v = next
	return nil
}
func (v accountID) MarshalJSON() ([]byte, error) {
	if err := v.Validate(); err != nil {
		return nil, err
	}
	return contract.EncodeJSON(string(v))
}
func decodeSecret(data []byte) (secret, error) { return contract.Decode[secret](data) }
func (v secret) Validate() error               { return contractValidateSecret(v, 0) }
func contractValidateSecret(v secret, depth int) error {
	if depth > 1000 {
		return fmt.Errorf("validation nesting exceeds 1000")
	}
	if err := v.AccessToken.Validate(); err != nil {
		return contract.At("accessToken", err)
	}
	if err := contract.Text(string(v.AccessToken), 0, -1, ""); err != nil {
		return contract.At("accessToken", err)
	}
	if err := v.RefreshToken.Validate(); err != nil {
		return contract.At("refreshToken", err)
	}
	if err := contract.Text(string(v.RefreshToken), 0, -1, ""); err != nil {
		return contract.At("refreshToken", err)
	}
	if err := v.IDToken.Validate(); err != nil {
		return contract.At("idToken", err)
	}
	if err := contract.Text(string(v.IDToken), 0, -1, ""); err != nil {
		return contract.At("idToken", err)
	}
	if err := contractValidateAccountID(v.AccountID, depth+1); err != nil {
		return contract.At("accountId", err)
	}
	if err := contract.Text(string(v.AccountID), 0, -1, ""); err != nil {
		return contract.At("accountId", err)
	}
	if err := v.LastRefresh.Validate(); err != nil {
		return contract.At("lastRefresh", err)
	}
	if err := contract.Text(string(v.LastRefresh), 0, -1, ""); err != nil {
		return contract.At("lastRefresh", err)
	}
	return nil
}
func (v *secret) UnmarshalJSON(data []byte) error {
	obj, err := contract.Decode[map[string]json.RawMessage](data)
	if err != nil {
		return err
	}
	var next secret
	for key := range obj {
		switch key {
		case "accessToken", "refreshToken", "idToken", "accountId", "lastRefresh":
		default:
			return contract.At(key, fmt.Errorf("unknown field"))
		}
	}
	{
		raw, ok := obj["accessToken"]
		if !ok {
			return contract.At("accessToken", fmt.Errorf("required field is absent"))
		}
		if ok {
			value, err := contract.Decode[provider.Secret](raw)
			if err != nil {
				return contract.At("accessToken", err)
			}
			next.AccessToken = value
		}
	}
	{
		raw, ok := obj["refreshToken"]
		if !ok {
			return contract.At("refreshToken", fmt.Errorf("required field is absent"))
		}
		if ok {
			value, err := contract.Decode[provider.Secret](raw)
			if err != nil {
				return contract.At("refreshToken", err)
			}
			next.RefreshToken = value
		}
	}
	{
		raw, ok := obj["idToken"]
		if !ok {
			return contract.At("idToken", fmt.Errorf("required field is absent"))
		}
		if ok {
			value, err := contract.Decode[provider.Secret](raw)
			if err != nil {
				return contract.At("idToken", err)
			}
			next.IDToken = value
		}
	}
	{
		raw, ok := obj["accountId"]
		if !ok {
			return contract.At("accountId", fmt.Errorf("required field is absent"))
		}
		if ok {
			value, err := contract.Decode[accountID](raw)
			if err != nil {
				return contract.At("accountId", err)
			}
			next.AccountID = value
		}
	}
	{
		raw, ok := obj["lastRefresh"]
		if !ok {
			return contract.At("lastRefresh", fmt.Errorf("required field is absent"))
		}
		if ok {
			value, err := contract.Decode[core.Timestamp](raw)
			if err != nil {
				return contract.At("lastRefresh", err)
			}
			next.LastRefresh = value
		}
	}
	if err := next.Validate(); err != nil {
		return err
	}
	*v = next
	return nil
}
func (v secret) MarshalJSON() ([]byte, error) {
	if err := v.Validate(); err != nil {
		return nil, err
	}
	fields := []contract.Field{}
	fields = append(fields, contract.Field{Name: "accessToken", Value: v.AccessToken})
	fields = append(fields, contract.Field{Name: "refreshToken", Value: v.RefreshToken})
	fields = append(fields, contract.Field{Name: "idToken", Value: v.IDToken})
	fields = append(fields, contract.Field{Name: "accountId", Value: v.AccountID})
	fields = append(fields, contract.Field{Name: "lastRefresh", Value: v.LastRefresh})
	return contract.EncodeObject(fields)
}
