// Code generated by wiregen; DO NOT EDIT.

package commandservice

import (
	"encoding/json/jsontext"
	"encoding/json/v2"
	"fmt"

	"github.com/wspl/demi/go/internal/wire"
)

// decodeConversationRequest decodes the JSON object of a ConversationRequest, whichever variant it is.
func decodeConversationRequest(dec *jsontext.Decoder) (ConversationRequest, error) {
	raw, err := wire.ReadObject(dec)
	if err != nil {
		return nil, err
	}
	tag, err := wire.Tag(raw, "operation")
	if err != nil {
		return nil, err
	}
	switch tag {
	case "release":
		var v ReleaseRequest
		if err := v.UnmarshalJSONFrom(wire.NewDecoder(raw)); err != nil {
			return nil, err
		}
		return v, nil
	case "status":
		var v StatusRequest
		if err := v.UnmarshalJSONFrom(wire.NewDecoder(raw)); err != nil {
			return nil, err
		}
		return v, nil
	}
	return nil, wire.UnknownTag("operation", "release", "status")
}

// validateConversationRequest checks the rules of the variant that v is.
func validateConversationRequest(v ConversationRequest) error {
	switch v := v.(type) {
	case nil:
		return wire.Required("")
	case ReleaseRequest:
		return v.validate()
	case *ReleaseRequest:
		if v == nil {
			return fmt.Errorf("a nil %T is not a variant of ConversationRequest", v)
		}
		return v.validate()
	case StatusRequest:
		return v.validate()
	case *StatusRequest:
		if v == nil {
			return fmt.Errorf("a nil %T is not a variant of ConversationRequest", v)
		}
		return v.validate()
	}
	return fmt.Errorf("%T is not a variant of ConversationRequest", v)
}

// UnmarshalJSONFrom decodes the JSON object of ReleaseRequest: it refuses a member that
// the type does not have, a required member that is missing, a null, and a
// value of another JSON kind than the member's, naming the member.
func (v *ReleaseRequest) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = ReleaseRequest{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "operation":
			seen |= 1 << 0
			tag, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("operation", err)
			}
			if tag != "release" {
				return wire.UnknownTag("operation", "release")
			}
		case "conversation":
			seen |= 1 << 1
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("conversation", err)
			}
			v.Conversation = s
		default:
			return wire.Unknown(name)
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("operation")
	}
	if seen&(1<<1) == 0 {
		return wire.Required("conversation")
	}
	return nil
}

// MarshalJSONTo encodes ReleaseRequest as a JSON object that starts with its tag.
func (v ReleaseRequest) MarshalJSONTo(enc *jsontext.Encoder) error {
	return json.MarshalEncode(enc, struct {
		Tag          string `json:"operation"`
		Conversation string `json:"conversation"`
	}{"release", v.Conversation})
}

// validate checks the rules of the fields of ReleaseRequest, and reports every one that
// is broken.
func (v ReleaseRequest) validate() error {
	var r wire.Report
	r.Chars("conversation", v.Conversation, wire.Between(1, int64(ConversationNameChars)))
	r.Pattern("conversation", v.Conversation, nameCharacters)
	return r.Err()
}

// UnmarshalJSONFrom decodes the JSON object of StatusRequest: it refuses a member that
// the type does not have, a required member that is missing, a null, and a
// value of another JSON kind than the member's, naming the member.
func (v *StatusRequest) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = StatusRequest{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "operation":
			seen |= 1 << 0
			tag, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("operation", err)
			}
			if tag != "status" {
				return wire.UnknownTag("operation", "status")
			}
		default:
			return wire.Unknown(name)
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("operation")
	}
	return nil
}

// MarshalJSONTo encodes StatusRequest as a JSON object that starts with its tag.
func (v StatusRequest) MarshalJSONTo(enc *jsontext.Encoder) error {
	return json.MarshalEncode(enc, struct {
		Tag string `json:"operation"`
	}{"status"})
}

// validate checks the rules of the fields of StatusRequest, and reports every one that
// is broken.
func (StatusRequest) validate() error {
	return nil
}

// UnmarshalJSONFrom decodes the JSON object of ConversationStatus: it refuses a member that
// the type does not have, a required member that is missing, a null, and a
// value of another JSON kind than the member's, naming the member.
func (v *ConversationStatus) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = ConversationStatus{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "conversations":
			seen |= 1 << 0
			if err := wire.BeginArray(dec); err != nil {
				return wire.In("conversations", err)
			}
			items0 := []string{}
			for {
				more, err := wire.NextElement(dec)
				if err != nil {
					return wire.In("conversations", err)
				}
				if !more {
					break
				}
				var element0 string
				{
					s, err := wire.ReadString(dec)
					if err != nil {
						return wire.In("conversations", wire.In(wire.Index(len(items0)), err))
					}
					element0 = s
				}
				items0 = append(items0, element0)
			}
			v.Conversations = items0
		default:
			return wire.Unknown(name)
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("conversations")
	}
	return nil
}

// validate checks the rules of the fields of ConversationStatus, and reports every one that
// is broken.
func (v ConversationStatus) validate() error {
	var r wire.Report
	{
		var group0 wire.Report
		for i, e := range v.Conversations {
			var item0 wire.Report
			item0.Chars("", e, wire.AtLeast(1))
			group0.Nest(wire.Index(i), item0.Err())
		}
		r.Nest("conversations", group0.Err())
	}
	return r.Err()
}
