// Code generated by wiregen; DO NOT EDIT.

package commandservice

import (
	"encoding/json/jsontext"
	"encoding/json/v2"
)

// wireOptions are the options of every decode and encode of the package's wire
// types: maps are encoded in sorted key order, and each union has its own
// decoder, which json needs to decode into an interface.
var wireOptions = json.JoinOptions(
	json.Deterministic(true),
	json.WithUnmarshalers(json.JoinUnmarshalers(
		json.UnmarshalFromFunc(func(dec *jsontext.Decoder, v *ConversationRequest) error {
			value, err := decodeConversationRequest(dec)
			if err != nil {
				return err
			}
			*v = value
			return nil
		}),
		json.UnmarshalFromFunc(func(dec *jsontext.Decoder, v *CommandCaller) error {
			value, err := decodeCommandCaller(dec)
			if err != nil {
				return err
			}
			*v = value
			return nil
		}),
		json.UnmarshalFromFunc(func(dec *jsontext.Decoder, v *ArtifactLocation) error {
			value, err := decodeArtifactLocation(dec)
			if err != nil {
				return err
			}
			*v = value
			return nil
		}),
	)),
)
