// Code generated by wiregen; DO NOT EDIT.

package provider

import (
	"encoding/json/jsontext"
	"encoding/json/v2"

	"github.com/wspl/demi/go/internal/wire"
)

// UnmarshalJSONFrom decodes the JSON object of ResponsesItemEvent: it ignores a member that
// the type does not have, and refuses a required member that is missing, a
// null, and a value of another JSON kind than the member's, naming the member.
func (v *ResponsesItemEvent) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = ResponsesItemEvent{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "item":
			if wire.IsNull(dec) {
				if _, err := dec.ReadToken(); err != nil {
					return wire.In("item", err)
				}
			} else {
				var value jsontext.Value
				raw, err := wire.ReadRaw(dec)
				if err != nil {
					return wire.In("item", err)
				}
				value = raw
				v.Item = &value
			}
		case "item_id":
			if wire.IsNull(dec) {
				if _, err := dec.ReadToken(); err != nil {
					return wire.In("item_id", err)
				}
			} else {
				var value string
				s, err := wire.ReadString(dec)
				if err != nil {
					return wire.In("item_id", err)
				}
				value = s
				v.ItemID = &value
			}
		case "call_id":
			if wire.IsNull(dec) {
				if _, err := dec.ReadToken(); err != nil {
					return wire.In("call_id", err)
				}
			} else {
				var value string
				s, err := wire.ReadString(dec)
				if err != nil {
					return wire.In("call_id", err)
				}
				value = s
				v.CallID = &value
			}
		default:
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
	return nil
}

// validate checks the rules of the fields of ResponsesItemEvent, and reports every one that
// is broken.
func (ResponsesItemEvent) validate() error {
	return nil
}

// UnmarshalJSONFrom decodes the JSON object of ResponsesDelta: it ignores a member that
// the type does not have, and refuses a required member that is missing, a
// null, and a value of another JSON kind than the member's, naming the member.
func (v *ResponsesDelta) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = ResponsesDelta{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "delta":
			seen |= 1 << 0
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("delta", err)
			}
			v.Delta = s
		case "item_id":
			if wire.IsNull(dec) {
				if _, err := dec.ReadToken(); err != nil {
					return wire.In("item_id", err)
				}
			} else {
				var value string
				s, err := wire.ReadString(dec)
				if err != nil {
					return wire.In("item_id", err)
				}
				value = s
				v.ItemID = &value
			}
		default:
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("delta")
	}
	return nil
}

// validate checks the rules of the fields of ResponsesDelta, and reports every one that
// is broken.
func (ResponsesDelta) validate() error {
	return nil
}

// UnmarshalJSONFrom decodes the JSON object of ResponsesArgumentsDone: it ignores a member that
// the type does not have, and refuses a required member that is missing, a
// null, and a value of another JSON kind than the member's, naming the member.
func (v *ResponsesArgumentsDone) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = ResponsesArgumentsDone{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "arguments":
			seen |= 1 << 0
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("arguments", err)
			}
			v.Arguments = s
		case "item_id":
			if wire.IsNull(dec) {
				if _, err := dec.ReadToken(); err != nil {
					return wire.In("item_id", err)
				}
			} else {
				var value string
				s, err := wire.ReadString(dec)
				if err != nil {
					return wire.In("item_id", err)
				}
				value = s
				v.ItemID = &value
			}
		default:
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("arguments")
	}
	return nil
}

// validate checks the rules of the fields of ResponsesArgumentsDone, and reports every one that
// is broken.
func (ResponsesArgumentsDone) validate() error {
	return nil
}

// UnmarshalJSONFrom decodes the JSON object of ResponsesCompleted: it ignores a member that
// the type does not have, and refuses a required member that is missing, a
// null, and a value of another JSON kind than the member's, naming the member.
func (v *ResponsesCompleted) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = ResponsesCompleted{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "response":
			if wire.IsNull(dec) {
				if _, err := dec.ReadToken(); err != nil {
					return wire.In("response", err)
				}
			} else {
				var value ResponsesCompletedResponse
				if err := value.UnmarshalJSONFrom(dec); err != nil {
					return wire.In("response", err)
				}
				v.Response = &value
			}
		default:
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
	return nil
}

// validate checks the rules of the fields of ResponsesCompleted, and reports every one that
// is broken.
func (v ResponsesCompleted) validate() error {
	var r wire.Report
	if v.Response != nil {
		r.Nest("response", (*v.Response).validate())
	}
	return r.Err()
}

// UnmarshalJSONFrom decodes the JSON object of ResponsesCompletedResponse: it ignores a member that
// the type does not have, and refuses a required member that is missing, a
// null, and a value of another JSON kind than the member's, naming the member.
func (v *ResponsesCompletedResponse) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = ResponsesCompletedResponse{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "usage":
			if wire.IsNull(dec) {
				if _, err := dec.ReadToken(); err != nil {
					return wire.In("usage", err)
				}
			} else {
				var value ResponsesUsage
				if err := value.UnmarshalJSONFrom(dec); err != nil {
					return wire.In("usage", err)
				}
				v.Usage = &value
			}
		default:
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
	return nil
}

// validate checks the rules of the fields of ResponsesCompletedResponse, and reports every one that
// is broken.
func (v ResponsesCompletedResponse) validate() error {
	var r wire.Report
	if v.Usage != nil {
		r.Nest("usage", (*v.Usage).validate())
	}
	return r.Err()
}

// UnmarshalJSONFrom decodes the JSON object of ResponsesUsage: it ignores a member that
// the type does not have, and refuses a required member that is missing, a
// null, and a value of another JSON kind than the member's, naming the member.
func (v *ResponsesUsage) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = ResponsesUsage{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "input_tokens":
			if wire.IsNull(dec) {
				if _, err := dec.ReadToken(); err != nil {
					return wire.In("input_tokens", err)
				}
			} else {
				var value uint64
				n, err := wire.ReadUint(dec, 64)
				if err != nil {
					return wire.In("input_tokens", err)
				}
				value = n
				v.InputTokens = &value
			}
		case "output_tokens":
			if wire.IsNull(dec) {
				if _, err := dec.ReadToken(); err != nil {
					return wire.In("output_tokens", err)
				}
			} else {
				var value uint64
				n, err := wire.ReadUint(dec, 64)
				if err != nil {
					return wire.In("output_tokens", err)
				}
				value = n
				v.OutputTokens = &value
			}
		case "input_tokens_details":
			if wire.IsNull(dec) {
				if _, err := dec.ReadToken(); err != nil {
					return wire.In("input_tokens_details", err)
				}
			} else {
				var value ResponsesInputDetails
				if err := value.UnmarshalJSONFrom(dec); err != nil {
					return wire.In("input_tokens_details", err)
				}
				v.InputTokensDetails = &value
			}
		default:
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
	return nil
}

// validate checks the rules of the fields of ResponsesUsage, and reports every one that
// is broken.
func (v ResponsesUsage) validate() error {
	var r wire.Report
	if v.InputTokensDetails != nil {
		r.Nest("input_tokens_details", (*v.InputTokensDetails).validate())
	}
	return r.Err()
}

// UnmarshalJSONFrom decodes the JSON object of ResponsesInputDetails: it ignores a member that
// the type does not have, and refuses a required member that is missing, a
// null, and a value of another JSON kind than the member's, naming the member.
func (v *ResponsesInputDetails) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = ResponsesInputDetails{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "cached_tokens":
			if wire.IsNull(dec) {
				if _, err := dec.ReadToken(); err != nil {
					return wire.In("cached_tokens", err)
				}
			} else {
				var value uint64
				n, err := wire.ReadUint(dec, 64)
				if err != nil {
					return wire.In("cached_tokens", err)
				}
				value = n
				v.CachedTokens = &value
			}
		case "cache_write_tokens":
			if wire.IsNull(dec) {
				if _, err := dec.ReadToken(); err != nil {
					return wire.In("cache_write_tokens", err)
				}
			} else {
				var value uint64
				n, err := wire.ReadUint(dec, 64)
				if err != nil {
					return wire.In("cache_write_tokens", err)
				}
				value = n
				v.CacheWriteTokens = &value
			}
		default:
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
	return nil
}

// validate checks the rules of the fields of ResponsesInputDetails, and reports every one that
// is broken.
func (ResponsesInputDetails) validate() error {
	return nil
}

// UnmarshalJSONFrom decodes the JSON object of ResponsesFailed: it ignores a member that
// the type does not have, and refuses a required member that is missing, a
// null, and a value of another JSON kind than the member's, naming the member.
func (v *ResponsesFailed) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = ResponsesFailed{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "response":
			if wire.IsNull(dec) {
				if _, err := dec.ReadToken(); err != nil {
					return wire.In("response", err)
				}
			} else {
				var value ResponsesFailedResponse
				if err := value.UnmarshalJSONFrom(dec); err != nil {
					return wire.In("response", err)
				}
				v.Response = &value
			}
		default:
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
	return nil
}

// validate checks the rules of the fields of ResponsesFailed, and reports every one that
// is broken.
func (v ResponsesFailed) validate() error {
	var r wire.Report
	if v.Response != nil {
		r.Nest("response", (*v.Response).validate())
	}
	return r.Err()
}

// UnmarshalJSONFrom decodes the JSON object of ResponsesFailedResponse: it ignores a member that
// the type does not have, and refuses a required member that is missing, a
// null, and a value of another JSON kind than the member's, naming the member.
func (v *ResponsesFailedResponse) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = ResponsesFailedResponse{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "id":
			if wire.IsNull(dec) {
				if _, err := dec.ReadToken(); err != nil {
					return wire.In("id", err)
				}
			} else {
				var value ReportedString
				if err := value.UnmarshalJSONFrom(dec); err != nil {
					return wire.In("id", err)
				}
				v.ID = &value
			}
		case "error":
			if wire.IsNull(dec) {
				if _, err := dec.ReadToken(); err != nil {
					return wire.In("error", err)
				}
			} else {
				var value ResponsesVendorError
				if err := value.UnmarshalJSONFrom(dec); err != nil {
					return wire.In("error", err)
				}
				v.Error = &value
			}
		default:
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
	return nil
}

// validate checks the rules of the fields of ResponsesFailedResponse, and reports every one that
// is broken.
func (v ResponsesFailedResponse) validate() error {
	var r wire.Report
	if v.Error != nil {
		r.Nest("error", (*v.Error).validate())
	}
	return r.Err()
}

// UnmarshalJSONFrom decodes the JSON object of ResponsesIncomplete: it ignores a member that
// the type does not have, and refuses a required member that is missing, a
// null, and a value of another JSON kind than the member's, naming the member.
func (v *ResponsesIncomplete) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = ResponsesIncomplete{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "response":
			if wire.IsNull(dec) {
				if _, err := dec.ReadToken(); err != nil {
					return wire.In("response", err)
				}
			} else {
				var value ResponsesIncompleteResponse
				if err := value.UnmarshalJSONFrom(dec); err != nil {
					return wire.In("response", err)
				}
				v.Response = &value
			}
		default:
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
	return nil
}

// validate checks the rules of the fields of ResponsesIncomplete, and reports every one that
// is broken.
func (v ResponsesIncomplete) validate() error {
	var r wire.Report
	if v.Response != nil {
		r.Nest("response", (*v.Response).validate())
	}
	return r.Err()
}

// UnmarshalJSONFrom decodes the JSON object of ResponsesIncompleteResponse: it ignores a member that
// the type does not have, and refuses a required member that is missing, a
// null, and a value of another JSON kind than the member's, naming the member.
func (v *ResponsesIncompleteResponse) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = ResponsesIncompleteResponse{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "incomplete_details":
			if wire.IsNull(dec) {
				if _, err := dec.ReadToken(); err != nil {
					return wire.In("incomplete_details", err)
				}
			} else {
				var value ResponsesIncompleteDetails
				if err := value.UnmarshalJSONFrom(dec); err != nil {
					return wire.In("incomplete_details", err)
				}
				v.IncompleteDetails = &value
			}
		default:
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
	return nil
}

// validate checks the rules of the fields of ResponsesIncompleteResponse, and reports every one that
// is broken.
func (v ResponsesIncompleteResponse) validate() error {
	var r wire.Report
	if v.IncompleteDetails != nil {
		r.Nest("incomplete_details", (*v.IncompleteDetails).validate())
	}
	return r.Err()
}

// UnmarshalJSONFrom decodes the JSON object of ResponsesIncompleteDetails: it ignores a member that
// the type does not have, and refuses a required member that is missing, a
// null, and a value of another JSON kind than the member's, naming the member.
func (v *ResponsesIncompleteDetails) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = ResponsesIncompleteDetails{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "reason":
			if wire.IsNull(dec) {
				if _, err := dec.ReadToken(); err != nil {
					return wire.In("reason", err)
				}
			} else {
				var value ReportedString
				if err := value.UnmarshalJSONFrom(dec); err != nil {
					return wire.In("reason", err)
				}
				v.Reason = &value
			}
		default:
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
	return nil
}

// validate checks the rules of the fields of ResponsesIncompleteDetails, and reports every one that
// is broken.
func (ResponsesIncompleteDetails) validate() error {
	return nil
}

// UnmarshalJSONFrom decodes the JSON object of ResponsesError: it ignores a member that
// the type does not have, and refuses a required member that is missing, a
// null, and a value of another JSON kind than the member's, naming the member.
func (v *ResponsesError) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = ResponsesError{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "message":
			if wire.IsNull(dec) {
				if _, err := dec.ReadToken(); err != nil {
					return wire.In("message", err)
				}
			} else {
				var value ReportedString
				if err := value.UnmarshalJSONFrom(dec); err != nil {
					return wire.In("message", err)
				}
				v.Message = &value
			}
		case "code":
			if wire.IsNull(dec) {
				if _, err := dec.ReadToken(); err != nil {
					return wire.In("code", err)
				}
			} else {
				var value ReportedString
				if err := value.UnmarshalJSONFrom(dec); err != nil {
					return wire.In("code", err)
				}
				v.Code = &value
			}
		case "error":
			if wire.IsNull(dec) {
				if _, err := dec.ReadToken(); err != nil {
					return wire.In("error", err)
				}
			} else {
				var value ResponsesVendorError
				if err := value.UnmarshalJSONFrom(dec); err != nil {
					return wire.In("error", err)
				}
				v.Error = &value
			}
		default:
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
	return nil
}

// validate checks the rules of the fields of ResponsesError, and reports every one that
// is broken.
func (v ResponsesError) validate() error {
	var r wire.Report
	if v.Error != nil {
		r.Nest("error", (*v.Error).validate())
	}
	return r.Err()
}

// UnmarshalJSONFrom decodes the JSON object of ResponsesVendorError: it ignores a member that
// the type does not have, and refuses a required member that is missing, a
// null, and a value of another JSON kind than the member's, naming the member.
func (v *ResponsesVendorError) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = ResponsesVendorError{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "code":
			if wire.IsNull(dec) {
				if _, err := dec.ReadToken(); err != nil {
					return wire.In("code", err)
				}
			} else {
				var value ReportedString
				if err := value.UnmarshalJSONFrom(dec); err != nil {
					return wire.In("code", err)
				}
				v.Code = &value
			}
		case "type":
			if wire.IsNull(dec) {
				if _, err := dec.ReadToken(); err != nil {
					return wire.In("type", err)
				}
			} else {
				var value ReportedString
				if err := value.UnmarshalJSONFrom(dec); err != nil {
					return wire.In("type", err)
				}
				v.Type = &value
			}
		case "message":
			if wire.IsNull(dec) {
				if _, err := dec.ReadToken(); err != nil {
					return wire.In("message", err)
				}
			} else {
				var value ReportedString
				if err := value.UnmarshalJSONFrom(dec); err != nil {
					return wire.In("message", err)
				}
				v.Message = &value
			}
		case "request_id":
			if wire.IsNull(dec) {
				if _, err := dec.ReadToken(); err != nil {
					return wire.In("request_id", err)
				}
			} else {
				var value ReportedString
				if err := value.UnmarshalJSONFrom(dec); err != nil {
					return wire.In("request_id", err)
				}
				v.RequestID = &value
			}
		case "requestId":
			if wire.IsNull(dec) {
				if _, err := dec.ReadToken(); err != nil {
					return wire.In("requestId", err)
				}
			} else {
				var value ReportedString
				if err := value.UnmarshalJSONFrom(dec); err != nil {
					return wire.In("requestId", err)
				}
				v.RequestIDCamel = &value
			}
		default:
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
	return nil
}

// validate checks the rules of the fields of ResponsesVendorError, and reports every one that
// is broken.
func (ResponsesVendorError) validate() error {
	return nil
}

// UnmarshalJSONFrom decodes the JSON object of ResponsesMessage: it ignores a member that
// the type does not have, and refuses a required member that is missing, a
// null, and a value of another JSON kind than the member's, naming the member.
func (v *ResponsesMessage) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = ResponsesMessage{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "content":
			if wire.IsNull(dec) {
				if _, err := dec.ReadToken(); err != nil {
					return wire.In("content", err)
				}
			} else {
				var value []jsontext.Value
				if err := wire.BeginArray(dec); err != nil {
					return wire.In("content", err)
				}
				items0 := []jsontext.Value{}
				for {
					more, err := wire.NextElement(dec)
					if err != nil {
						return wire.In("content", err)
					}
					if !more {
						break
					}
					var element0 jsontext.Value
					{
						raw, err := wire.ReadRaw(dec)
						if err != nil {
							return wire.In("content", wire.In(wire.Index(len(items0)), err))
						}
						element0 = raw
					}
					items0 = append(items0, element0)
				}
				value = items0
				v.Content = &value
			}
		default:
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
	return nil
}

// validate checks the rules of the fields of ResponsesMessage, and reports every one that
// is broken.
func (ResponsesMessage) validate() error {
	return nil
}

// UnmarshalJSONFrom decodes the JSON object of ResponsesOutputText: it ignores a member that
// the type does not have, and refuses a required member that is missing, a
// null, and a value of another JSON kind than the member's, naming the member.
func (v *ResponsesOutputText) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = ResponsesOutputText{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "text":
			seen |= 1 << 0
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("text", err)
			}
			v.Text = s
		default:
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("text")
	}
	return nil
}

// validate checks the rules of the fields of ResponsesOutputText, and reports every one that
// is broken.
func (ResponsesOutputText) validate() error {
	return nil
}

// UnmarshalJSONFrom decodes the JSON object of ResponsesRefusal: it ignores a member that
// the type does not have, and refuses a required member that is missing, a
// null, and a value of another JSON kind than the member's, naming the member.
func (v *ResponsesRefusal) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = ResponsesRefusal{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "refusal":
			seen |= 1 << 0
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("refusal", err)
			}
			v.Refusal = s
		default:
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("refusal")
	}
	return nil
}

// validate checks the rules of the fields of ResponsesRefusal, and reports every one that
// is broken.
func (ResponsesRefusal) validate() error {
	return nil
}

// UnmarshalJSONFrom decodes the JSON object of ResponsesFunctionCall: it ignores a member that
// the type does not have, and refuses a required member that is missing, a
// null, and a value of another JSON kind than the member's, naming the member.
func (v *ResponsesFunctionCall) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = ResponsesFunctionCall{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "id":
			if wire.IsNull(dec) {
				if _, err := dec.ReadToken(); err != nil {
					return wire.In("id", err)
				}
			} else {
				var value string
				s, err := wire.ReadString(dec)
				if err != nil {
					return wire.In("id", err)
				}
				value = s
				v.ID = &value
			}
		case "call_id":
			if wire.IsNull(dec) {
				if _, err := dec.ReadToken(); err != nil {
					return wire.In("call_id", err)
				}
			} else {
				var value string
				s, err := wire.ReadString(dec)
				if err != nil {
					return wire.In("call_id", err)
				}
				value = s
				v.CallID = &value
			}
		case "name":
			if wire.IsNull(dec) {
				if _, err := dec.ReadToken(); err != nil {
					return wire.In("name", err)
				}
			} else {
				var value string
				s, err := wire.ReadString(dec)
				if err != nil {
					return wire.In("name", err)
				}
				value = s
				v.Name = &value
			}
		case "arguments":
			if wire.IsNull(dec) {
				if _, err := dec.ReadToken(); err != nil {
					return wire.In("arguments", err)
				}
			} else {
				var value string
				s, err := wire.ReadString(dec)
				if err != nil {
					return wire.In("arguments", err)
				}
				value = s
				v.Arguments = &value
			}
		default:
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
	return nil
}

// validate checks the rules of the fields of ResponsesFunctionCall, and reports every one that
// is broken.
func (ResponsesFunctionCall) validate() error {
	return nil
}

// UnmarshalJSONFrom decodes the JSON object of ReasoningItem: it refuses a member that
// the type does not have, a required member that is missing, a null, and a
// value of another JSON kind than the member's, naming the member.
func (v *ReasoningItem) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = ReasoningItem{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "type":
			seen |= 1 << 0
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("type", err)
			}
			v.Type = s
		case "id":
			if wire.IsNull(dec) {
				if _, err := dec.ReadToken(); err != nil {
					return wire.In("id", err)
				}
			} else {
				var value string
				s, err := wire.ReadString(dec)
				if err != nil {
					return wire.In("id", err)
				}
				value = s
				v.ID = &value
			}
		case "summary":
			if wire.IsNull(dec) {
				if _, err := dec.ReadToken(); err != nil {
					return wire.In("summary", err)
				}
			} else {
				var value []ReasoningPart
				if err := wire.BeginArray(dec); err != nil {
					return wire.In("summary", err)
				}
				items0 := []ReasoningPart{}
				for {
					more, err := wire.NextElement(dec)
					if err != nil {
						return wire.In("summary", err)
					}
					if !more {
						break
					}
					var element0 ReasoningPart
					{
						if err := element0.UnmarshalJSONFrom(dec); err != nil {
							return wire.In("summary", wire.In(wire.Index(len(items0)), err))
						}
					}
					items0 = append(items0, element0)
				}
				value = items0
				v.Summary = &value
			}
		case "content":
			if wire.IsNull(dec) {
				if _, err := dec.ReadToken(); err != nil {
					return wire.In("content", err)
				}
			} else {
				var value []ReasoningPart
				if err := wire.BeginArray(dec); err != nil {
					return wire.In("content", err)
				}
				items0 := []ReasoningPart{}
				for {
					more, err := wire.NextElement(dec)
					if err != nil {
						return wire.In("content", err)
					}
					if !more {
						break
					}
					var element0 ReasoningPart
					{
						if err := element0.UnmarshalJSONFrom(dec); err != nil {
							return wire.In("content", wire.In(wire.Index(len(items0)), err))
						}
					}
					items0 = append(items0, element0)
				}
				value = items0
				v.Content = &value
			}
		case "encrypted_content":
			if wire.IsNull(dec) {
				if _, err := dec.ReadToken(); err != nil {
					return wire.In("encrypted_content", err)
				}
			} else {
				var value string
				s, err := wire.ReadString(dec)
				if err != nil {
					return wire.In("encrypted_content", err)
				}
				value = s
				v.EncryptedContent = &value
			}
		default:
			raw, err := wire.ReadRaw(dec)
			if err != nil {
				return wire.In(name, err)
			}
			v.Extra = append(v.Extra, wire.Member{Name: name, Value: raw})
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("type")
	}
	return nil
}

// MarshalJSONTo encodes ReasoningItem as a JSON object with the members of the structs
// it embeds among its own.
func (v ReasoningItem) MarshalJSONTo(enc *jsontext.Encoder) error {
	if err := wire.CheckUnknown(v.Extra, "type", "id", "summary", "content", "encrypted_content"); err != nil {
		return err
	}
	extra, err := v.Extra.JSON()
	if err != nil {
		return err
	}
	return json.MarshalEncode(enc, struct {
		Type             string           `json:"type"`
		ID               *string          `json:"id,omitzero"`
		Summary          *[]ReasoningPart `json:"summary,omitzero"`
		Content          *[]ReasoningPart `json:"content,omitzero"`
		EncryptedContent *string          `json:"encrypted_content,omitzero"`
		Extra            jsontext.Value   `json:",embed"`
	}{v.Type, v.ID, v.Summary, v.Content, v.EncryptedContent, extra})
}

// validate checks the rules of the fields of ReasoningItem, and reports every one that
// is broken.
func (v ReasoningItem) validate() error {
	var r wire.Report
	r.EqString("type", v.Type, "reasoning")
	if v.Summary != nil {
		{
			var group0 wire.Report
			for i, e := range *v.Summary {
				group0.Nest(wire.Index(i), e.validate())
			}
			r.Nest("summary", group0.Err())
		}
	}
	if v.Content != nil {
		{
			var group0 wire.Report
			for i, e := range *v.Content {
				group0.Nest(wire.Index(i), e.validate())
			}
			r.Nest("content", group0.Err())
		}
	}
	r.Check("", wire.CheckUnknown(v.Extra, "type", "id", "summary", "content", "encrypted_content"))
	return r.Err()
}

// UnmarshalJSONFrom decodes the JSON object of ReasoningPart: it refuses a member that
// the type does not have, a required member that is missing, a null, and a
// value of another JSON kind than the member's, naming the member.
func (v *ReasoningPart) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = ReasoningPart{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "text":
			seen |= 1 << 0
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("text", err)
			}
			v.Text = s
		default:
			raw, err := wire.ReadRaw(dec)
			if err != nil {
				return wire.In(name, err)
			}
			v.Extra = append(v.Extra, wire.Member{Name: name, Value: raw})
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("text")
	}
	return nil
}

// MarshalJSONTo encodes ReasoningPart as a JSON object with the members of the structs
// it embeds among its own.
func (v ReasoningPart) MarshalJSONTo(enc *jsontext.Encoder) error {
	if err := wire.CheckUnknown(v.Extra, "text"); err != nil {
		return err
	}
	extra, err := v.Extra.JSON()
	if err != nil {
		return err
	}
	return json.MarshalEncode(enc, struct {
		Text  string         `json:"text"`
		Extra jsontext.Value `json:",embed"`
	}{v.Text, extra})
}

// validate checks the rules of the fields of ReasoningPart, and reports every one that
// is broken.
func (v ReasoningPart) validate() error {
	var r wire.Report
	r.Check("", wire.CheckUnknown(v.Extra, "text"))
	return r.Err()
}
