// Code generated by wiregen; DO NOT EDIT.

package codex

import (
	"encoding/json/jsontext"

	"github.com/wspl/demi/go/internal/wire"
)

// UnmarshalJSONFrom decodes the JSON object of envelope: it ignores a member that
// the type does not have, and refuses a required member that is missing, a
// null, and a value of another JSON kind than the member's, naming the member.
func (v *envelope) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = envelope{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "type":
			if wire.IsNull(dec) {
				if _, err := dec.ReadToken(); err != nil {
					return wire.In("type", err)
				}
			} else {
				var value string
				s, err := wire.ReadString(dec)
				if err != nil {
					return wire.In("type", err)
				}
				value = s
				v.Type = &value
			}
		case "event":
			if wire.IsNull(dec) {
				if _, err := dec.ReadToken(); err != nil {
					return wire.In("event", err)
				}
			} else {
				var value map[string]jsontext.Value
				if err := wire.BeginObject(dec); err != nil {
					return wire.In("event", err)
				}
				entries0 := map[string]jsontext.Value{}
				for {
					key0, more, err := wire.NextMember(dec)
					if err != nil {
						return wire.In("event", err)
					}
					if !more {
						break
					}
					var element0 jsontext.Value
					{
						raw, err := wire.ReadRaw(dec)
						if err != nil {
							return wire.In("event", wire.In(wire.Key(key0), err))
						}
						element0 = raw
					}
					entries0[key0] = element0
				}
				value = entries0
				v.Event = &value
			}
		case "response":
			if wire.IsNull(dec) {
				if _, err := dec.ReadToken(); err != nil {
					return wire.In("response", err)
				}
			} else {
				var value jsontext.Value
				raw, err := wire.ReadRaw(dec)
				if err != nil {
					return wire.In("response", err)
				}
				value = raw
				v.Response = &value
			}
		default:
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
	return nil
}

// validate checks the rules of the fields of envelope, and reports every one that
// is broken.
func (envelope) validate() error {
	return nil
}
