// Code generated by wiregen; DO NOT EDIT.

package core

import (
	"encoding/json/jsontext"
	"encoding/json/v2"
	"fmt"

	"github.com/wspl/demi/go/internal/wire"
)

// UnmarshalJSONFrom decodes the JSON object of AccountInfo: it ignores a member that
// the type does not have, and refuses a required member that is missing, a
// null, and a value of another JSON kind than the member's, naming the member.
func (v *AccountInfo) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = AccountInfo{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "id":
			seen |= 1 << 0
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("id", err)
			}
			v.ID = s
		case "label":
			seen |= 1 << 1
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("label", err)
			}
			v.Label = s
		case "detail":
			seen |= 1 << 2
			if wire.IsNull(dec) {
				if _, err := dec.ReadToken(); err != nil {
					return wire.In("detail", err)
				}
			} else {
				var value string
				s, err := wire.ReadString(dec)
				if err != nil {
					return wire.In("detail", err)
				}
				value = s
				v.Detail = &value
			}
		case "updatedAt":
			seen |= 1 << 3
			if wire.IsNull(dec) {
				if _, err := dec.ReadToken(); err != nil {
					return wire.In("updatedAt", err)
				}
			} else {
				var value Timestamp
				if err := value.UnmarshalJSONFrom(dec); err != nil {
					return wire.In("updatedAt", err)
				}
				v.UpdatedAt = &value
			}
		default:
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("id")
	}
	if seen&(1<<1) == 0 {
		return wire.Required("label")
	}
	if seen&(1<<2) == 0 {
		return wire.Required("detail")
	}
	if seen&(1<<3) == 0 {
		return wire.Required("updatedAt")
	}
	return nil
}

// validate checks the rules of the fields of AccountInfo, and reports every one that
// is broken.
func (v AccountInfo) validate() error {
	var r wire.Report
	if v.UpdatedAt != nil {
		r.Check("updatedAt", Validate((*v.UpdatedAt)))
	}
	return r.Err()
}

// UnmarshalJSONFrom decodes the JSON object of LoginPending: it ignores a member that
// the type does not have, and refuses a required member that is missing, a
// null, and a value of another JSON kind than the member's, naming the member.
func (v *LoginPending) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = LoginPending{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "verificationUrl":
			seen |= 1 << 0
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("verificationUrl", err)
			}
			v.VerificationURL = s
		case "userCode":
			seen |= 1 << 1
			if wire.IsNull(dec) {
				if _, err := dec.ReadToken(); err != nil {
					return wire.In("userCode", err)
				}
			} else {
				var value string
				s, err := wire.ReadString(dec)
				if err != nil {
					return wire.In("userCode", err)
				}
				value = s
				v.UserCode = &value
			}
		case "expiresAt":
			seen |= 1 << 2
			if wire.IsNull(dec) {
				if _, err := dec.ReadToken(); err != nil {
					return wire.In("expiresAt", err)
				}
			} else {
				var value Timestamp
				if err := value.UnmarshalJSONFrom(dec); err != nil {
					return wire.In("expiresAt", err)
				}
				v.ExpiresAt = &value
			}
		default:
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("verificationUrl")
	}
	if seen&(1<<1) == 0 {
		return wire.Required("userCode")
	}
	if seen&(1<<2) == 0 {
		return wire.Required("expiresAt")
	}
	return nil
}

// validate checks the rules of the fields of LoginPending, and reports every one that
// is broken.
func (v LoginPending) validate() error {
	var r wire.Report
	if v.ExpiresAt != nil {
		r.Check("expiresAt", Validate((*v.ExpiresAt)))
	}
	return r.Err()
}

// decodeAuthState decodes the JSON object of a AuthState, whichever variant it is.
func decodeAuthState(dec *jsontext.Decoder) (AuthState, error) {
	raw, err := wire.ReadObject(dec)
	if err != nil {
		return nil, err
	}
	tag, err := wire.Tag(raw, "status")
	if err != nil {
		return nil, err
	}
	switch tag {
	case "unknown":
		var v AuthStateUnknown
		if err := v.UnmarshalJSONFrom(wire.NewDecoder(raw)); err != nil {
			return nil, err
		}
		return v, nil
	case "authenticated":
		var v AuthStateAuthenticated
		if err := v.UnmarshalJSONFrom(wire.NewDecoder(raw)); err != nil {
			return nil, err
		}
		return v, nil
	case "unauthenticated":
		var v AuthStateUnauthenticated
		if err := v.UnmarshalJSONFrom(wire.NewDecoder(raw)); err != nil {
			return nil, err
		}
		return v, nil
	case "error":
		var v AuthStateError
		if err := v.UnmarshalJSONFrom(wire.NewDecoder(raw)); err != nil {
			return nil, err
		}
		return v, nil
	}
	return nil, wire.UnknownTag("status", "unknown", "authenticated", "unauthenticated", "error")
}

// validateAuthState checks the rules of the variant that v is.
func validateAuthState(v AuthState) error {
	switch v := v.(type) {
	case nil:
		return wire.Required("")
	case AuthStateUnknown:
		return v.validate()
	case *AuthStateUnknown:
		if v == nil {
			return fmt.Errorf("a nil %T is not a variant of AuthState", v)
		}
		return v.validate()
	case AuthStateAuthenticated:
		return v.validate()
	case *AuthStateAuthenticated:
		if v == nil {
			return fmt.Errorf("a nil %T is not a variant of AuthState", v)
		}
		return v.validate()
	case AuthStateUnauthenticated:
		return v.validate()
	case *AuthStateUnauthenticated:
		if v == nil {
			return fmt.Errorf("a nil %T is not a variant of AuthState", v)
		}
		return v.validate()
	case AuthStateError:
		return v.validate()
	case *AuthStateError:
		if v == nil {
			return fmt.Errorf("a nil %T is not a variant of AuthState", v)
		}
		return v.validate()
	}
	return fmt.Errorf("%T is not a variant of AuthState", v)
}

// UnmarshalJSONFrom decodes the JSON object of AuthStateUnknown: it ignores a member that
// the type does not have, and refuses a required member that is missing, a
// null, and a value of another JSON kind than the member's, naming the member.
func (v *AuthStateUnknown) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = AuthStateUnknown{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "status":
			seen |= 1 << 0
			tag, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("status", err)
			}
			if tag != "unknown" {
				return wire.UnknownTag("status", "unknown")
			}
		case "message":
			if wire.IsNull(dec) {
				return wire.In("message", wire.Null())
			}
			var value string
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("message", err)
			}
			value = s
			v.Message = &value
		default:
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("status")
	}
	return nil
}

// MarshalJSONTo encodes AuthStateUnknown as a JSON object that starts with its tag.
func (v AuthStateUnknown) MarshalJSONTo(enc *jsontext.Encoder) error {
	return json.MarshalEncode(enc, struct {
		Tag     string  `json:"status"`
		Message *string `json:"message,omitzero"`
	}{"unknown", v.Message})
}

// validate checks the rules of the fields of AuthStateUnknown, and reports every one that
// is broken.
func (AuthStateUnknown) validate() error {
	return nil
}

// UnmarshalJSONFrom decodes the JSON object of AuthStateAuthenticated: it ignores a member that
// the type does not have, and refuses a required member that is missing, a
// null, and a value of another JSON kind than the member's, naming the member.
func (v *AuthStateAuthenticated) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = AuthStateAuthenticated{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "status":
			seen |= 1 << 0
			tag, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("status", err)
			}
			if tag != "authenticated" {
				return wire.UnknownTag("status", "authenticated")
			}
		case "accountLabel":
			if wire.IsNull(dec) {
				return wire.In("accountLabel", wire.Null())
			}
			var value string
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("accountLabel", err)
			}
			value = s
			v.AccountLabel = &value
		default:
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("status")
	}
	return nil
}

// MarshalJSONTo encodes AuthStateAuthenticated as a JSON object that starts with its tag.
func (v AuthStateAuthenticated) MarshalJSONTo(enc *jsontext.Encoder) error {
	return json.MarshalEncode(enc, struct {
		Tag          string  `json:"status"`
		AccountLabel *string `json:"accountLabel,omitzero"`
	}{"authenticated", v.AccountLabel})
}

// validate checks the rules of the fields of AuthStateAuthenticated, and reports every one that
// is broken.
func (AuthStateAuthenticated) validate() error {
	return nil
}

// UnmarshalJSONFrom decodes the JSON object of AuthStateUnauthenticated: it ignores a member that
// the type does not have, and refuses a required member that is missing, a
// null, and a value of another JSON kind than the member's, naming the member.
func (v *AuthStateUnauthenticated) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = AuthStateUnauthenticated{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "status":
			seen |= 1 << 0
			tag, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("status", err)
			}
			if tag != "unauthenticated" {
				return wire.UnknownTag("status", "unauthenticated")
			}
		case "message":
			if wire.IsNull(dec) {
				return wire.In("message", wire.Null())
			}
			var value string
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("message", err)
			}
			value = s
			v.Message = &value
		default:
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("status")
	}
	return nil
}

// MarshalJSONTo encodes AuthStateUnauthenticated as a JSON object that starts with its tag.
func (v AuthStateUnauthenticated) MarshalJSONTo(enc *jsontext.Encoder) error {
	return json.MarshalEncode(enc, struct {
		Tag     string  `json:"status"`
		Message *string `json:"message,omitzero"`
	}{"unauthenticated", v.Message})
}

// validate checks the rules of the fields of AuthStateUnauthenticated, and reports every one that
// is broken.
func (AuthStateUnauthenticated) validate() error {
	return nil
}

// UnmarshalJSONFrom decodes the JSON object of AuthStateError: it ignores a member that
// the type does not have, and refuses a required member that is missing, a
// null, and a value of another JSON kind than the member's, naming the member.
func (v *AuthStateError) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = AuthStateError{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "status":
			seen |= 1 << 0
			tag, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("status", err)
			}
			if tag != "error" {
				return wire.UnknownTag("status", "error")
			}
		case "message":
			seen |= 1 << 1
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("message", err)
			}
			v.Message = s
		default:
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("status")
	}
	if seen&(1<<1) == 0 {
		return wire.Required("message")
	}
	return nil
}

// MarshalJSONTo encodes AuthStateError as a JSON object that starts with its tag.
func (v AuthStateError) MarshalJSONTo(enc *jsontext.Encoder) error {
	return json.MarshalEncode(enc, struct {
		Tag     string `json:"status"`
		Message string `json:"message"`
	}{"error", v.Message})
}

// validate checks the rules of the fields of AuthStateError, and reports every one that
// is broken.
func (AuthStateError) validate() error {
	return nil
}

// decodeRuntimeState decodes the JSON object of a RuntimeState, whichever variant it is.
func decodeRuntimeState(dec *jsontext.Decoder) (RuntimeState, error) {
	raw, err := wire.ReadObject(dec)
	if err != nil {
		return nil, err
	}
	tag, err := wire.Tag(raw, "status")
	if err != nil {
		return nil, err
	}
	switch tag {
	case "unknown":
		var v RuntimeStateUnknown
		if err := v.UnmarshalJSONFrom(wire.NewDecoder(raw)); err != nil {
			return nil, err
		}
		return v, nil
	case "ready":
		var v RuntimeStateReady
		if err := v.UnmarshalJSONFrom(wire.NewDecoder(raw)); err != nil {
			return nil, err
		}
		return v, nil
	case "unavailable":
		var v RuntimeStateUnavailable
		if err := v.UnmarshalJSONFrom(wire.NewDecoder(raw)); err != nil {
			return nil, err
		}
		return v, nil
	case "error":
		var v RuntimeStateError
		if err := v.UnmarshalJSONFrom(wire.NewDecoder(raw)); err != nil {
			return nil, err
		}
		return v, nil
	}
	return nil, wire.UnknownTag("status", "unknown", "ready", "unavailable", "error")
}

// validateRuntimeState checks the rules of the variant that v is.
func validateRuntimeState(v RuntimeState) error {
	switch v := v.(type) {
	case nil:
		return wire.Required("")
	case RuntimeStateUnknown:
		return v.validate()
	case *RuntimeStateUnknown:
		if v == nil {
			return fmt.Errorf("a nil %T is not a variant of RuntimeState", v)
		}
		return v.validate()
	case RuntimeStateReady:
		return v.validate()
	case *RuntimeStateReady:
		if v == nil {
			return fmt.Errorf("a nil %T is not a variant of RuntimeState", v)
		}
		return v.validate()
	case RuntimeStateUnavailable:
		return v.validate()
	case *RuntimeStateUnavailable:
		if v == nil {
			return fmt.Errorf("a nil %T is not a variant of RuntimeState", v)
		}
		return v.validate()
	case RuntimeStateError:
		return v.validate()
	case *RuntimeStateError:
		if v == nil {
			return fmt.Errorf("a nil %T is not a variant of RuntimeState", v)
		}
		return v.validate()
	}
	return fmt.Errorf("%T is not a variant of RuntimeState", v)
}

// UnmarshalJSONFrom decodes the JSON object of RuntimeStateUnknown: it ignores a member that
// the type does not have, and refuses a required member that is missing, a
// null, and a value of another JSON kind than the member's, naming the member.
func (v *RuntimeStateUnknown) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = RuntimeStateUnknown{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "status":
			seen |= 1 << 0
			tag, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("status", err)
			}
			if tag != "unknown" {
				return wire.UnknownTag("status", "unknown")
			}
		case "message":
			if wire.IsNull(dec) {
				return wire.In("message", wire.Null())
			}
			var value string
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("message", err)
			}
			value = s
			v.Message = &value
		default:
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("status")
	}
	return nil
}

// MarshalJSONTo encodes RuntimeStateUnknown as a JSON object that starts with its tag.
func (v RuntimeStateUnknown) MarshalJSONTo(enc *jsontext.Encoder) error {
	return json.MarshalEncode(enc, struct {
		Tag     string  `json:"status"`
		Message *string `json:"message,omitzero"`
	}{"unknown", v.Message})
}

// validate checks the rules of the fields of RuntimeStateUnknown, and reports every one that
// is broken.
func (RuntimeStateUnknown) validate() error {
	return nil
}

// UnmarshalJSONFrom decodes the JSON object of RuntimeStateReady: it ignores a member that
// the type does not have, and refuses a required member that is missing, a
// null, and a value of another JSON kind than the member's, naming the member.
func (v *RuntimeStateReady) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = RuntimeStateReady{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "status":
			seen |= 1 << 0
			tag, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("status", err)
			}
			if tag != "ready" {
				return wire.UnknownTag("status", "ready")
			}
		case "message":
			if wire.IsNull(dec) {
				return wire.In("message", wire.Null())
			}
			var value string
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("message", err)
			}
			value = s
			v.Message = &value
		default:
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("status")
	}
	return nil
}

// MarshalJSONTo encodes RuntimeStateReady as a JSON object that starts with its tag.
func (v RuntimeStateReady) MarshalJSONTo(enc *jsontext.Encoder) error {
	return json.MarshalEncode(enc, struct {
		Tag     string  `json:"status"`
		Message *string `json:"message,omitzero"`
	}{"ready", v.Message})
}

// validate checks the rules of the fields of RuntimeStateReady, and reports every one that
// is broken.
func (RuntimeStateReady) validate() error {
	return nil
}

// UnmarshalJSONFrom decodes the JSON object of RuntimeStateUnavailable: it ignores a member that
// the type does not have, and refuses a required member that is missing, a
// null, and a value of another JSON kind than the member's, naming the member.
func (v *RuntimeStateUnavailable) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = RuntimeStateUnavailable{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "status":
			seen |= 1 << 0
			tag, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("status", err)
			}
			if tag != "unavailable" {
				return wire.UnknownTag("status", "unavailable")
			}
		case "message":
			seen |= 1 << 1
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("message", err)
			}
			v.Message = s
		default:
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("status")
	}
	if seen&(1<<1) == 0 {
		return wire.Required("message")
	}
	return nil
}

// MarshalJSONTo encodes RuntimeStateUnavailable as a JSON object that starts with its tag.
func (v RuntimeStateUnavailable) MarshalJSONTo(enc *jsontext.Encoder) error {
	return json.MarshalEncode(enc, struct {
		Tag     string `json:"status"`
		Message string `json:"message"`
	}{"unavailable", v.Message})
}

// validate checks the rules of the fields of RuntimeStateUnavailable, and reports every one that
// is broken.
func (RuntimeStateUnavailable) validate() error {
	return nil
}

// UnmarshalJSONFrom decodes the JSON object of RuntimeStateError: it ignores a member that
// the type does not have, and refuses a required member that is missing, a
// null, and a value of another JSON kind than the member's, naming the member.
func (v *RuntimeStateError) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = RuntimeStateError{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "status":
			seen |= 1 << 0
			tag, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("status", err)
			}
			if tag != "error" {
				return wire.UnknownTag("status", "error")
			}
		case "message":
			seen |= 1 << 1
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("message", err)
			}
			v.Message = s
		default:
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("status")
	}
	if seen&(1<<1) == 0 {
		return wire.Required("message")
	}
	return nil
}

// MarshalJSONTo encodes RuntimeStateError as a JSON object that starts with its tag.
func (v RuntimeStateError) MarshalJSONTo(enc *jsontext.Encoder) error {
	return json.MarshalEncode(enc, struct {
		Tag     string `json:"status"`
		Message string `json:"message"`
	}{"error", v.Message})
}

// validate checks the rules of the fields of RuntimeStateError, and reports every one that
// is broken.
func (RuntimeStateError) validate() error {
	return nil
}
