// Code generated by wiregen; DO NOT EDIT.

package core

import (
	"encoding/json/jsontext"
	"encoding/json/v2"
	"fmt"

	"github.com/wspl/demi/go/internal/wire"
)

// UnmarshalJSONFrom decodes the JSON object of ShellToolView: it refuses a member that
// the type does not have, a required member that is missing, a null, and a
// value of another JSON kind than the member's, naming the member.
func (v *ShellToolView) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = ShellToolView{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "status":
			seen |= 1 << 0
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("status", err)
			}
			v.Status = ShellViewStatus(s)
		case "shellId":
			seen |= 1 << 1
			if err := v.ShellID.UnmarshalJSONFrom(dec); err != nil {
				return wire.In("shellId", err)
			}
		case "commandId":
			seen |= 1 << 2
			if err := v.CommandID.UnmarshalJSONFrom(dec); err != nil {
				return wire.In("commandId", err)
			}
		case "exitCode":
			if wire.IsNull(dec) {
				return wire.In("exitCode", wire.Null())
			}
			var value int32
			n, err := wire.ReadInt(dec, 32)
			if err != nil {
				return wire.In("exitCode", err)
			}
			value = int32(n)
			v.ExitCode = &value
		case "runningMs":
			seen |= 1 << 4
			n, err := wire.ReadUint(dec, 64)
			if err != nil {
				return wire.In("runningMs", err)
			}
			v.RunningMs = n
		case "idleMs":
			seen |= 1 << 5
			n, err := wire.ReadUint(dec, 64)
			if err != nil {
				return wire.In("idleMs", err)
			}
			v.IdleMs = n
		case "chunks":
			seen |= 1 << 6
			if err := wire.BeginArray(dec); err != nil {
				return wire.In("chunks", err)
			}
			items0 := []OutputChunk{}
			for {
				more, err := wire.NextElement(dec)
				if err != nil {
					return wire.In("chunks", err)
				}
				if !more {
					break
				}
				var element0 OutputChunk
				{
					if err := element0.UnmarshalJSONFrom(dec); err != nil {
						return wire.In("chunks", wire.In(wire.Index(len(items0)), err))
					}
				}
				items0 = append(items0, element0)
			}
			v.Chunks = items0
		case "viewTruncated":
			seen |= 1 << 7
			b, err := wire.ReadBool(dec)
			if err != nil {
				return wire.In("viewTruncated", err)
			}
			v.ViewTruncated = b
		case "files":
			if wire.IsNull(dec) {
				return wire.In("files", wire.Null())
			}
			var value []EditedFile
			if err := wire.BeginArray(dec); err != nil {
				return wire.In("files", err)
			}
			items0 := []EditedFile{}
			for {
				more, err := wire.NextElement(dec)
				if err != nil {
					return wire.In("files", err)
				}
				if !more {
					break
				}
				var element0 EditedFile
				{
					if err := element0.UnmarshalJSONFrom(dec); err != nil {
						return wire.In("files", wire.In(wire.Index(len(items0)), err))
					}
				}
				items0 = append(items0, element0)
			}
			value = items0
			v.Files = &value
		case "filesTruncated":
			if wire.IsNull(dec) {
				return wire.In("filesTruncated", wire.Null())
			}
			var value bool
			b, err := wire.ReadBool(dec)
			if err != nil {
				return wire.In("filesTruncated", err)
			}
			value = b
			v.FilesTruncated = &value
		default:
			return wire.Unknown(name)
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("status")
	}
	if seen&(1<<1) == 0 {
		return wire.Required("shellId")
	}
	if seen&(1<<2) == 0 {
		return wire.Required("commandId")
	}
	if seen&(1<<4) == 0 {
		return wire.Required("runningMs")
	}
	if seen&(1<<5) == 0 {
		return wire.Required("idleMs")
	}
	if seen&(1<<6) == 0 {
		return wire.Required("chunks")
	}
	if seen&(1<<7) == 0 {
		return wire.Required("viewTruncated")
	}
	return nil
}

// validate checks the rules of the fields of ShellToolView, and reports every one that
// is broken.
func (v ShellToolView) validate() error {
	var r wire.Report
	r.OneOf("status", string(v.Status), "running", "exited", "aborted")
	r.Check("shellId", Validate(v.ShellID))
	r.Check("commandId", Validate(v.CommandID))
	r.Uint("runningMs", uint64(v.RunningMs), wire.AtMost(int64(MaxSafeInteger)))
	r.Uint("idleMs", uint64(v.IdleMs), wire.AtMost(int64(MaxSafeInteger)))
	{
		var group0 wire.Report
		for i, e := range v.Chunks {
			group0.Nest(wire.Index(i), e.validate())
		}
		r.Nest("chunks", group0.Err())
	}
	if v.Files != nil {
		{
			var group0 wire.Report
			for i, e := range *v.Files {
				group0.Nest(wire.Index(i), e.validate())
			}
			r.Nest("files", group0.Err())
		}
	}
	return r.Err()
}

// UnmarshalJSONFrom decodes the JSON object of OutputChunk: it refuses a member that
// the type does not have, a required member that is missing, a null, and a
// value of another JSON kind than the member's, naming the member.
func (v *OutputChunk) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = OutputChunk{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "stream":
			seen |= 1 << 0
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("stream", err)
			}
			v.Stream = StreamKind(s)
		case "text":
			seen |= 1 << 1
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("text", err)
			}
			v.Text = s
		default:
			return wire.Unknown(name)
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("stream")
	}
	if seen&(1<<1) == 0 {
		return wire.Required("text")
	}
	return nil
}

// validate checks the rules of the fields of OutputChunk, and reports every one that
// is broken.
func (v OutputChunk) validate() error {
	var r wire.Report
	r.OneOf("stream", string(v.Stream), "stdout", "stderr")
	return r.Err()
}

// UnmarshalJSONFrom decodes the JSON object of EditedFile: it refuses a member that
// the type does not have, a required member that is missing, a null, and a
// value of another JSON kind than the member's, naming the member.
func (v *EditedFile) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = EditedFile{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "path":
			seen |= 1 << 0
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("path", err)
			}
			v.Path = s
		case "kind":
			seen |= 1 << 1
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("kind", err)
			}
			v.Kind = EditKind(s)
		case "added":
			seen |= 1 << 2
			n, err := wire.ReadUint(dec, 32)
			if err != nil {
				return wire.In("added", err)
			}
			v.Added = uint32(n)
		case "removed":
			seen |= 1 << 3
			n, err := wire.ReadUint(dec, 32)
			if err != nil {
				return wire.In("removed", err)
			}
			v.Removed = uint32(n)
		case "edits":
			seen |= 1 << 4
			if err := wire.BeginArray(dec); err != nil {
				return wire.In("edits", err)
			}
			items0 := []EditSegment{}
			for {
				more, err := wire.NextElement(dec)
				if err != nil {
					return wire.In("edits", err)
				}
				if !more {
					break
				}
				var element0 EditSegment
				{
					if err := element0.UnmarshalJSONFrom(dec); err != nil {
						return wire.In("edits", wire.In(wire.Index(len(items0)), err))
					}
				}
				items0 = append(items0, element0)
			}
			v.Edits = items0
		default:
			return wire.Unknown(name)
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("path")
	}
	if seen&(1<<1) == 0 {
		return wire.Required("kind")
	}
	if seen&(1<<2) == 0 {
		return wire.Required("added")
	}
	if seen&(1<<3) == 0 {
		return wire.Required("removed")
	}
	if seen&(1<<4) == 0 {
		return wire.Required("edits")
	}
	return nil
}

// validate checks the rules of the fields of EditedFile, and reports every one that
// is broken.
func (v EditedFile) validate() error {
	var r wire.Report
	r.Chars("path", v.Path, wire.AtLeast(1))
	r.OneOf("kind", string(v.Kind), "added", "modified")
	r.Items("edits", len(v.Edits), wire.AtLeast(1))
	{
		var group0 wire.Report
		for i, e := range v.Edits {
			group0.Nest(wire.Index(i), e.validate())
		}
		r.Nest("edits", group0.Err())
	}
	return r.Err()
}

// UnmarshalJSONFrom decodes the JSON object of EditSegment: it refuses a member that
// the type does not have, a required member that is missing, a null, and a
// value of another JSON kind than the member's, naming the member.
func (v *EditSegment) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = EditSegment{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "copies":
			if wire.IsNull(dec) {
				return wire.In("copies", wire.Null())
			}
			var value EditCopies
			if err := value.UnmarshalJSONFrom(dec); err != nil {
				return wire.In("copies", err)
			}
			v.Copies = &value
		default:
			return wire.Unknown(name)
		}
	}
	return nil
}

// validate checks the rules of the fields of EditSegment, and reports every one that
// is broken.
func (v EditSegment) validate() error {
	var r wire.Report
	if v.Copies != nil {
		r.Nest("copies", (*v.Copies).validate())
	}
	return r.Err()
}

// UnmarshalJSONFrom decodes the JSON object of EditCopies: it refuses a member that
// the type does not have, a required member that is missing, a null, and a
// value of another JSON kind than the member's, naming the member.
func (v *EditCopies) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = EditCopies{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "original":
			seen |= 1 << 0
			if err := v.Original.UnmarshalJSONFrom(dec); err != nil {
				return wire.In("original", err)
			}
		case "modified":
			seen |= 1 << 1
			if err := v.Modified.UnmarshalJSONFrom(dec); err != nil {
				return wire.In("modified", err)
			}
		default:
			return wire.Unknown(name)
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("original")
	}
	if seen&(1<<1) == 0 {
		return wire.Required("modified")
	}
	return nil
}

// validate checks the rules of the fields of EditCopies, and reports every one that
// is broken.
func (v EditCopies) validate() error {
	var r wire.Report
	r.Check("original", Validate(v.Original))
	r.Check("modified", Validate(v.Modified))
	return r.Err()
}

// UnmarshalJSONFrom decodes the JSON object of StreamView: it ignores a member that
// the type does not have, and refuses a required member that is missing, a
// null, and a value of another JSON kind than the member's, naming the member.
func (v *StreamView) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = StreamView{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "offset":
			seen |= 1 << 0
			n, err := wire.ReadUint(dec, 64)
			if err != nil {
				return wire.In("offset", err)
			}
			v.Offset = n
		case "delta":
			seen |= 1 << 1
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("delta", err)
			}
			v.Delta = s
		case "tail":
			seen |= 1 << 2
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("tail", err)
			}
			v.Tail = s
		case "bytes":
			seen |= 1 << 3
			n, err := wire.ReadUint(dec, 64)
			if err != nil {
				return wire.In("bytes", err)
			}
			v.Bytes = n
		case "truncated":
			seen |= 1 << 4
			b, err := wire.ReadBool(dec)
			if err != nil {
				return wire.In("truncated", err)
			}
			v.Truncated = b
		default:
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("offset")
	}
	if seen&(1<<1) == 0 {
		return wire.Required("delta")
	}
	if seen&(1<<2) == 0 {
		return wire.Required("tail")
	}
	if seen&(1<<3) == 0 {
		return wire.Required("bytes")
	}
	if seen&(1<<4) == 0 {
		return wire.Required("truncated")
	}
	return nil
}

// validate checks the rules of the fields of StreamView, and reports every one that
// is broken.
func (v StreamView) validate() error {
	var r wire.Report
	r.Uint("offset", uint64(v.Offset), wire.AtMost(int64(MaxSafeInteger)))
	r.Uint("bytes", uint64(v.Bytes), wire.AtMost(int64(MaxSafeInteger)))
	return r.Err()
}

// UnmarshalJSONFrom decodes the JSON object of OutputView: it ignores a member that
// the type does not have, and refuses a required member that is missing, a
// null, and a value of another JSON kind than the member's, naming the member.
func (v *OutputView) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = OutputView{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "offset":
			seen |= 1 << 0
			n, err := wire.ReadUint(dec, 64)
			if err != nil {
				return wire.In("offset", err)
			}
			v.Offset = n
		case "line":
			seen |= 1 << 1
			n, err := wire.ReadUint(dec, 64)
			if err != nil {
				return wire.In("line", err)
			}
			v.Line = n
		case "text":
			seen |= 1 << 2
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("text", err)
			}
			v.Text = s
		case "tail":
			seen |= 1 << 3
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("tail", err)
			}
			v.Tail = s
		case "chunks":
			seen |= 1 << 4
			if err := wire.BeginArray(dec); err != nil {
				return wire.In("chunks", err)
			}
			items0 := []OutputChunk{}
			for {
				more, err := wire.NextElement(dec)
				if err != nil {
					return wire.In("chunks", err)
				}
				if !more {
					break
				}
				var element0 OutputChunk
				{
					if err := element0.UnmarshalJSONFrom(dec); err != nil {
						return wire.In("chunks", wire.In(wire.Index(len(items0)), err))
					}
				}
				items0 = append(items0, element0)
			}
			v.Chunks = items0
		case "bytes":
			seen |= 1 << 5
			n, err := wire.ReadUint(dec, 64)
			if err != nil {
				return wire.In("bytes", err)
			}
			v.Bytes = n
		case "truncated":
			seen |= 1 << 6
			b, err := wire.ReadBool(dec)
			if err != nil {
				return wire.In("truncated", err)
			}
			v.Truncated = b
		default:
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("offset")
	}
	if seen&(1<<1) == 0 {
		return wire.Required("line")
	}
	if seen&(1<<2) == 0 {
		return wire.Required("text")
	}
	if seen&(1<<3) == 0 {
		return wire.Required("tail")
	}
	if seen&(1<<4) == 0 {
		return wire.Required("chunks")
	}
	if seen&(1<<5) == 0 {
		return wire.Required("bytes")
	}
	if seen&(1<<6) == 0 {
		return wire.Required("truncated")
	}
	return nil
}

// validate checks the rules of the fields of OutputView, and reports every one that
// is broken.
func (v OutputView) validate() error {
	var r wire.Report
	r.Uint("offset", uint64(v.Offset), wire.AtMost(int64(MaxSafeInteger)))
	r.Uint("line", uint64(v.Line), wire.AtMost(int64(MaxSafeInteger)))
	{
		var group0 wire.Report
		for i, e := range v.Chunks {
			group0.Nest(wire.Index(i), e.validate())
		}
		r.Nest("chunks", group0.Err())
	}
	r.Uint("bytes", uint64(v.Bytes), wire.AtMost(int64(MaxSafeInteger)))
	return r.Err()
}

// UnmarshalJSONFrom decodes the JSON object of BinaryStdout: it ignores a member that
// the type does not have, and refuses a required member that is missing, a
// null, and a value of another JSON kind than the member's, naming the member.
func (v *BinaryStdout) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = BinaryStdout{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "truncated":
			seen |= 1 << 0
			b, err := wire.ReadBool(dec)
			if err != nil {
				return wire.In("truncated", err)
			}
			v.Truncated = b
		case "totalBytes":
			seen |= 1 << 1
			n, err := wire.ReadUint(dec, 64)
			if err != nil {
				return wire.In("totalBytes", err)
			}
			v.TotalBytes = n
		case "limitBytes":
			seen |= 1 << 2
			n, err := wire.ReadUint(dec, 64)
			if err != nil {
				return wire.In("limitBytes", err)
			}
			v.LimitBytes = n
		default:
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("truncated")
	}
	if seen&(1<<1) == 0 {
		return wire.Required("totalBytes")
	}
	if seen&(1<<2) == 0 {
		return wire.Required("limitBytes")
	}
	return nil
}

// validate checks the rules of the fields of BinaryStdout, and reports every one that
// is broken.
func (v BinaryStdout) validate() error {
	var r wire.Report
	r.Uint("totalBytes", uint64(v.TotalBytes), wire.AtMost(int64(MaxSafeInteger)))
	r.Uint("limitBytes", uint64(v.LimitBytes), wire.AtMost(int64(MaxSafeInteger)))
	return r.Err()
}

// decodeToolView decodes the JSON object of a ToolView, whichever variant it is.
func decodeToolView(dec *jsontext.Decoder) (ToolView, error) {
	raw, err := wire.ReadObject(dec)
	if err != nil {
		return nil, err
	}
	tag, err := wire.Tag(raw, "kind")
	if err != nil {
		return nil, err
	}
	switch tag {
	case "shell":
		var v ToolViewShell
		if err := v.UnmarshalJSONFrom(wire.NewDecoder(raw)); err != nil {
			return nil, err
		}
		return v, nil
	case "repeated_shell_exec":
		var v ToolViewRepeatedShellExec
		if err := v.UnmarshalJSONFrom(wire.NewDecoder(raw)); err != nil {
			return nil, err
		}
		return v, nil
	case "yield_wakeup":
		var v ToolViewYieldWakeup
		if err := v.UnmarshalJSONFrom(wire.NewDecoder(raw)); err != nil {
			return nil, err
		}
		return v, nil
	}
	return nil, wire.UnknownTag("kind", "shell", "repeated_shell_exec", "yield_wakeup")
}

// validateToolView checks the rules of the variant that v is.
func validateToolView(v ToolView) error {
	switch v := v.(type) {
	case nil:
		return wire.Required("")
	case ToolViewShell:
		return v.validate()
	case *ToolViewShell:
		if v == nil {
			return fmt.Errorf("a nil %T is not a variant of ToolView", v)
		}
		return v.validate()
	case ToolViewRepeatedShellExec:
		return v.validate()
	case *ToolViewRepeatedShellExec:
		if v == nil {
			return fmt.Errorf("a nil %T is not a variant of ToolView", v)
		}
		return v.validate()
	case ToolViewYieldWakeup:
		return v.validate()
	case *ToolViewYieldWakeup:
		if v == nil {
			return fmt.Errorf("a nil %T is not a variant of ToolView", v)
		}
		return v.validate()
	}
	return fmt.Errorf("%T is not a variant of ToolView", v)
}

// UnmarshalJSONFrom decodes the JSON object of ToolViewShell: it refuses a member that
// the type does not have, a required member that is missing, a null, and a
// value of another JSON kind than the member's, naming the member.
func (v *ToolViewShell) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = ToolViewShell{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "kind":
			seen |= 1 << 0
			tag, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("kind", err)
			}
			if tag != "shell" {
				return wire.UnknownTag("kind", "shell")
			}
		case "status":
			seen |= 1 << 1
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("status", err)
			}
			v.Status = ShellViewStatus(s)
		case "shellId":
			seen |= 1 << 2
			if err := v.ShellID.UnmarshalJSONFrom(dec); err != nil {
				return wire.In("shellId", err)
			}
		case "commandId":
			seen |= 1 << 3
			if err := v.CommandID.UnmarshalJSONFrom(dec); err != nil {
				return wire.In("commandId", err)
			}
		case "exitCode":
			if wire.IsNull(dec) {
				return wire.In("exitCode", wire.Null())
			}
			var value int32
			n, err := wire.ReadInt(dec, 32)
			if err != nil {
				return wire.In("exitCode", err)
			}
			value = int32(n)
			v.ExitCode = &value
		case "runningMs":
			seen |= 1 << 5
			n, err := wire.ReadUint(dec, 64)
			if err != nil {
				return wire.In("runningMs", err)
			}
			v.RunningMs = n
		case "idleMs":
			seen |= 1 << 6
			n, err := wire.ReadUint(dec, 64)
			if err != nil {
				return wire.In("idleMs", err)
			}
			v.IdleMs = n
		case "chunks":
			seen |= 1 << 7
			if err := wire.BeginArray(dec); err != nil {
				return wire.In("chunks", err)
			}
			items0 := []OutputChunk{}
			for {
				more, err := wire.NextElement(dec)
				if err != nil {
					return wire.In("chunks", err)
				}
				if !more {
					break
				}
				var element0 OutputChunk
				{
					if err := element0.UnmarshalJSONFrom(dec); err != nil {
						return wire.In("chunks", wire.In(wire.Index(len(items0)), err))
					}
				}
				items0 = append(items0, element0)
			}
			v.Chunks = items0
		case "viewTruncated":
			seen |= 1 << 8
			b, err := wire.ReadBool(dec)
			if err != nil {
				return wire.In("viewTruncated", err)
			}
			v.ViewTruncated = b
		case "files":
			if wire.IsNull(dec) {
				return wire.In("files", wire.Null())
			}
			var value []EditedFile
			if err := wire.BeginArray(dec); err != nil {
				return wire.In("files", err)
			}
			items0 := []EditedFile{}
			for {
				more, err := wire.NextElement(dec)
				if err != nil {
					return wire.In("files", err)
				}
				if !more {
					break
				}
				var element0 EditedFile
				{
					if err := element0.UnmarshalJSONFrom(dec); err != nil {
						return wire.In("files", wire.In(wire.Index(len(items0)), err))
					}
				}
				items0 = append(items0, element0)
			}
			value = items0
			v.Files = &value
		case "filesTruncated":
			if wire.IsNull(dec) {
				return wire.In("filesTruncated", wire.Null())
			}
			var value bool
			b, err := wire.ReadBool(dec)
			if err != nil {
				return wire.In("filesTruncated", err)
			}
			value = b
			v.FilesTruncated = &value
		default:
			return wire.Unknown(name)
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("kind")
	}
	if seen&(1<<1) == 0 {
		return wire.Required("status")
	}
	if seen&(1<<2) == 0 {
		return wire.Required("shellId")
	}
	if seen&(1<<3) == 0 {
		return wire.Required("commandId")
	}
	if seen&(1<<5) == 0 {
		return wire.Required("runningMs")
	}
	if seen&(1<<6) == 0 {
		return wire.Required("idleMs")
	}
	if seen&(1<<7) == 0 {
		return wire.Required("chunks")
	}
	if seen&(1<<8) == 0 {
		return wire.Required("viewTruncated")
	}
	return nil
}

// MarshalJSONTo encodes ToolViewShell as a JSON object that starts with its tag.
func (v ToolViewShell) MarshalJSONTo(enc *jsontext.Encoder) error {
	return json.MarshalEncode(enc, struct {
		Tag            string          `json:"kind"`
		Status         ShellViewStatus `json:"status"`
		ShellID        ShellID         `json:"shellId"`
		CommandID      CommandID       `json:"commandId"`
		ExitCode       *int32          `json:"exitCode,omitzero"`
		RunningMs      uint64          `json:"runningMs"`
		IdleMs         uint64          `json:"idleMs"`
		Chunks         []OutputChunk   `json:"chunks"`
		ViewTruncated  bool            `json:"viewTruncated"`
		Files          *[]EditedFile   `json:"files,omitzero"`
		FilesTruncated *bool           `json:"filesTruncated,omitzero"`
	}{"shell", v.Status, v.ShellID, v.CommandID, v.ExitCode, v.RunningMs, v.IdleMs, v.Chunks, v.ViewTruncated, v.Files, v.FilesTruncated})
}

// validate checks the rules of the fields of ToolViewShell, and reports every one that
// is broken.
func (v ToolViewShell) validate() error {
	var r wire.Report
	r.OneOf("status", string(v.Status), "running", "exited", "aborted")
	r.Check("shellId", Validate(v.ShellID))
	r.Check("commandId", Validate(v.CommandID))
	r.Uint("runningMs", uint64(v.RunningMs), wire.AtMost(int64(MaxSafeInteger)))
	r.Uint("idleMs", uint64(v.IdleMs), wire.AtMost(int64(MaxSafeInteger)))
	{
		var group0 wire.Report
		for i, e := range v.Chunks {
			group0.Nest(wire.Index(i), e.validate())
		}
		r.Nest("chunks", group0.Err())
	}
	if v.Files != nil {
		{
			var group0 wire.Report
			for i, e := range *v.Files {
				group0.Nest(wire.Index(i), e.validate())
			}
			r.Nest("files", group0.Err())
		}
	}
	return r.Err()
}

// UnmarshalJSONFrom decodes the JSON object of ToolViewRepeatedShellExec: it refuses a member that
// the type does not have, a required member that is missing, a null, and a
// value of another JSON kind than the member's, naming the member.
func (v *ToolViewRepeatedShellExec) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = ToolViewRepeatedShellExec{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "kind":
			seen |= 1 << 0
			tag, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("kind", err)
			}
			if tag != "repeated_shell_exec" {
				return wire.UnknownTag("kind", "repeated_shell_exec")
			}
		case "script":
			seen |= 1 << 1
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("script", err)
			}
			v.Script = s
		case "count":
			seen |= 1 << 2
			n, err := wire.ReadUint(dec, 32)
			if err != nil {
				return wire.In("count", err)
			}
			v.Count = uint32(n)
		default:
			return wire.Unknown(name)
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("kind")
	}
	if seen&(1<<1) == 0 {
		return wire.Required("script")
	}
	if seen&(1<<2) == 0 {
		return wire.Required("count")
	}
	return nil
}

// MarshalJSONTo encodes ToolViewRepeatedShellExec as a JSON object that starts with its tag.
func (v ToolViewRepeatedShellExec) MarshalJSONTo(enc *jsontext.Encoder) error {
	return json.MarshalEncode(enc, struct {
		Tag    string `json:"kind"`
		Script string `json:"script"`
		Count  uint32 `json:"count"`
	}{"repeated_shell_exec", v.Script, v.Count})
}

// validate checks the rules of the fields of ToolViewRepeatedShellExec, and reports every one that
// is broken.
func (ToolViewRepeatedShellExec) validate() error {
	return nil
}

// UnmarshalJSONFrom decodes the JSON object of ToolViewYieldWakeup: it refuses a member that
// the type does not have, a required member that is missing, a null, and a
// value of another JSON kind than the member's, naming the member.
func (v *ToolViewYieldWakeup) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = ToolViewYieldWakeup{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "kind":
			seen |= 1 << 0
			tag, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("kind", err)
			}
			if tag != "yield_wakeup" {
				return wire.UnknownTag("kind", "yield_wakeup")
			}
		case "wakeupId":
			seen |= 1 << 1
			if err := v.WakeupID.UnmarshalJSONFrom(dec); err != nil {
				return wire.In("wakeupId", err)
			}
		case "durationMs":
			seen |= 1 << 2
			n, err := wire.ReadUint(dec, 32)
			if err != nil {
				return wire.In("durationMs", err)
			}
			v.DurationMs = uint32(n)
		default:
			return wire.Unknown(name)
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("kind")
	}
	if seen&(1<<1) == 0 {
		return wire.Required("wakeupId")
	}
	if seen&(1<<2) == 0 {
		return wire.Required("durationMs")
	}
	return nil
}

// MarshalJSONTo encodes ToolViewYieldWakeup as a JSON object that starts with its tag.
func (v ToolViewYieldWakeup) MarshalJSONTo(enc *jsontext.Encoder) error {
	return json.MarshalEncode(enc, struct {
		Tag        string   `json:"kind"`
		WakeupID   WakeupID `json:"wakeupId"`
		DurationMs uint32   `json:"durationMs"`
	}{"yield_wakeup", v.WakeupID, v.DurationMs})
}

// validate checks the rules of the fields of ToolViewYieldWakeup, and reports every one that
// is broken.
func (v ToolViewYieldWakeup) validate() error {
	var r wire.Report
	r.Check("wakeupId", Validate(v.WakeupID))
	return r.Err()
}
