// Code generated by wiregen; DO NOT EDIT.

package runnerproto

import (
	"encoding/json/jsontext"

	"github.com/wspl/demi/go/internal/wire"
)

// UnmarshalJSONFrom decodes the JSON object of ManagedBoot: it refuses a member that
// the type does not have, a required member that is missing, a null, and a
// value of another JSON kind than the member's, naming the member.
func (v *ManagedBoot) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = ManagedBoot{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "backendUrl":
			seen |= 1 << 0
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("backendUrl", err)
			}
			v.BackendURL = BackendURL(s)
		case "deviceToken":
			seen |= 1 << 1
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("deviceToken", err)
			}
			v.DeviceToken = DeviceToken(s)
		default:
			return wire.Unknown(name)
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("backendUrl")
	}
	if seen&(1<<1) == 0 {
		return wire.Required("deviceToken")
	}
	return nil
}

// validate checks the rules of the fields of ManagedBoot, and reports every one that
// is broken.
func (v ManagedBoot) validate() error {
	var r wire.Report
	r.Check("backendUrl", backendURL(v.BackendURL))
	r.Check("deviceToken", deviceToken(v.DeviceToken))
	return r.Err()
}
