// Code generated by wiregen; DO NOT EDIT.

package runnerproto

import (
	"encoding/json/jsontext"
	"encoding/json/v2"
	"fmt"

	"github.com/wspl/demi/go/internal/wire"
)

// decodeKeptRecord decodes the JSON object of a KeptRecord, whichever variant it is.
func decodeKeptRecord(dec *jsontext.Decoder) (KeptRecord, error) {
	raw, err := wire.ReadObject(dec)
	if err != nil {
		return nil, err
	}
	tag, err := wire.Tag(raw, "type")
	if err != nil {
		return nil, err
	}
	switch tag {
	case "output":
		var v KeptOutput
		if err := v.UnmarshalJSONFrom(wire.NewDecoder(raw)); err != nil {
			return nil, err
		}
		return v, nil
	case "left_out":
		var v KeptLeftOut
		if err := v.UnmarshalJSONFrom(wire.NewDecoder(raw)); err != nil {
			return nil, err
		}
		return v, nil
	}
	return nil, wire.UnknownTag("type", "output", "left_out")
}

// validateKeptRecord checks the rules of the variant that v is.
func validateKeptRecord(v KeptRecord) error {
	switch v := v.(type) {
	case nil:
		return wire.Required("")
	case KeptOutput:
		return v.validate()
	case *KeptOutput:
		if v == nil {
			return fmt.Errorf("a nil %T is not a variant of KeptRecord", v)
		}
		return v.validate()
	case KeptLeftOut:
		return v.validate()
	case *KeptLeftOut:
		if v == nil {
			return fmt.Errorf("a nil %T is not a variant of KeptRecord", v)
		}
		return v.validate()
	}
	return fmt.Errorf("%T is not a variant of KeptRecord", v)
}

// UnmarshalJSONFrom decodes the JSON object of KeptOutput: it refuses a member that
// the type does not have, a required member that is missing, a null, and a
// value of another JSON kind than the member's, naming the member.
func (v *KeptOutput) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = KeptOutput{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "type":
			seen |= 1 << 0
			tag, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("type", err)
			}
			if tag != "output" {
				return wire.UnknownTag("type", "output")
			}
		case "stream":
			seen |= 1 << 1
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("stream", err)
			}
			v.Stream = OutputStream(s)
		case "bytes":
			seen |= 1 << 2
			if err := wire.BeginArray(dec); err != nil {
				return wire.In("bytes", err)
			}
			items0 := []byte{}
			for {
				more, err := wire.NextElement(dec)
				if err != nil {
					return wire.In("bytes", err)
				}
				if !more {
					break
				}
				var element0 byte
				{
					n, err := wire.ReadUint(dec, 8)
					if err != nil {
						return wire.In("bytes", wire.In(wire.Index(len(items0)), err))
					}
					element0 = byte(n)
				}
				items0 = append(items0, element0)
			}
			v.Bytes = items0
		default:
			return wire.Unknown(name)
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("type")
	}
	if seen&(1<<1) == 0 {
		return wire.Required("stream")
	}
	if seen&(1<<2) == 0 {
		return wire.Required("bytes")
	}
	return nil
}

// MarshalJSONTo encodes KeptOutput as a JSON object that starts with its tag.
func (v KeptOutput) MarshalJSONTo(enc *jsontext.Encoder) error {
	return json.MarshalEncode(enc, struct {
		Tag    string       `json:"type"`
		Stream OutputStream `json:"stream"`
		Bytes  []byte       `json:"bytes"`
	}{"output", v.Stream, v.Bytes})
}

// validate checks the rules of the fields of KeptOutput, and reports every one that
// is broken.
func (v KeptOutput) validate() error {
	var r wire.Report
	r.OneOf("stream", string(v.Stream), "stdout", "stderr")
	return r.Err()
}

// UnmarshalJSONFrom decodes the JSON object of KeptLeftOut: it refuses a member that
// the type does not have, a required member that is missing, a null, and a
// value of another JSON kind than the member's, naming the member.
func (v *KeptLeftOut) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = KeptLeftOut{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "type":
			seen |= 1 << 0
			tag, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("type", err)
			}
			if tag != "left_out" {
				return wire.UnknownTag("type", "left_out")
			}
		case "bytes":
			seen |= 1 << 1
			n, err := wire.ReadUint(dec, 64)
			if err != nil {
				return wire.In("bytes", err)
			}
			v.Bytes = n
		default:
			return wire.Unknown(name)
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("type")
	}
	if seen&(1<<1) == 0 {
		return wire.Required("bytes")
	}
	return nil
}

// MarshalJSONTo encodes KeptLeftOut as a JSON object that starts with its tag.
func (v KeptLeftOut) MarshalJSONTo(enc *jsontext.Encoder) error {
	return json.MarshalEncode(enc, struct {
		Tag   string `json:"type"`
		Bytes uint64 `json:"bytes"`
	}{"left_out", v.Bytes})
}

// validate checks the rules of the fields of KeptLeftOut, and reports every one that
// is broken.
func (KeptLeftOut) validate() error {
	return nil
}
