// Code generated by wiregen; DO NOT EDIT.

package runnerproto

import (
	"encoding/json/jsontext"
	"maps"
	"slices"

	"github.com/wspl/demi/go/commandservice"
	"github.com/wspl/demi/go/internal/wire"
)

// UnmarshalJSONFrom decodes the JSON object of Manifest: it refuses a member that
// the type does not have, a required member that is missing, a null, and a
// value of another JSON kind than the member's, naming the member.
func (v *Manifest) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = Manifest{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "hash":
			seen |= 1 << 0
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("hash", err)
			}
			v.Hash = s
		case "roots":
			seen |= 1 << 1
			if err := wire.BeginObject(dec); err != nil {
				return wire.In("roots", err)
			}
			entries0 := map[string]Root{}
			for {
				key0, more, err := wire.NextMember(dec)
				if err != nil {
					return wire.In("roots", err)
				}
				if !more {
					break
				}
				var element0 Root
				{
					if err := element0.UnmarshalJSONFrom(dec); err != nil {
						return wire.In("roots", wire.In(wire.Key(key0), err))
					}
				}
				entries0[key0] = element0
			}
			v.Roots = entries0
		case "packages":
			seen |= 1 << 2
			if err := wire.BeginObject(dec); err != nil {
				return wire.In("packages", err)
			}
			entries0 := map[string]commandservice.PackageDescriptor{}
			for {
				key0, more, err := wire.NextMember(dec)
				if err != nil {
					return wire.In("packages", err)
				}
				if !more {
					break
				}
				var element0 commandservice.PackageDescriptor
				{
					if err := element0.UnmarshalJSONFrom(dec); err != nil {
						return wire.In("packages", wire.In(wire.Key(key0), err))
					}
				}
				entries0[key0] = element0
			}
			v.Packages = entries0
		default:
			return wire.Unknown(name)
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("hash")
	}
	if seen&(1<<1) == 0 {
		return wire.Required("roots")
	}
	if seen&(1<<2) == 0 {
		return wire.Required("packages")
	}
	return nil
}

// validate checks the rules of the fields of Manifest, and reports every one that
// is broken.
func (v Manifest) validate() error {
	var r wire.Report
	{
		var group0 wire.Report
		for _, k := range slices.Sorted(maps.Keys(v.Packages)) {
			e := v.Packages[k]
			var item0 wire.Report
			item0.Check("", commandservice.Validate(e))
			group0.Nest(wire.Key(k), item0.Err())
		}
		r.Nest("packages", group0.Err())
	}
	r.Check("", v.check())
	return r.Err()
}
