// Code generated by wiregen; DO NOT EDIT.

package runnerproto

import (
	"encoding/json/jsontext"
	"encoding/json/v2"
	"fmt"
	"reflect"

	"github.com/wspl/demi/go/internal/wire"
)

// wireOptions are the options of every decode and encode of the package's wire
// types: maps are encoded in sorted key order, and each union has its own
// decoder, which json needs to decode into an interface.
var wireOptions = json.JoinOptions(
	json.Deterministic(true),
	json.WithUnmarshalers(json.JoinUnmarshalers(
		json.UnmarshalFromFunc(func(dec *jsontext.Decoder, v *KeptRecord) error {
			value, err := decodeKeptRecord(dec)
			if err != nil {
				return err
			}
			*v = value
			return nil
		}),
		json.UnmarshalFromFunc(func(dec *jsontext.Decoder, v *Inbound) error {
			value, err := decodeInbound(dec)
			if err != nil {
				return err
			}
			*v = value
			return nil
		}),
		json.UnmarshalFromFunc(func(dec *jsontext.Decoder, v *Outbound) error {
			value, err := decodeOutbound(dec)
			if err != nil {
				return err
			}
			*v = value
			return nil
		}),
		json.UnmarshalFromFunc(func(dec *jsontext.Decoder, v *ArtifactOwner) error {
			value, err := decodeArtifactOwner(dec)
			if err != nil {
				return err
			}
			*v = value
			return nil
		}),
	)),
)

// decode decodes data, one JSON document, as a T, one of the package's wire
// types, and checks its rules. A failure is an *wire.InvalidError that names the
// field and the rule, never the value.
func decode[T any](data []byte) (T, error) {
	var value T
	if err := json.Unmarshal(data, &value, wireOptions); err != nil {
		return value, wire.Refusal(err)
	}
	if err := check(value); err != nil {
		return value, err
	}
	return value, nil
}

// encode returns the JSON of value, one of the package's wire types, after
// checking it as decode would.
func encode[T any](value T) ([]byte, error) {
	if err := check(value); err != nil {
		return nil, err
	}
	data, err := json.Marshal(value, wireOptions)
	if err != nil {
		return nil, wire.Refusal(err)
	}
	return data, nil
}

// check runs the rule check of a wire type. A value that is absent (a nil
// interface, or a nil pointer) is refused as required.
func check(value any) error {
	if value == nil {
		return wire.Required("")
	}
	// A nil pointer to a wire type has methods, and calling them would panic.
	if pointer := reflect.ValueOf(value); pointer.Kind() == reflect.Pointer && pointer.IsNil() {
		return wire.Required("")
	}
	checked, ok := value.(interface{ validate() error })
	if !ok {
		return fmt.Errorf("runnerproto: %T is not a type of the wire", value)
	}
	return checked.validate()
}
