// Code generated by wiregen; DO NOT EDIT.

package packtest

import (
	"encoding/json/jsontext"

	"github.com/wspl/demi/go/internal/wire"
	"github.com/wspl/demi/go/internal/wiregen/featuretest"
)

// UnmarshalJSONFrom decodes the JSON object of Normalized: it refuses a member that
// the type does not have, a required member that is missing, a null, and a
// value of another JSON kind than the member's, naming the member.
func (v *Normalized) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = Normalized{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "label":
			seen |= 1 << 0
			if err := v.Label.UnmarshalJSONFrom(dec); err != nil {
				return wire.In("label", err)
			}
		default:
			return wire.Unknown(name)
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("label")
	}
	return nil
}

// validate checks the rules of the fields of Normalized, and reports every one that
// is broken.
func (v Normalized) validate() error {
	var r wire.Report
	r.Chars("label", string(v.Label), wire.Between(1, 3))
	r.Check("label", featuretest.ValidateTrimmed(v.Label))
	return r.Err()
}
