// Code generated by wiregen; DO NOT EDIT.

package agentdata

import (
	"encoding/json/jsontext"

	"github.com/wspl/demi/go/core"
	"github.com/wspl/demi/go/internal/wire"
)

// UnmarshalJSONFrom decodes the JSON object of CheckpointState: it refuses a member that
// the type does not have, a required member that is missing, a null, and a
// value of another JSON kind than the member's, naming the member.
func (v *CheckpointState) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = CheckpointState{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "phase":
			seen |= 1 << 0
			u, err := core.DecodeSessionPhaseJSONFrom(dec)
			if err != nil {
				return wire.In("phase", err)
			}
			v.Phase = u
		case "queue":
			seen |= 1 << 1
			if err := wire.BeginArray(dec); err != nil {
				return wire.In("queue", err)
			}
			items0 := []core.QueuedMessage{}
			for {
				more, err := wire.NextElement(dec)
				if err != nil {
					return wire.In("queue", err)
				}
				if !more {
					break
				}
				var element0 core.QueuedMessage
				{
					if err := element0.UnmarshalJSONFrom(dec); err != nil {
						return wire.In("queue", wire.In(wire.Index(len(items0)), err))
					}
				}
				items0 = append(items0, element0)
			}
			v.Queue = items0
		case "agentInputs":
			seen |= 1 << 2
			if err := wire.BeginArray(dec); err != nil {
				return wire.In("agentInputs", err)
			}
			items0 := []PendingAgentInput{}
			for {
				more, err := wire.NextElement(dec)
				if err != nil {
					return wire.In("agentInputs", err)
				}
				if !more {
					break
				}
				var element0 PendingAgentInput
				{
					if err := element0.UnmarshalJSONFrom(dec); err != nil {
						return wire.In("agentInputs", wire.In(wire.Index(len(items0)), err))
					}
				}
				items0 = append(items0, element0)
			}
			v.AgentInputs = items0
		case "wakeups":
			seen |= 1 << 3
			if err := wire.BeginArray(dec); err != nil {
				return wire.In("wakeups", err)
			}
			items0 := []ScheduledWakeup{}
			for {
				more, err := wire.NextElement(dec)
				if err != nil {
					return wire.In("wakeups", err)
				}
				if !more {
					break
				}
				var element0 ScheduledWakeup
				{
					if err := element0.UnmarshalJSONFrom(dec); err != nil {
						return wire.In("wakeups", wire.In(wire.Index(len(items0)), err))
					}
				}
				items0 = append(items0, element0)
			}
			v.Wakeups = items0
		case "cwd":
			seen |= 1 << 4
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("cwd", err)
			}
			v.Cwd = s
		case "model":
			seen |= 1 << 5
			if err := v.Model.UnmarshalJSONFrom(dec); err != nil {
				return wire.In("model", err)
			}
		case "harness":
			seen |= 1 << 6
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("harness", err)
			}
			v.Harness = s
		case "edits":
			seen |= 1 << 7
			if err := wire.BeginArray(dec); err != nil {
				return wire.In("edits", err)
			}
			items0 := []EditReceipt{}
			for {
				more, err := wire.NextElement(dec)
				if err != nil {
					return wire.In("edits", err)
				}
				if !more {
					break
				}
				var element0 EditReceipt
				{
					if err := element0.UnmarshalJSONFrom(dec); err != nil {
						return wire.In("edits", wire.In(wire.Index(len(items0)), err))
					}
				}
				items0 = append(items0, element0)
			}
			v.Edits = items0
		default:
			return wire.Unknown(name)
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("phase")
	}
	if seen&(1<<1) == 0 {
		return wire.Required("queue")
	}
	if seen&(1<<2) == 0 {
		return wire.Required("agentInputs")
	}
	if seen&(1<<3) == 0 {
		return wire.Required("wakeups")
	}
	if seen&(1<<4) == 0 {
		return wire.Required("cwd")
	}
	if seen&(1<<5) == 0 {
		return wire.Required("model")
	}
	if seen&(1<<6) == 0 {
		return wire.Required("harness")
	}
	if seen&(1<<7) == 0 {
		return wire.Required("edits")
	}
	return nil
}

// validate checks the rules of the fields of CheckpointState, and reports every one that
// is broken.
func (v CheckpointState) validate() error {
	var r wire.Report
	r.Check("phase", core.ValidateSessionPhase(v.Phase))
	{
		var group0 wire.Report
		for i, e := range v.Queue {
			var item0 wire.Report
			item0.Check("", core.Validate(e))
			group0.Nest(wire.Index(i), item0.Err())
		}
		r.Nest("queue", group0.Err())
	}
	{
		var group0 wire.Report
		for i, e := range v.AgentInputs {
			group0.Nest(wire.Index(i), e.validate())
		}
		r.Nest("agentInputs", group0.Err())
	}
	{
		var group0 wire.Report
		for i, e := range v.Wakeups {
			group0.Nest(wire.Index(i), e.validate())
		}
		r.Nest("wakeups", group0.Err())
	}
	r.Chars("cwd", v.Cwd, wire.AtLeast(1))
	r.Check("model", core.Validate(v.Model))
	r.Chars("harness", v.Harness, wire.AtLeast(1))
	{
		var group0 wire.Report
		for i, e := range v.Edits {
			group0.Nest(wire.Index(i), e.validate())
		}
		r.Nest("edits", group0.Err())
	}
	return r.Err()
}

// UnmarshalJSONFrom decodes the JSON object of PendingAgentInput: it refuses a member that
// the type does not have, a required member that is missing, a null, and a
// value of another JSON kind than the member's, naming the member.
func (v *PendingAgentInput) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = PendingAgentInput{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "turnId":
			seen |= 1 << 0
			if err := v.TurnID.UnmarshalJSONFrom(dec); err != nil {
				return wire.In("turnId", err)
			}
		case "model":
			seen |= 1 << 1
			if err := v.Model.UnmarshalJSONFrom(dec); err != nil {
				return wire.In("model", err)
			}
		case "message":
			seen |= 1 << 2
			if err := v.Message.UnmarshalJSONFrom(dec); err != nil {
				return wire.In("message", err)
			}
		default:
			return wire.Unknown(name)
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("turnId")
	}
	if seen&(1<<1) == 0 {
		return wire.Required("model")
	}
	if seen&(1<<2) == 0 {
		return wire.Required("message")
	}
	return nil
}

// validate checks the rules of the fields of PendingAgentInput, and reports every one that
// is broken.
func (v PendingAgentInput) validate() error {
	var r wire.Report
	r.Check("turnId", core.Validate(v.TurnID))
	r.Check("model", core.Validate(v.Model))
	r.Check("message", core.Validate(v.Message))
	return r.Err()
}

// UnmarshalJSONFrom decodes the JSON object of ScheduledWakeup: it refuses a member that
// the type does not have, a required member that is missing, a null, and a
// value of another JSON kind than the member's, naming the member.
func (v *ScheduledWakeup) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = ScheduledWakeup{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "id":
			seen |= 1 << 0
			if err := v.ID.UnmarshalJSONFrom(dec); err != nil {
				return wire.In("id", err)
			}
		case "durationMs":
			seen |= 1 << 1
			n, err := wire.ReadUint(dec, 32)
			if err != nil {
				return wire.In("durationMs", err)
			}
			v.DurationMs = uint32(n)
		case "dueAt":
			seen |= 1 << 2
			if wire.IsNull(dec) {
				if _, err := dec.ReadToken(); err != nil {
					return wire.In("dueAt", err)
				}
			} else {
				var value core.Timestamp
				if err := value.UnmarshalJSONFrom(dec); err != nil {
					return wire.In("dueAt", err)
				}
				v.DueAt = &value
			}
		default:
			return wire.Unknown(name)
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("id")
	}
	if seen&(1<<1) == 0 {
		return wire.Required("durationMs")
	}
	if seen&(1<<2) == 0 {
		return wire.Required("dueAt")
	}
	return nil
}

// validate checks the rules of the fields of ScheduledWakeup, and reports every one that
// is broken.
func (v ScheduledWakeup) validate() error {
	var r wire.Report
	r.Check("id", core.Validate(v.ID))
	r.Uint("durationMs", uint64(v.DurationMs), wire.AtLeast(1))
	if v.DueAt != nil {
		r.Check("dueAt", core.Validate((*v.DueAt)))
	}
	return r.Err()
}

// UnmarshalJSONFrom decodes the JSON object of EditReceipt: it refuses a member that
// the type does not have, a required member that is missing, a null, and a
// value of another JSON kind than the member's, naming the member.
func (v *EditReceipt) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = EditReceipt{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "operationId":
			seen |= 1 << 0
			if err := v.OperationID.UnmarshalJSONFrom(dec); err != nil {
				return wire.In("operationId", err)
			}
		case "digest":
			seen |= 1 << 1
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("digest", err)
			}
			v.Digest = s
		case "turnId":
			seen |= 1 << 2
			if err := v.TurnID.UnmarshalJSONFrom(dec); err != nil {
				return wire.In("turnId", err)
			}
		default:
			return wire.Unknown(name)
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("operationId")
	}
	if seen&(1<<1) == 0 {
		return wire.Required("digest")
	}
	if seen&(1<<2) == 0 {
		return wire.Required("turnId")
	}
	return nil
}

// validate checks the rules of the fields of EditReceipt, and reports every one that
// is broken.
func (v EditReceipt) validate() error {
	var r wire.Report
	r.Check("operationId", core.Validate(v.OperationID))
	r.Pattern("digest", v.Digest, DigestPattern)
	r.Check("turnId", core.Validate(v.TurnID))
	return r.Err()
}
