// Code generated by contractgen; DO NOT EDIT.
import { z } from 'zod'
export const inputSchema = z.strictObject({"data": z.record(z.string(), z.json())})
export type Input = z.infer<typeof inputSchema>
