// Code generated by contractgen; DO NOT EDIT.
package schemacheck

import (
	"encoding/json"
	"fmt"
	"github.com/wspl/demi/internal/contract"
)

func DecodeCheckedObject(data []byte) (CheckedObject, error) {
	return contract.Decode[CheckedObject](data)
}
func (v CheckedObject) Validate() error { return contractValidateCheckedObject(v, 0) }
func contractValidateCheckedObject(v CheckedObject, depth int) error {
	if depth > 1000 {
		return fmt.Errorf("validation nesting exceeds 1000")
	}
	if err := contract.Text(string(v.Value), 0, -1, ""); err != nil {
		return contract.At("value", err)
	}
	if err := validateObject(v); err != nil {
		return err
	}
	return nil
}
func (v *CheckedObject) UnmarshalJSON(data []byte) error {
	obj, err := contract.Decode[map[string]json.RawMessage](data)
	if err != nil {
		return err
	}
	var next CheckedObject
	for key := range obj {
		switch key {
		case "value":
		default:
			return contract.At(key, fmt.Errorf("unknown field"))
		}
	}
	{
		raw, ok := obj["value"]
		if !ok {
			return contract.At("value", fmt.Errorf("required field is absent"))
		}
		if ok {
			value, err := contract.Decode[string](raw)
			if err != nil {
				return contract.At("value", err)
			}
			next.Value = value
		}
	}
	if err := next.Validate(); err != nil {
		return err
	}
	*v = next
	return nil
}
func (v CheckedObject) MarshalJSON() ([]byte, error) {
	if err := v.Validate(); err != nil {
		return nil, err
	}
	fields := []contract.Field{}
	fields = append(fields, contract.Field{Name: "value", Value: v.Value})
	return contract.EncodeObject(fields)
}
func DecodeCheckedText(data []byte) (CheckedText, error) { return contract.Decode[CheckedText](data) }
func (v CheckedText) Validate() error                    { return contractValidateCheckedText(v, 0) }
func contractValidateCheckedText(v CheckedText, depth int) error {
	if depth > 1000 {
		return fmt.Errorf("validation nesting exceeds 1000")
	}
	if err := contract.Text(string(v), 1, -1, ""); err != nil {
		return contract.At("", err)
	}
	if err := validateText(v); err != nil {
		return err
	}
	return nil
}
func (v *CheckedText) UnmarshalJSON(data []byte) error {
	value, err := contract.Decode[string](data)
	if err != nil {
		return err
	}
	next := CheckedText(value)
	if err := next.Validate(); err != nil {
		return err
	}
	*v = next
	return nil
}
func (v CheckedText) MarshalJSON() ([]byte, error) {
	if err := v.Validate(); err != nil {
		return nil, err
	}
	return contract.EncodeJSON(string(v))
}
func CheckedTextJSONSchema() json.RawMessage {
	return json.RawMessage("{\"minLength\":1,\"title\":\"CheckedText\",\"type\":\"string\"}")
}
func DecodeEnvelope(data []byte) (Envelope, error) { return contract.Decode[Envelope](data) }
func (v Envelope) Validate() error                 { return contractValidateEnvelope(v, 0) }
func contractValidateEnvelope(v Envelope, depth int) error {
	if depth > 1000 {
		return fmt.Errorf("validation nesting exceeds 1000")
	}
	if err := contractValidateCheckedObject(v.CheckedObject, depth+1); err != nil {
		return contract.At("", err)
	}
	return nil
}
func (v *Envelope) UnmarshalJSON(data []byte) error {
	obj, err := contract.Decode[map[string]json.RawMessage](data)
	if err != nil {
		return err
	}
	var next Envelope
	for key := range obj {
		switch key {
		case "value":
		default:
			return contract.At(key, fmt.Errorf("unknown field"))
		}
	}
	{
		raw, ok := obj["value"]
		if !ok {
			return contract.At("value", fmt.Errorf("required field is absent"))
		}
		if ok {
			value, err := contract.Decode[string](raw)
			if err != nil {
				return contract.At("value", err)
			}
			next.CheckedObject.Value = value
		}
	}
	if err := next.Validate(); err != nil {
		return err
	}
	*v = next
	return nil
}
func (v Envelope) MarshalJSON() ([]byte, error) {
	if err := v.Validate(); err != nil {
		return nil, err
	}
	fields := []contract.Field{}
	fields = append(fields, contract.Field{Name: "value", Value: v.CheckedObject.Value})
	return contract.EncodeObject(fields)
}
func EnvelopeJSONSchema() json.RawMessage {
	return json.RawMessage("{\"additionalProperties\":false,\"properties\":{\"value\":{\"type\":\"string\"}},\"required\":[\"value\"],\"title\":\"Envelope\",\"type\":\"object\"}")
}
