// Code generated by contractgen; DO NOT EDIT.
package features

import (
	"encoding/json"
	"fmt"
	"github.com/wspl/demi/internal/contract"
	contracts "github.com/wspl/demi/tools/contractgen/testdata/blocks"
)

func DecodeCommon(data []byte) (Common, error) { return contract.Decode[Common](data) }
func (v Common) Validate() error               { return contractValidateCommon(v, 0) }
func contractValidateCommon(v Common, depth int) error {
	if depth > 1000 {
		return fmt.Errorf("validation nesting exceeds 1000")
	}
	if err := contractValidateIdentifier(v.ID, depth+1); err != nil {
		return contract.At("id", err)
	}
	if err := contract.Text(string(v.ID), 0, -1, ""); err != nil {
		return contract.At("id", err)
	}
	return nil
}
func (v *Common) UnmarshalJSON(data []byte) error {
	obj, err := contract.Decode[map[string]json.RawMessage](data)
	if err != nil {
		return err
	}
	var next Common
	for key := range obj {
		switch key {
		case "id":
		default:
			return contract.At(key, fmt.Errorf("unknown field"))
		}
	}
	{
		raw, ok := obj["id"]
		if !ok {
			return contract.At("id", fmt.Errorf("required field is absent"))
		}
		if ok {
			value, err := contract.Decode[Identifier](raw)
			if err != nil {
				return contract.At("id", err)
			}
			next.ID = value
		}
	}
	if err := next.Validate(); err != nil {
		return err
	}
	*v = next
	return nil
}
func (v Common) MarshalJSON() ([]byte, error) {
	if err := v.Validate(); err != nil {
		return nil, err
	}
	fields := []contract.Field{}
	fields = append(fields, contract.Field{Name: "id", Value: v.ID})
	return contract.EncodeObject(fields)
}
func DecodeEncoded(data []byte) (Encoded, error) { return contract.Decode[Encoded](data) }
func (v Encoded) Validate() error                { return contractValidateEncoded(v, 0) }
func contractValidateEncoded(v Encoded, depth int) error {
	if depth > 1000 {
		return fmt.Errorf("validation nesting exceeds 1000")
	}
	if err := contract.Base64(string(v)); err != nil {
		return contract.At("", err)
	}
	if err := contract.Text(string(v), 0, -1, ""); err != nil {
		return contract.At("", err)
	}
	return nil
}
func (v *Encoded) UnmarshalJSON(data []byte) error {
	value, err := contract.Decode[string](data)
	if err != nil {
		return err
	}
	next := Encoded(value)
	if err := next.Validate(); err != nil {
		return err
	}
	*v = next
	return nil
}
func (v Encoded) MarshalJSON() ([]byte, error) {
	if err := v.Validate(); err != nil {
		return nil, err
	}
	return contract.EncodeJSON(string(v))
}
func DecodeFlat(data []byte) (Flat, error) { return contract.Decode[Flat](data) }
func (v Flat) Validate() error             { return contractValidateFlat(v, 0) }
func contractValidateFlat(v Flat, depth int) error {
	if depth > 1000 {
		return fmt.Errorf("validation nesting exceeds 1000")
	}
	if err := contractValidateCommon(v.Common, depth+1); err != nil {
		return contract.At("", err)
	}
	if err := contract.Text(string(v.Text), 0, -1, ""); err != nil {
		return contract.At("text", err)
	}
	return nil
}
func (v *Flat) UnmarshalJSON(data []byte) error {
	obj, err := contract.Decode[map[string]json.RawMessage](data)
	if err != nil {
		return err
	}
	var next Flat
	for key := range obj {
		switch key {
		case "id", "text":
		default:
			return contract.At(key, fmt.Errorf("unknown field"))
		}
	}
	{
		raw, ok := obj["id"]
		if !ok {
			return contract.At("id", fmt.Errorf("required field is absent"))
		}
		if ok {
			value, err := contract.Decode[Identifier](raw)
			if err != nil {
				return contract.At("id", err)
			}
			next.Common.ID = value
		}
	}
	{
		raw, ok := obj["text"]
		if !ok {
			return contract.At("text", fmt.Errorf("required field is absent"))
		}
		if ok {
			value, err := contract.Decode[string](raw)
			if err != nil {
				return contract.At("text", err)
			}
			next.Text = value
		}
	}
	if err := next.Validate(); err != nil {
		return err
	}
	*v = next
	return nil
}
func (v Flat) MarshalJSON() ([]byte, error) {
	if err := v.Validate(); err != nil {
		return nil, err
	}
	fields := []contract.Field{}
	fields = append(fields, contract.Field{Name: "id", Value: v.Common.ID})
	fields = append(fields, contract.Field{Name: "text", Value: v.Text})
	return contract.EncodeObject(fields)
}
func ParseIdentifier(value string) (Identifier, error) {
	v := Identifier(value)
	if err := v.Validate(); err != nil {
		return "", err
	}
	return v, nil
}
func DecodeIdentifier(data []byte) (Identifier, error) { return contract.Decode[Identifier](data) }
func (v Identifier) Validate() error                   { return contractValidateIdentifier(v, 0) }
func contractValidateIdentifier(v Identifier, depth int) error {
	if depth > 1000 {
		return fmt.Errorf("validation nesting exceeds 1000")
	}
	if err := contract.Text(string(v), 0, -1, "^id_[a-z]+$"); err != nil {
		return contract.At("", err)
	}
	return nil
}
func (v *Identifier) UnmarshalJSON(data []byte) error {
	value, err := contract.Decode[string](data)
	if err != nil {
		return err
	}
	next := Identifier(value)
	if err := next.Validate(); err != nil {
		return err
	}
	*v = next
	return nil
}
func (v Identifier) MarshalJSON() ([]byte, error) {
	if err := v.Validate(); err != nil {
		return nil, err
	}
	return contract.EncodeJSON(string(v))
}
func DecodeNames(data []byte) (Names, error) { return contract.Decode[Names](data) }
func (v Names) Validate() error              { return contractValidateNames(v, 0) }
func contractValidateNames(v Names, depth int) error {
	if depth > 1000 {
		return fmt.Errorf("validation nesting exceeds 1000")
	}
	if v.Items == nil {
		return contract.At("items", fmt.Errorf("required array is nil"))
	}
	for i, item := range v.Items {
		_ = i
		_ = item
		if err := contractValidateIdentifier(item, depth+1); err != nil {
			return contract.At(fmt.Sprintf("%s[%d]", "items", i), err)
		}
		if err := contract.Text(string(item), 0, -1, ""); err != nil {
			return contract.At(fmt.Sprintf("%s[%d]", "items", i), err)
		}
	}
	if len(v.Items) < 1 {
		return contract.At("items", fmt.Errorf("too few items"))
	}
	return nil
}
func (v *Names) UnmarshalJSON(data []byte) error {
	obj, err := contract.Decode[map[string]json.RawMessage](data)
	if err != nil {
		return err
	}
	var next Names
	for key := range obj {
		switch key {
		case "items":
		default:
			return contract.At(key, fmt.Errorf("unknown field"))
		}
	}
	{
		raw, ok := obj["items"]
		if !ok {
			return contract.At("items", fmt.Errorf("required field is absent"))
		}
		if ok {
			value, err := func(b []byte) ([]Identifier, error) { return contract.List(b, contract.Decode[Identifier]) }(raw)
			if err != nil {
				return contract.At("items", err)
			}
			next.Items = value
		}
	}
	if err := next.Validate(); err != nil {
		return err
	}
	*v = next
	return nil
}
func (v Names) MarshalJSON() ([]byte, error) {
	if err := v.Validate(); err != nil {
		return nil, err
	}
	fields := []contract.Field{}
	fields = append(fields, contract.Field{Name: "items", Value: v.Items})
	return contract.EncodeObject(fields)
}
func DecodeRecords(data []byte) (Records, error) { return contract.Decode[Records](data) }
func (v Records) Validate() error                { return contractValidateRecords(v, 0) }
func contractValidateRecords(v Records, depth int) error {
	if depth > 1000 {
		return fmt.Errorf("validation nesting exceeds 1000")
	}
	if v.Values == nil {
		return contract.At("values", fmt.Errorf("required record is nil"))
	}
	for key, item := range v.Values {
		_ = item
		if err := contract.Text(key, 0, -1, ""); err != nil {
			return contract.At("values", err)
		}
		if item != nil {
			if err := contract.Text(string((*item)), 0, -1, ""); err != nil {
				return contract.At(fmt.Sprintf("%s[%q]", "values", key), err)
			}
		}
	}
	if err := contract.Timestamp(string(v.At)); err != nil {
		return contract.At("at", err)
	}
	if err := contract.Text(string(v.At), 0, -1, ""); err != nil {
		return contract.At("at", err)
	}
	return nil
}
func (v *Records) UnmarshalJSON(data []byte) error {
	obj, err := contract.Decode[map[string]json.RawMessage](data)
	if err != nil {
		return err
	}
	var next Records
	for key := range obj {
		switch key {
		case "values", "at":
		default:
			return contract.At(key, fmt.Errorf("unknown field"))
		}
	}
	{
		raw, ok := obj["values"]
		if !ok {
			return contract.At("values", fmt.Errorf("required field is absent"))
		}
		if ok {
			value, err := func(b []byte) (map[string]*string, error) {
				return contract.Record(b, func(b []byte) (*string, error) { return contract.Pointer(b, contract.Decode[string]) }, true)
			}(raw)
			if err != nil {
				return contract.At("values", err)
			}
			next.Values = value
		}
	}
	{
		raw, ok := obj["at"]
		if !ok {
			return contract.At("at", fmt.Errorf("required field is absent"))
		}
		if ok {
			value, err := contract.Decode[string](raw)
			if err != nil {
				return contract.At("at", err)
			}
			next.At = value
		}
	}
	if err := next.Validate(); err != nil {
		return err
	}
	*v = next
	return nil
}
func (v Records) MarshalJSON() ([]byte, error) {
	if err := v.Validate(); err != nil {
		return nil, err
	}
	fields := []contract.Field{}
	fields = append(fields, contract.Field{Name: "values", Value: v.Values})
	fields = append(fields, contract.Field{Name: "at", Value: v.At})
	return contract.EncodeObject(fields)
}
func DecodeRequest(data []byte) (Request, error) { return contract.Decode[Request](data) }
func (v Request) Validate() error                { return contractValidateRequest(v, 0) }
func contractValidateRequest(v Request, depth int) error {
	if depth > 1000 {
		return fmt.Errorf("validation nesting exceeds 1000")
	}
	if err := contractValidateIdentifier(v.ID, depth+1); err != nil {
		return contract.At("id", err)
	}
	if err := contract.Text(string(v.ID), 0, -1, ""); err != nil {
		return contract.At("id", err)
	}
	if err := contracts.ValidateUserContentBlock(v.Body); err != nil {
		return contract.At("body", err)
	}
	if err := contractValidateEncoded(v.Data, depth+1); err != nil {
		return contract.At("data", err)
	}
	if err := contract.Text(string(v.Data), 0, -1, ""); err != nil {
		return contract.At("data", err)
	}
	if v.Label != nil {
		if err := contract.Text(string((*v.Label)), 0, -1, ""); err != nil {
			return contract.At("label", err)
		}
	}
	if err := contract.CheckJSON(v.Extra); err != nil {
		return contract.At("extra", err)
	}
	return nil
}
func (v *Request) UnmarshalJSON(data []byte) error {
	obj, err := contract.Decode[map[string]json.RawMessage](data)
	if err != nil {
		return err
	}
	var next Request
	for key := range obj {
		switch key {
		case "id", "body", "data", "label", "extra":
		default:
			return contract.At(key, fmt.Errorf("unknown field"))
		}
	}
	{
		raw, ok := obj["id"]
		if !ok {
			return contract.At("id", fmt.Errorf("required field is absent"))
		}
		if ok {
			value, err := contract.Decode[Identifier](raw)
			if err != nil {
				return contract.At("id", err)
			}
			next.ID = value
		}
	}
	{
		raw, ok := obj["body"]
		if !ok {
			return contract.At("body", fmt.Errorf("required field is absent"))
		}
		if ok {
			value, err := contracts.DecodeUserContentBlock(raw)
			if err != nil {
				return contract.At("body", err)
			}
			next.Body = value
		}
	}
	{
		raw, ok := obj["data"]
		if !ok {
			return contract.At("data", fmt.Errorf("required field is absent"))
		}
		if ok {
			value, err := contract.Decode[Encoded](raw)
			if err != nil {
				return contract.At("data", err)
			}
			next.Data = value
		}
	}
	{
		raw, ok := obj["label"]
		if !ok {
			return contract.At("label", fmt.Errorf("required field is absent"))
		}
		if ok {
			if !contract.IsNull(raw) {
				value, err := func(b []byte) (*string, error) { return contract.Pointer(b, contract.Decode[string]) }(raw)
				if err != nil {
					return contract.At("label", err)
				}
				next.Label = value
			}
		}
	}
	{
		raw, ok := obj["extra"]
		if !ok {
			return contract.At("extra", fmt.Errorf("required field is absent"))
		}
		if ok {
			value, err := contract.JSON(raw)
			if err != nil {
				return contract.At("extra", err)
			}
			next.Extra = value
		}
	}
	if err := next.Validate(); err != nil {
		return err
	}
	*v = next
	return nil
}
func (v Request) MarshalJSON() ([]byte, error) {
	if err := v.Validate(); err != nil {
		return nil, err
	}
	fields := []contract.Field{}
	fields = append(fields, contract.Field{Name: "id", Value: v.ID})
	fields = append(fields, contract.Field{Name: "body", Value: v.Body})
	fields = append(fields, contract.Field{Name: "data", Value: v.Data})
	fields = append(fields, contract.Field{Name: "label", Value: v.Label})
	fields = append(fields, contract.Field{Name: "extra", Value: v.Extra})
	return contract.EncodeObject(fields)
}
func DecodeTree(data []byte) (Tree, error) { return contract.Decode[Tree](data) }
func (v Tree) Validate() error             { return contractValidateTree(v, 0) }
func contractValidateTree(v Tree, depth int) error {
	if depth > 1000 {
		return fmt.Errorf("validation nesting exceeds 1000")
	}
	if err := contractValidateIdentifier(v.Name, depth+1); err != nil {
		return contract.At("name", err)
	}
	if err := contract.Text(string(v.Name), 0, -1, ""); err != nil {
		return contract.At("name", err)
	}
	if v.Children == nil {
		return contract.At("children", fmt.Errorf("required array is nil"))
	}
	for i, item := range v.Children {
		_ = i
		_ = item
		if err := contractValidateTree(item, depth+1); err != nil {
			return contract.At(fmt.Sprintf("%s[%d]", "children", i), err)
		}
	}
	if v.Parent != nil {
		if err := contractValidateTree((*v.Parent), depth+1); err != nil {
			return contract.At("parent", err)
		}
	}
	return nil
}
func (v *Tree) UnmarshalJSON(data []byte) error {
	obj, err := contract.Decode[map[string]json.RawMessage](data)
	if err != nil {
		return err
	}
	var next Tree
	{
		raw, ok := obj["name"]
		if !ok {
			return contract.At("name", fmt.Errorf("required field is absent"))
		}
		if ok {
			value, err := contract.Decode[Identifier](raw)
			if err != nil {
				return contract.At("name", err)
			}
			next.Name = value
		}
	}
	{
		raw, ok := obj["children"]
		if !ok {
			return contract.At("children", fmt.Errorf("required field is absent"))
		}
		if ok {
			value, err := func(b []byte) ([]Tree, error) { return contract.List(b, contract.Decode[Tree]) }(raw)
			if err != nil {
				return contract.At("children", err)
			}
			next.Children = value
		}
	}
	{
		raw, ok := obj["parent"]
		if ok {
			value, err := func(b []byte) (*Tree, error) { return contract.Pointer(b, contract.Decode[Tree]) }(raw)
			if err != nil {
				return contract.At("parent", err)
			}
			next.Parent = value
		}
	}
	if err := next.Validate(); err != nil {
		return err
	}
	*v = next
	return nil
}
func (v Tree) MarshalJSON() ([]byte, error) {
	if err := v.Validate(); err != nil {
		return nil, err
	}
	fields := []contract.Field{}
	fields = append(fields, contract.Field{Name: "name", Value: v.Name})
	fields = append(fields, contract.Field{Name: "children", Value: v.Children})
	if v.Parent != nil {
		fields = append(fields, contract.Field{Name: "parent", Value: v.Parent})
	}
	return contract.EncodeObject(fields)
}
func DecodeRecordsMsgpack(data []byte) (Records, error) { return contract.DecodeMsgpack[Records](data) }
func (v *Records) UnmarshalMsgpack(data []byte) error {
	obj, err := contract.MsgpackObject(data)
	if err != nil {
		return err
	}
	var next Records
	{
		raw, present := obj["values"]
		delete(obj, "values")
		if !present {
			return contract.At("values", fmt.Errorf("required field is absent"))
		}
		if present {
			value, err := func(b []byte) (map[string]*string, error) {
				return contract.MsgpackRecord(b, func(b []byte) (*string, error) { return contract.Pointer(b, contract.DecodeMsgpack[string]) }, true)
			}(raw)
			if err != nil {
				return contract.At("values", err)
			}
			next.Values = value
		}
	}
	{
		raw, present := obj["at"]
		delete(obj, "at")
		if !present {
			return contract.At("at", fmt.Errorf("required field is absent"))
		}
		if present {
			value, err := func(b []byte) (string, error) { v, err := contract.MsgpackTimestamp(b); return string(v), err }(raw)
			if err != nil {
				return contract.At("at", err)
			}
			next.At = value
		}
	}
	for key := range obj {
		return contract.At(key, fmt.Errorf("unknown field"))
	}
	if err := next.Validate(); err != nil {
		return err
	}
	*v = next
	return nil
}
func (v Records) MarshalMsgpack() ([]byte, error) {
	if err := v.Validate(); err != nil {
		return nil, err
	}
	fields := []contract.Field{}
	fields = append(fields, contract.Field{Name: "values", Value: v.Values})
	fields = append(fields, contract.Field{Name: "at", Value: contract.MsgpackTimestampValue(v.At)})
	return contract.EncodeMsgpackObject(fields)
}
