//! `xtask contracts`: the TypeScript emitter (`contracts.md` § Generated
//! TypeScript). It asks schemars for the JSON Schema of every browser-facing
//! Rust type, in memory, and writes Zod v4 source with `z.infer` types into
//! `@demicodes/protocol` and `packages/web/src/api/generated`. A schema
//! outside the emitter's subset fails generation and names the type.

mod roots;
mod shape;
mod tables;
mod zod;

use std::collections::{BTreeMap, BTreeSet, HashSet};
use std::path::{Path, PathBuf};

use schemars::SchemaGenerator;
use serde_json::Value;

use self::roots::{Direction, Root};
use self::shape::{Shape, Unsupported};

/// The first line of every generated file.
const HEADER: &str = "// Generated by `bun run contracts` (`xtask contracts`) from the Rust contract types. Do not edit.\n";

/// Where `@demicodes/protocol`'s generated modules go, and the module the web
/// application imports them from.
const PROTOCOL_DIRECTORY: &str = "packages/protocol/src/generated";
const PROTOCOL_MODULE: &str = "@demicodes/protocol";
/// Where the web application's REST types go.
const WEB_DIRECTORY: &str = "packages/web/src/api/generated";

/// Why generation failed.
#[derive(Debug, thiserror::Error)]
pub enum Error {
    #[error("{0}")]
    Unsupported(#[from] Unsupported),
    /// The roots or the definitions they bring cannot become TypeScript.
    #[error("{0}")]
    Definitions(String),
    #[error("{path}: {source}")]
    Write { path: PathBuf, source: std::io::Error },
}

/// Generates every module and answers the files it wrote, relative to the
/// repository.
pub fn run() -> Result<Vec<PathBuf>, Error> {
    let repository = crate::repository();
    let generated = generate()?;
    let mut written = Vec::new();
    for (directory, files) in [
        (PROTOCOL_DIRECTORY, generated.protocol),
        (WEB_DIRECTORY, generated.web),
    ] {
        replace_directory(&repository.join(directory), &files)?;
        written.extend(files.iter().map(|(name, _)| Path::new(directory).join(name)));
    }
    Ok(written)
}

/// The generated files, by name, of each directory.
struct Generated {
    protocol: Vec<(&'static str, String)>,
    web: Vec<(&'static str, String)>,
}

fn generate() -> Result<Generated, Error> {
    let mut generator = SchemaGenerator::default();
    let protocol_roots = register(&mut generator, roots::protocol())?;
    let protocol_names: BTreeSet<String> = generator.definitions().keys().cloned().collect();
    let web_roots = register(&mut generator, roots::web())?;
    let definitions = read_definitions(generator.take_definitions(true))?;

    let received = received(
        &definitions,
        protocol_roots.iter().chain(&web_roots).filter(|(_, direction)| *direction == Direction::Receives),
    );
    let (protocol, protocol_imports) = module(&definitions, &received, &protocol_names)?;
    if let Some(name) = protocol_imports.iter().next() {
        return Err(Error::Definitions(format!("{name} is referred to by @demicodes/protocol but declared outside it")));
    }
    let web_names: BTreeSet<String> = definitions.keys().filter(|name| !protocol_names.contains(*name)).cloned().collect();
    let (web, web_imports) = module(&definitions, &received, &web_names)?;

    let mut web_source = String::from(HEADER);
    web_source.push_str("import { z } from \"zod\"\n");
    if !web_imports.is_empty() {
        let names: Vec<String> = web_imports.iter().map(|name| zod::schema_name(name)).collect();
        web_source.push_str(&format!("import {{ {} }} from \"{PROTOCOL_MODULE}\"\n", names.join(", ")));
    }
    web_source.push_str(&web);

    let mut contracts = String::from(HEADER);
    contracts.push_str("import { z } from \"zod\"\n");
    contracts.push_str(&protocol);
    Ok(Generated {
        protocol: vec![("contracts.ts", contracts), ("tables.ts", tables::module(HEADER))],
        web: vec![("web-api.ts", web_source)],
    })
}

/// Adds each root's schema to the generator and answers the definition each
/// root is, with its direction.
fn register(generator: &mut SchemaGenerator, roots: Vec<Root>) -> Result<Vec<(String, Direction)>, Error> {
    roots
        .into_iter()
        .map(|root| {
            let schema = (root.register)(generator);
            let name = schema
                .get("$ref")
                .and_then(Value::as_str)
                .and_then(|reference| reference.strip_prefix("#/$defs/"))
                .ok_or_else(|| Error::Definitions(format!("a root is not a named type: {}", schema.as_value())))?;
            Ok((name.to_owned(), root.direction))
        })
        .collect()
}

/// A definition read into the subset.
struct Definition {
    shape: Shape,
    description: Option<String>,
}

fn read_definitions(schemas: serde_json::Map<String, Value>) -> Result<BTreeMap<String, Definition>, Error> {
    let names: HashSet<&str> = schemas.keys().map(String::as_str).collect();
    for name in &names {
        check_name(name, &names)?;
    }
    schemas
        .iter()
        .map(|(name, schema)| {
            let definition = Definition {
                shape: shape::read(schema, name)?,
                description: shape::description(schema),
            };
            Ok((name.clone(), definition))
        })
        .collect()
}

/// A definition's name becomes a TypeScript name, so it must be an
/// identifier; and schemars numbers the second of two types with one name
/// (`Model2`), which would publish one of them under a name nobody chose.
fn check_name(name: &str, names: &HashSet<&str>) -> Result<(), Error> {
    let identifier = name.chars().next().is_some_and(|first| first.is_ascii_uppercase())
        && name.chars().all(|character| character.is_ascii_alphanumeric());
    if !identifier {
        return Err(Error::Definitions(format!("the type name {name:?} is not a TypeScript identifier")));
    }
    let stem = name.trim_end_matches(|character: char| character.is_ascii_digit());
    if stem.len() < name.len() && names.contains(stem) {
        return Err(Error::Definitions(format!("two types are named {stem}; schemars called the second {name}")));
    }
    Ok(())
}

/// The definitions the browser receives: every one a receiving root refers
/// to, directly or through others.
fn received<'a>(
    definitions: &BTreeMap<String, Definition>,
    roots: impl Iterator<Item = &'a (String, Direction)>,
) -> BTreeSet<String> {
    let mut received = BTreeSet::new();
    let mut pending: Vec<String> = roots.map(|(name, _)| name.clone()).collect();
    while let Some(name) = pending.pop() {
        if !received.insert(name.clone()) {
            continue;
        }
        if let Some(definition) = definitions.get(&name) {
            pending.extend(references(&definition.shape));
        }
    }
    received
}

/// The definitions a shape refers to, in the order it names them.
fn references(shape: &Shape) -> Vec<String> {
    let mut names = Vec::new();
    collect_references(shape, &mut names);
    names
}

fn collect_references(shape: &Shape, names: &mut Vec<String>) {
    match shape {
        Shape::Ref(name) => names.push(name.clone()),
        Shape::Array { items: inner, .. } | Shape::Record(inner) | Shape::Nullable(inner) => collect_references(inner, names),
        Shape::Object(object) => {
            for property in &object.properties {
                collect_references(&property.shape, names);
            }
        }
        Shape::Union { variants, .. } => {
            for variant in variants {
                names.extend(variant.extends.iter().cloned());
                for property in &variant.object.properties {
                    collect_references(&property.shape, names);
                }
            }
        }
        Shape::String(_) | Shape::Integer { .. } | Shape::Number { .. } | Shape::Boolean | Shape::Literal(_) | Shape::Enum(_) | Shape::Json => {}
    }
}

/// The declarations of the module that holds `names`, each after the
/// definitions it refers to, and the definitions it imports.
fn module(
    definitions: &BTreeMap<String, Definition>,
    received: &BTreeSet<String>,
    names: &BTreeSet<String>,
) -> Result<(String, BTreeSet<String>), Error> {
    let mut order = Vec::new();
    let mut visited = HashSet::new();
    for name in names {
        visit(name, definitions, names, &mut visited, &mut order);
    }
    let declared: Vec<zod::Definition<'_>> = order
        .iter()
        .map(|name| {
            let definition = &definitions[name];
            zod::Definition {
                name,
                shape: &definition.shape,
                description: definition.description.as_deref(),
                received: received.contains(name),
            }
        })
        .collect();
    Ok(zod::declarations(&declared)?)
}

/// Depth first, dependencies first; a definition already being visited is a
/// recursion, which the declarations reach through a getter.
fn visit(
    name: &str,
    definitions: &BTreeMap<String, Definition>,
    members: &BTreeSet<String>,
    visited: &mut HashSet<String>,
    order: &mut Vec<String>,
) {
    if !members.contains(name) || !visited.insert(name.to_owned()) {
        return;
    }
    for dependency in references(&definitions[name].shape) {
        visit(&dependency, definitions, members, visited, order);
    }
    order.push(name.to_owned());
}

/// Replaces `directory`, which holds only generated files, with `files`.
fn replace_directory(directory: &Path, files: &[(&str, String)]) -> Result<(), Error> {
    let fail = |path: &Path| {
        let path = path.to_owned();
        move |source| Error::Write { path, source }
    };
    if directory.exists() {
        std::fs::remove_dir_all(directory).map_err(fail(directory))?;
    }
    std::fs::create_dir_all(directory).map_err(fail(directory))?;
    for (name, source) in files {
        let path = directory.join(name);
        std::fs::write(&path, source).map_err(fail(&path))?;
    }
    Ok(())
}
