// Code generated by wiregen; DO NOT EDIT.

package builtinproto

import (
	"encoding/json/jsontext"

	"github.com/wspl/demi/go/internal/wire"
)

// UnmarshalJSONFrom decodes the JSON object of ErrorDetails: it ignores a member that
// the type does not have, and refuses a required member that is missing, a
// null, and a value of another JSON kind than the member's, naming the member.
func (v *ErrorDetails) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = ErrorDetails{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "action":
			if wire.IsNull(dec) {
				return wire.In("action", wire.Null())
			}
			var value ActionProgress
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("action", err)
			}
			value = ActionProgress(s)
			v.Action = &value
		case "tab":
			if wire.IsNull(dec) {
				return wire.In("tab", wire.Null())
			}
			var value string
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("tab", err)
			}
			value = s
			v.Tab = &value
		case "url":
			if wire.IsNull(dec) {
				return wire.In("url", wire.Null())
			}
			var value string
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("url", err)
			}
			value = s
			v.URL = &value
		case "condition":
			if wire.IsNull(dec) {
				return wire.In("condition", wire.Null())
			}
			var value string
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("condition", err)
			}
			value = s
			v.Condition = &value
		case "interceptor":
			if wire.IsNull(dec) {
				return wire.In("interceptor", wire.Null())
			}
			var value string
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("interceptor", err)
			}
			value = s
			v.Interceptor = &value
		case "count":
			if wire.IsNull(dec) {
				return wire.In("count", wire.Null())
			}
			var value uint
			n, err := wire.ReadUint(dec, wire.IntBits)
			if err != nil {
				return wire.In("count", err)
			}
			value = uint(n)
			v.Count = &value
		case "delivered":
			if wire.IsNull(dec) {
				return wire.In("delivered", wire.Null())
			}
			var value uint
			n, err := wire.ReadUint(dec, wire.IntBits)
			if err != nil {
				return wire.In("delivered", err)
			}
			value = uint(n)
			v.Delivered = &value
		case "debuggingCallers":
			if wire.IsNull(dec) {
				return wire.In("debuggingCallers", wire.Null())
			}
			var value []uint64
			if err := wire.BeginArray(dec); err != nil {
				return wire.In("debuggingCallers", err)
			}
			items0 := []uint64{}
			for {
				more, err := wire.NextElement(dec)
				if err != nil {
					return wire.In("debuggingCallers", err)
				}
				if !more {
					break
				}
				var element0 uint64
				{
					n, err := wire.ReadUint(dec, 64)
					if err != nil {
						return wire.In("debuggingCallers", wire.In(wire.Index(len(items0)), err))
					}
					element0 = n
				}
				items0 = append(items0, element0)
			}
			value = items0
			v.DebuggingCallers = &value
		case "directory":
			if wire.IsNull(dec) {
				return wire.In("directory", wire.Null())
			}
			var value string
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("directory", err)
			}
			value = s
			v.Directory = &value
		case "manifest":
			if wire.IsNull(dec) {
				return wire.In("manifest", wire.Null())
			}
			var value string
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("manifest", err)
			}
			value = s
			v.Manifest = &value
		case "files":
			if wire.IsNull(dec) {
				return wire.In("files", wire.Null())
			}
			var value []ExportedAsset
			if err := wire.BeginArray(dec); err != nil {
				return wire.In("files", err)
			}
			items0 := []ExportedAsset{}
			for {
				more, err := wire.NextElement(dec)
				if err != nil {
					return wire.In("files", err)
				}
				if !more {
					break
				}
				var element0 ExportedAsset
				{
					if err := element0.UnmarshalJSONFrom(dec); err != nil {
						return wire.In("files", wire.In(wire.Index(len(items0)), err))
					}
				}
				items0 = append(items0, element0)
			}
			value = items0
			v.Files = &value
		default:
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
	return nil
}

// validate checks the rules of the fields of ErrorDetails, and reports every one that
// is broken.
func (v ErrorDetails) validate() error {
	var r wire.Report
	if v.Action != nil {
		r.OneOf("action", string((*v.Action)), "not_started", "completed", "unknown")
	}
	if v.Files != nil {
		{
			var group0 wire.Report
			for i, e := range *v.Files {
				group0.Nest(wire.Index(i), e.validate())
			}
			r.Nest("files", group0.Err())
		}
	}
	r.Check("", v.check())
	return r.Err()
}

// UnmarshalJSONFrom decodes the JSON object of BrowserFailure: it refuses a member that
// the type does not have, a required member that is missing, a null, and a
// value of another JSON kind than the member's, naming the member.
func (v *BrowserFailure) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = BrowserFailure{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "code":
			seen |= 1 << 0
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("code", err)
			}
			v.Code = BrowserErrorCode(s)
		case "message":
			seen |= 1 << 1
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("message", err)
			}
			v.Message = s
		case "details":
			if wire.IsNull(dec) {
				return wire.In("details", wire.Null())
			}
			var value ErrorDetails
			if err := value.UnmarshalJSONFrom(dec); err != nil {
				return wire.In("details", err)
			}
			v.Details = &value
		default:
			return wire.Unknown(name)
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("code")
	}
	if seen&(1<<1) == 0 {
		return wire.Required("message")
	}
	return nil
}

// validate checks the rules of the fields of BrowserFailure, and reports every one that
// is broken.
func (v BrowserFailure) validate() error {
	var r wire.Report
	r.OneOf("code", string(v.Code), "invalid_input", "tab_not_found", "tab_busy", "stale_ref", "stale_cursor", "stale_inventory", "stale_tools", "target_not_found", "ambiguous_target", "not_actionable", "timeout", "dialog_blocked", "dialog_not_found", "invalid_dialog_action", "history_boundary", "navigation_failed", "protected_value", "side_effect_rejected", "unsupported_result", "unsupported_capability", "cdp_method_denied", "output_exists", "io_error", "result_too_large", "partial_failure", "driver_error", "browser_unavailable", "browser_lost", "cancelled", "outcome_unknown")
	if v.Details != nil {
		r.Nest("details", (*v.Details).validate())
	}
	return r.Err()
}

// UnmarshalJSONFrom decodes the JSON object of FailureDocument: it refuses a member that
// the type does not have, a required member that is missing, a null, and a
// value of another JSON kind than the member's, naming the member.
func (v *FailureDocument) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = FailureDocument{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "error":
			seen |= 1 << 0
			if err := v.Error.UnmarshalJSONFrom(dec); err != nil {
				return wire.In("error", err)
			}
		default:
			return wire.Unknown(name)
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("error")
	}
	return nil
}

// validate checks the rules of the fields of FailureDocument, and reports every one that
// is broken.
func (v FailureDocument) validate() error {
	var r wire.Report
	r.Nest("error", v.Error.validate())
	return r.Err()
}
