package builtinproto

// operationOrder is every operation the package serves, in the order its
// descriptor lists them: the file operations, the browser operations, and the
// live view.
var operationOrder = []string{
	"file.read",
	"file.create",
	"file.edit",
	"file.patch",
	"browser.open",
	"browser.tabs",
	"browser.info",
	"browser.goto",
	"browser.back",
	"browser.forward",
	"browser.reload",
	"browser.history",
	"browser.close",
	"browser.inspect",
	"browser.find",
	"browser.read",
	"browser.screenshot",
	"browser.probe",
	"browser.click",
	"browser.move",
	"browser.drag",
	"browser.scroll",
	"browser.fill",
	"browser.type",
	"browser.key",
	"browser.check",
	"browser.select",
	"browser.select-text",
	"browser.wait",
	"browser.upload",
	"browser.download",
	"browser.clipboard.write",
	"browser.clipboard.read",
	"browser.eval",
	"browser.logs",
	"browser.viewport.set",
	"browser.viewport.reset",
	"browser.dialog.inspect",
	"browser.dialog.accept",
	"browser.dialog.dismiss",
	"browser.cdp.targets",
	"browser.cdp.detach",
	"browser.cdp.send",
	"browser.cdp.events",
	"browser.content.read",
	"browser.content.fetch",
	"browser.assets.list",
	"browser.assets.export",
	"browser.capabilities",
	"browser.webmcp.list",
	"browser.webmcp.call",
	LiveOperation,
}

// decoders decode the arguments of each operation into its input type.
var decoders = map[string]func([]byte) (any, error){
	"file.read":               decoder[ReadArgs],
	"file.create":             decoder[CreateArgs],
	"file.edit":               decoder[EditArgs],
	"file.patch":              decoder[PatchArgs],
	"browser.open":            decoder[OpenInput],
	"browser.tabs":            decoder[TabsInput],
	"browser.info":            decoder[InfoInput],
	"browser.goto":            decoder[GotoInput],
	"browser.back":            decoder[BackInput],
	"browser.forward":         decoder[ForwardInput],
	"browser.reload":          decoder[ReloadInput],
	"browser.history":         decoder[HistoryInput],
	"browser.close":           decoder[CloseInput],
	"browser.inspect":         decoder[InspectInput],
	"browser.find":            decoder[FindInput],
	"browser.read":            decoder[ReadInput],
	"browser.screenshot":      decoder[ScreenshotInput],
	"browser.probe":           decoder[ProbeInput],
	"browser.click":           decoder[ClickInput],
	"browser.move":            decoder[MoveInput],
	"browser.drag":            decoder[DragInput],
	"browser.scroll":          decoder[ScrollInput],
	"browser.fill":            decoder[FillInput],
	"browser.type":            decoder[TypeInput],
	"browser.key":             decoder[KeyInput],
	"browser.check":           decoder[CheckInput],
	"browser.select":          decoder[SelectInput],
	"browser.select-text":     decoder[SelectTextInput],
	"browser.wait":            decoder[WaitInput],
	"browser.upload":          decoder[UploadInput],
	"browser.download":        decoder[DownloadInput],
	"browser.clipboard.write": decoder[ClipboardWriteInput],
	"browser.clipboard.read":  decoder[ClipboardReadInput],
	"browser.eval":            decoder[EvalInput],
	"browser.logs":            decoder[LogsInput],
	"browser.viewport.set":    decoder[ViewportSetInput],
	"browser.viewport.reset":  decoder[ViewportResetInput],
	"browser.dialog.inspect":  decoder[DialogInspectInput],
	"browser.dialog.accept":   decoder[DialogAcceptInput],
	"browser.dialog.dismiss":  decoder[DialogDismissInput],
	"browser.cdp.targets":     decoder[CDPTargetsInput],
	"browser.cdp.detach":      decoder[CDPDetachInput],
	"browser.cdp.send":        decoder[CDPSendInput],
	"browser.cdp.events":      decoder[CDPEventsInput],
	"browser.content.read":    decoder[ContentReadInput],
	"browser.content.fetch":   decoder[ContentFetchInput],
	"browser.assets.list":     decoder[AssetsListInput],
	"browser.assets.export":   decoder[AssetsExportInput],
	"browser.capabilities":    decoder[CapabilitiesInput],
	"browser.webmcp.list":     decoder[WebmcpListInput],
	"browser.webmcp.call":     decoder[WebmcpCallInput],
	LiveOperation:             decoder[LiveInput],
}

// decoder returns the decoder of the arguments of an operation whose input is a
// T.
func decoder[T any](args []byte) (any, error) {
	return decode[T](args)
}
