// Code generated by contractgen; DO NOT EDIT.

package kept

import (
	"encoding/json"
	"fmt"
	"github.com/wspl/demi/internal/contract"
)

func (*LeftOut) record()                         {}
func DecodeLeftOut(data []byte) (LeftOut, error) { return contract.Decode[LeftOut](data) }
func (v LeftOut) Validate() error                { return contractValidateLeftOut(v, 0) }
func contractValidateLeftOut(v LeftOut, depth int) error {
	if depth > 1000 {
		return fmt.Errorf("validation nesting exceeds 1000")
	}
	return nil
}
func (v *LeftOut) UnmarshalJSON(data []byte) error {
	obj, err := contract.Decode[map[string]json.RawMessage](data)
	if err != nil {
		return err
	}
	var next LeftOut
	for key := range obj {
		switch key {
		case "bytes", "type":
		default:
			return contract.At(key, fmt.Errorf("unknown field"))
		}
	}
	if raw, ok := obj["type"]; !ok {
		return fmt.Errorf("missing union tag")
	} else {
		value, err := contract.Decode[string](raw)
		if err != nil || value != "left_out" {
			return fmt.Errorf("invalid union tag")
		}
	}
	{
		raw, ok := obj["bytes"]
		if !ok {
			return contract.At("bytes", fmt.Errorf("required field is absent"))
		}
		if ok {
			value, err := contract.Decode[uint64](raw)
			if err != nil {
				return contract.At("bytes", err)
			}
			next.Bytes = value
		}
	}
	if err := next.Validate(); err != nil {
		return err
	}
	*v = next
	return nil
}
func (v LeftOut) MarshalJSON() ([]byte, error) {
	if err := v.Validate(); err != nil {
		return nil, err
	}
	fields := []contract.Field{}
	fields = append(fields, contract.Field{Name: "type", Value: "left_out"})
	fields = append(fields, contract.Field{Name: "bytes", Value: v.Bytes})
	return contract.EncodeObject(fields)
}
func (*Output) record()                        {}
func DecodeOutput(data []byte) (Output, error) { return contract.Decode[Output](data) }
func (v Output) Validate() error               { return contractValidateOutput(v, 0) }
func contractValidateOutput(v Output, depth int) error {
	if depth > 1000 {
		return fmt.Errorf("validation nesting exceeds 1000")
	}
	if err := contractValidateStream(v.Stream, depth+1); err != nil {
		return contract.At("stream", err)
	}
	if err := contract.Text(string(v.Stream), 0, -1, ""); err != nil {
		return contract.At("stream", err)
	}
	if v.Data == nil {
		return contract.At("data", fmt.Errorf("required array is nil"))
	}
	for i, item := range v.Data {
		_ = i
		_ = item
	}
	return nil
}
func (v *Output) UnmarshalJSON(data []byte) error {
	obj, err := contract.Decode[map[string]json.RawMessage](data)
	if err != nil {
		return err
	}
	var next Output
	for key := range obj {
		switch key {
		case "stream", "data", "type":
		default:
			return contract.At(key, fmt.Errorf("unknown field"))
		}
	}
	if raw, ok := obj["type"]; !ok {
		return fmt.Errorf("missing union tag")
	} else {
		value, err := contract.Decode[string](raw)
		if err != nil || value != "output" {
			return fmt.Errorf("invalid union tag")
		}
	}
	{
		raw, ok := obj["stream"]
		if !ok {
			return contract.At("stream", fmt.Errorf("required field is absent"))
		}
		if ok {
			value, err := contract.Decode[Stream](raw)
			if err != nil {
				return contract.At("stream", err)
			}
			next.Stream = value
		}
	}
	{
		raw, ok := obj["data"]
		if !ok {
			return contract.At("data", fmt.Errorf("required field is absent"))
		}
		if ok {
			value, err := contract.Bytes(raw)
			if err != nil {
				return contract.At("data", err)
			}
			next.Data = value
		}
	}
	if err := next.Validate(); err != nil {
		return err
	}
	*v = next
	return nil
}
func (v Output) MarshalJSON() ([]byte, error) {
	if err := v.Validate(); err != nil {
		return nil, err
	}
	fields := []contract.Field{}
	fields = append(fields, contract.Field{Name: "type", Value: "output"})
	fields = append(fields, contract.Field{Name: "stream", Value: v.Stream})
	fields = append(fields, contract.Field{Name: "data", Value: v.Data})
	return contract.EncodeObject(fields)
}
func DecodeRecord(data []byte) (Record, error) {
	obj, err := contract.Decode[map[string]json.RawMessage](data)
	if err != nil {
		return nil, err
	}
	tag, err := contract.Decode[string](obj["type"])
	if err != nil {
		return nil, fmt.Errorf("type: %w", err)
	}
	switch tag {
	case "left_out":
		value, err := contract.Decode[LeftOut](data)
		if err != nil {
			return nil, err
		}
		return &value, nil
	case "output":
		value, err := contract.Decode[Output](data)
		if err != nil {
			return nil, err
		}
		return &value, nil
	}
	return nil, fmt.Errorf("unknown Record tag %q", tag)
}

type RecordJSON struct{ Value Record }

func (v *RecordJSON) UnmarshalJSON(data []byte) error {
	value, err := DecodeRecord(data)
	if err == nil {
		v.Value = value
	}
	return err
}
func (v RecordJSON) MarshalJSON() ([]byte, error) {
	if err := ValidateRecord(v.Value); err != nil {
		return nil, err
	}
	return contract.EncodeJSON(v.Value)
}
func ValidateRecord(value Record) error { return contractValidateRecord(value, 0) }
func contractValidateRecord(value Record, depth int) error {
	if depth > 1000 {
		return fmt.Errorf("validation nesting exceeds 1000")
	}
	switch v := value.(type) {
	case *LeftOut:
		if v == nil {
			return fmt.Errorf("nil variant")
		}
		return contractValidateLeftOut(*v, depth+1)
	case *Output:
		if v == nil {
			return fmt.Errorf("nil variant")
		}
		return contractValidateOutput(*v, depth+1)
	default:
		return fmt.Errorf("nil or unsupported Record")
	}
}
func DecodeStream(data []byte) (Stream, error) { return contract.Decode[Stream](data) }
func (v Stream) Validate() error               { return contractValidateStream(v, 0) }
func contractValidateStream(v Stream, depth int) error {
	if depth > 1000 {
		return fmt.Errorf("validation nesting exceeds 1000")
	}
	switch string(v) {
	case "stdout", "stderr":
	default:
		return contract.At("", fmt.Errorf("unknown value"))
	}
	if err := contract.Text(string(v), 0, -1, ""); err != nil {
		return contract.At("", err)
	}
	return nil
}
func (v *Stream) UnmarshalJSON(data []byte) error {
	value, err := contract.Decode[string](data)
	if err != nil {
		return err
	}
	next := Stream(value)
	if err := next.Validate(); err != nil {
		return err
	}
	*v = next
	return nil
}
func (v Stream) MarshalJSON() ([]byte, error) {
	if err := v.Validate(); err != nil {
		return nil, err
	}
	return contract.EncodeJSON(string(v))
}
func DecodeLeftOutMsgpack(data []byte) (LeftOut, error) { return contract.DecodeMsgpack[LeftOut](data) }
func (v *LeftOut) UnmarshalMsgpack(data []byte) error {
	fields, err := contract.MsgpackTuple(data, "left_out", 1)
	if err != nil {
		return err
	}
	var next LeftOut
	{
		raw := fields[0]
		value, err := contract.DecodeMsgpack[uint64](raw)
		if err != nil {
			return contract.At("bytes", err)
		}
		next.Bytes = value
	}
	if err := next.Validate(); err != nil {
		return err
	}
	*v = next
	return nil
}
func (v LeftOut) MarshalMsgpack() ([]byte, error) {
	if err := v.Validate(); err != nil {
		return nil, err
	}
	fields := []any{}
	fields = append(fields, v.Bytes)
	return contract.EncodeMsgpackTuple("left_out", fields)
}
func DecodeOutputMsgpack(data []byte) (Output, error) { return contract.DecodeMsgpack[Output](data) }
func (v *Output) UnmarshalMsgpack(data []byte) error {
	fields, err := contract.MsgpackTuple(data, "output", 2)
	if err != nil {
		return err
	}
	var next Output
	{
		raw := fields[0]
		value, err := contract.DecodeMsgpack[Stream](raw)
		if err != nil {
			return contract.At("stream", err)
		}
		next.Stream = value
	}
	{
		raw := fields[1]
		value, err := contract.DecodeMsgpack[[]byte](raw)
		if err != nil {
			return contract.At("data", err)
		}
		next.Data = value
	}
	if err := next.Validate(); err != nil {
		return err
	}
	*v = next
	return nil
}
func (v Output) MarshalMsgpack() ([]byte, error) {
	if err := v.Validate(); err != nil {
		return nil, err
	}
	fields := []any{}
	fields = append(fields, v.Stream)
	fields = append(fields, v.Data)
	return contract.EncodeMsgpackTuple("output", fields)
}
func DecodeRecordMsgpack(data []byte) (Record, error) {
	obj, err := contract.MsgpackObject(data)
	if err != nil {
		return nil, err
	}
	if len(obj) != 1 {
		return nil, fmt.Errorf("expected one external union tag")
	}
	var tag string
	for key := range obj {
		tag = key
	}
	switch tag {
	case "left_out":
		value, err := contract.DecodeMsgpack[LeftOut](data)
		return &value, err
	case "output":
		value, err := contract.DecodeMsgpack[Output](data)
		return &value, err
	}
	return nil, fmt.Errorf("unknown union tag")
}
func EncodeRecordMsgpack(v Record) ([]byte, error) {
	if err := ValidateRecord(v); err != nil {
		return nil, err
	}
	return contract.EncodeMsgpack(v)
}
func DecodeStreamMsgpack(data []byte) (Stream, error) { return contract.DecodeMsgpack[Stream](data) }
func (v *Stream) UnmarshalMsgpack(data []byte) error {
	value, err := contract.DecodeMsgpack[string](data)
	if err != nil {
		return err
	}
	next := Stream(value)
	if err := next.Validate(); err != nil {
		return err
	}
	*v = next
	return nil
}
func (v Stream) MarshalMsgpack() ([]byte, error) {
	if err := v.Validate(); err != nil {
		return nil, err
	}
	return contract.EncodeMsgpack(string(v))
}
