// Code generated by wiregen; DO NOT EDIT.

package sandbox

import (
	"encoding/json/jsontext"

	"github.com/wspl/demi/go/internal/wire"
)

// UnmarshalJSONFrom decodes the JSON object of Record: it refuses a member that
// the type does not have, a required member that is missing, a null, and a
// value of another JSON kind than the member's, naming the member.
func (v *Record) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = Record{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "id":
			seen |= 1 << 0
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("id", err)
			}
			v.ID = SandboxID(s)
		case "slot":
			seen |= 1 << 1
			n, err := wire.ReadUint(dec, 16)
			if err != nil {
				return wire.In("slot", err)
			}
			v.Slot = uint16(n)
		default:
			return wire.Unknown(name)
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("id")
	}
	if seen&(1<<1) == 0 {
		return wire.Required("slot")
	}
	return nil
}

// validate checks the rules of the fields of Record, and reports every one that
// is broken.
func (v Record) validate() error {
	var r wire.Report
	r.Check("id", sandboxID(v.ID))
	return r.Err()
}
