// Code generated by contractgen; DO NOT EDIT.
package text

import (
	"encoding/json"
	"fmt"
	"github.com/wspl/demi/internal/contract"
)

func ParseEmail(value string) (Email, error) {
	{
		normalized, err := contract.Email(value)
		if err != nil {
			return "", err
		}
		value = normalized
	}
	v := Email(value)
	if err := v.Validate(); err != nil {
		return "", err
	}
	return v, nil
}
func DecodeEmail(data []byte) (Email, error) { return contract.Decode[Email](data) }
func (v Email) Validate() error              { return contractValidateEmail(v, 0) }
func contractValidateEmail(v Email, depth int) error {
	if depth > 1000 {
		return fmt.Errorf("validation nesting exceeds 1000")
	}
	if value, err := contract.Email(string(v)); err != nil {
		return contract.At("", err)
	} else if value != string(v) {
		return contract.At("", fmt.Errorf("text is not canonical"))
	}
	if err := contract.Text(string(v), 0, -1, ""); err != nil {
		return contract.At("", err)
	}
	return nil
}
func (v *Email) UnmarshalJSON(data []byte) error {
	value, err := contract.Decode[string](data)
	if err != nil {
		return err
	}
	{
		normalized, err := contract.Email(value)
		if err != nil {
			return err
		}
		value = normalized
	}
	next := Email(value)
	if err := next.Validate(); err != nil {
		return err
	}
	*v = next
	return nil
}
func (v Email) MarshalJSON() ([]byte, error) {
	if err := v.Validate(); err != nil {
		return nil, err
	}
	return json.Marshal(string(v))
}
func DecodeName(data []byte) (Name, error) { return contract.Decode[Name](data) }
func (v Name) Validate() error             { return contractValidateName(v, 0) }
func contractValidateName(v Name, depth int) error {
	if depth > 1000 {
		return fmt.Errorf("validation nesting exceeds 1000")
	}
	if contract.Trim(string(v)) != string(v) {
		return contract.At("", fmt.Errorf("text is not trimmed"))
	}
	if err := contract.Text(string(v), 1, 8, ""); err != nil {
		return contract.At("", err)
	}
	return nil
}
func (v *Name) UnmarshalJSON(data []byte) error {
	value, err := contract.Decode[string](data)
	if err != nil {
		return err
	}
	value = contract.Trim(value)
	next := Name(value)
	if err := next.Validate(); err != nil {
		return err
	}
	*v = next
	return nil
}
func (v Name) MarshalJSON() ([]byte, error) {
	if err := v.Validate(); err != nil {
		return nil, err
	}
	return json.Marshal(string(v))
}
func DecodeReceived(data []byte) (Received, error) { return contract.Decode[Received](data) }
func (v Received) Validate() error                 { return contractValidateReceived(v, 0) }
func contractValidateReceived(v Received, depth int) error {
	if depth > 1000 {
		return fmt.Errorf("validation nesting exceeds 1000")
	}
	if err := contractValidateEmail(v.Email, depth+1); err != nil {
		return contract.At("email", err)
	}
	if err := contract.Text(string(v.Email), 0, -1, ""); err != nil {
		return contract.At("email", err)
	}
	return nil
}
func (v *Received) UnmarshalJSON(data []byte) error {
	obj, err := contract.Decode[map[string]json.RawMessage](data)
	if err != nil {
		return err
	}
	var next Received
	for key := range obj {
		switch key {
		case "email":
		default:
			return contract.At(key, fmt.Errorf("unknown field"))
		}
	}
	{
		raw, ok := obj["email"]
		if !ok {
			return contract.At("email", fmt.Errorf("required field is absent"))
		}
		if ok {
			value, err := contract.Decode[Email](raw)
			if err != nil {
				return contract.At("email", err)
			}
			next.Email = value
		}
	}
	if err := next.Validate(); err != nil {
		return err
	}
	*v = next
	return nil
}
func (v Received) MarshalJSON() ([]byte, error) {
	if err := v.Validate(); err != nil {
		return nil, err
	}
	fields := []contract.Field{}
	fields = append(fields, contract.Field{Name: "email", Value: v.Email})
	return contract.EncodeObject(fields)
}
func DecodeReceivedEmail(data []byte) (ReceivedEmail, error) {
	return contract.Decode[ReceivedEmail](data)
}
func (v ReceivedEmail) Validate() error { return contractValidateReceivedEmail(v, 0) }
func contractValidateReceivedEmail(v ReceivedEmail, depth int) error {
	if depth > 1000 {
		return fmt.Errorf("validation nesting exceeds 1000")
	}
	if value, err := contract.Email(string(v)); err != nil {
		return contract.At("", err)
	} else if value != string(v) {
		return contract.At("", fmt.Errorf("text is not canonical"))
	}
	if err := contract.Text(string(v), 0, -1, ""); err != nil {
		return contract.At("", err)
	}
	return nil
}
func (v *ReceivedEmail) UnmarshalJSON(data []byte) error {
	value, err := contract.Decode[string](data)
	if err != nil {
		return err
	}
	{
		normalized, err := contract.Email(value)
		if err != nil {
			return err
		}
		value = normalized
	}
	next := ReceivedEmail(value)
	if err := next.Validate(); err != nil {
		return err
	}
	*v = next
	return nil
}
func (v ReceivedEmail) MarshalJSON() ([]byte, error) {
	if err := v.Validate(); err != nil {
		return nil, err
	}
	return json.Marshal(string(v))
}
func DecodeEmailMsgpack(data []byte) (Email, error) { return contract.DecodeMsgpack[Email](data) }
func (v *Email) UnmarshalMsgpack(data []byte) error {
	value, err := contract.DecodeMsgpack[string](data)
	if err != nil {
		return err
	}
	{
		normalized, err := contract.Email(value)
		if err != nil {
			return err
		}
		value = normalized
	}
	next := Email(value)
	if err := next.Validate(); err != nil {
		return err
	}
	*v = next
	return nil
}
func (v Email) MarshalMsgpack() ([]byte, error) {
	if err := v.Validate(); err != nil {
		return nil, err
	}
	return contract.EncodeMsgpack(string(v))
}
func DecodeNameMsgpack(data []byte) (Name, error) { return contract.DecodeMsgpack[Name](data) }
func (v *Name) UnmarshalMsgpack(data []byte) error {
	value, err := contract.DecodeMsgpack[string](data)
	if err != nil {
		return err
	}
	value = contract.Trim(value)
	next := Name(value)
	if err := next.Validate(); err != nil {
		return err
	}
	*v = next
	return nil
}
func (v Name) MarshalMsgpack() ([]byte, error) {
	if err := v.Validate(); err != nil {
		return nil, err
	}
	return contract.EncodeMsgpack(string(v))
}
