// Code generated by wiregen; DO NOT EDIT.

package commandtree

import (
	"encoding/json/jsontext"
	"fmt"

	"github.com/wspl/demi/go/internal/wire"
)

// decodeNode decodes the JSON object of a Node, whichever variant it is.
func decodeNode(dec *jsontext.Decoder) (Node, error) {
	raw, err := wire.ReadObject(dec)
	if err != nil {
		return nil, err
	}
	var found Node
	matches := 0
	{
		var v Group
		if v.UnmarshalJSONFrom(wire.NewDecoder(raw)) == nil {
			found = v
			matches++
		}
	}
	{
		var v Leaf
		if v.UnmarshalJSONFrom(wire.NewDecoder(raw)) == nil {
			found = v
			matches++
		}
	}
	switch matches {
	case 1:
		return found, nil
	case 0:
		return nil, wire.NoVariant("Group", "Leaf")
	}
	return nil, wire.SeveralVariants("Group", "Leaf")
}

// validateNode checks the rules of the variant that v is.
func validateNode(v Node) error {
	switch v := v.(type) {
	case nil:
		return wire.Required("")
	case Group:
		return v.validate()
	case *Group:
		if v == nil {
			return fmt.Errorf("a nil %T is not a variant of Node", v)
		}
		return v.validate()
	case Leaf:
		return v.validate()
	case *Leaf:
		if v == nil {
			return fmt.Errorf("a nil %T is not a variant of Node", v)
		}
		return v.validate()
	}
	return fmt.Errorf("%T is not a variant of Node", v)
}

// UnmarshalJSONFrom decodes the JSON object of Group: it refuses a member that
// the type does not have, a required member that is missing, a null, and a
// value of another JSON kind than the member's, naming the member.
func (v *Group) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = Group{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "name":
			seen |= 1 << 0
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("name", err)
			}
			v.Name = s
		case "summary":
			seen |= 1 << 1
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("summary", err)
			}
			v.Summary = s
		case "subcommands":
			seen |= 1 << 2
			if err := wire.BeginArray(dec); err != nil {
				return wire.In("subcommands", err)
			}
			items0 := []Node{}
			for {
				more, err := wire.NextElement(dec)
				if err != nil {
					return wire.In("subcommands", err)
				}
				if !more {
					break
				}
				var element0 Node
				{
					u, err := decodeNode(dec)
					if err != nil {
						return wire.In("subcommands", wire.In(wire.Index(len(items0)), err))
					}
					element0 = u
				}
				items0 = append(items0, element0)
			}
			v.Subcommands = items0
		default:
			return wire.Unknown(name)
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("name")
	}
	if seen&(1<<1) == 0 {
		return wire.Required("summary")
	}
	if seen&(1<<2) == 0 {
		return wire.Required("subcommands")
	}
	return nil
}

// validate checks the rules of the fields of Group, and reports every one that
// is broken.
func (v Group) validate() error {
	var r wire.Report
	{
		var group0 wire.Report
		for i, e := range v.Subcommands {
			group0.Nest(wire.Index(i), validateNode(e))
		}
		r.Nest("subcommands", group0.Err())
	}
	return r.Err()
}

// UnmarshalJSONFrom decodes the JSON object of Leaf: it refuses a member that
// the type does not have, a required member that is missing, a null, and a
// value of another JSON kind than the member's, naming the member.
func (v *Leaf) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = Leaf{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "name":
			seen |= 1 << 0
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("name", err)
			}
			v.Name = s
		case "summary":
			seen |= 1 << 1
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("summary", err)
			}
			v.Summary = s
		case "successOutput":
			if wire.IsNull(dec) {
				return wire.In("successOutput", wire.Null())
			}
			var value string
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("successOutput", err)
			}
			value = s
			v.SuccessOutput = &value
		case "failureOutput":
			if wire.IsNull(dec) {
				return wire.In("failureOutput", wire.Null())
			}
			var value string
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("failureOutput", err)
			}
			value = s
			v.FailureOutput = &value
		case "runningHint":
			if wire.IsNull(dec) {
				return wire.In("runningHint", wire.Null())
			}
			var value string
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("runningHint", err)
			}
			value = s
			v.RunningHint = &value
		case "input":
			if wire.IsNull(dec) {
				return wire.In("input", wire.Null())
			}
			var value Schema
			if err := value.UnmarshalJSONFrom(dec); err != nil {
				return wire.In("input", err)
			}
			v.Input = &value
		case "positionals":
			if wire.IsNull(dec) {
				return wire.In("positionals", wire.Null())
			}
			var value []string
			if err := wire.BeginArray(dec); err != nil {
				return wire.In("positionals", err)
			}
			items0 := []string{}
			for {
				more, err := wire.NextElement(dec)
				if err != nil {
					return wire.In("positionals", err)
				}
				if !more {
					break
				}
				var element0 string
				{
					s, err := wire.ReadString(dec)
					if err != nil {
						return wire.In("positionals", wire.In(wire.Index(len(items0)), err))
					}
					element0 = s
				}
				items0 = append(items0, element0)
			}
			value = items0
			v.Positionals = &value
		case "stdinField":
			if wire.IsNull(dec) {
				return wire.In("stdinField", wire.Null())
			}
			var value string
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("stdinField", err)
			}
			value = s
			v.StdinField = &value
		case "restField":
			if wire.IsNull(dec) {
				return wire.In("restField", wire.Null())
			}
			var value string
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("restField", err)
			}
			value = s
			v.RestField = &value
		case "output":
			if wire.IsNull(dec) {
				return wire.In("output", wire.Null())
			}
			var value LeafOutput
			if err := value.UnmarshalJSONFrom(dec); err != nil {
				return wire.In("output", err)
			}
			v.Output = &value
		case "kind":
			seen |= 1 << 10
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("kind", err)
			}
			v.Kind = LeafKind(s)
		case "binding":
			if wire.IsNull(dec) {
				return wire.In("binding", wire.Null())
			}
			var value Binding
			if err := value.UnmarshalJSONFrom(dec); err != nil {
				return wire.In("binding", err)
			}
			v.Binding = &value
		default:
			return wire.Unknown(name)
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("name")
	}
	if seen&(1<<1) == 0 {
		return wire.Required("summary")
	}
	if seen&(1<<10) == 0 {
		return wire.Required("kind")
	}
	return nil
}

// validate checks the rules of the fields of Leaf, and reports every one that
// is broken.
func (v Leaf) validate() error {
	var r wire.Report
	if v.Output != nil {
		r.Nest("output", (*v.Output).validate())
	}
	r.OneOf("kind", string(v.Kind), "rpc", "native")
	if v.Binding != nil {
		r.Nest("binding", (*v.Binding).validate())
	}
	r.Check("", v.check())
	return r.Err()
}

// UnmarshalJSONFrom decodes the JSON object of LeafOutput: it refuses a member that
// the type does not have, a required member that is missing, a null, and a
// value of another JSON kind than the member's, naming the member.
func (v *LeafOutput) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = LeafOutput{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "json":
			if wire.IsNull(dec) {
				return wire.In("json", wire.Null())
			}
			var value Schema
			if err := value.UnmarshalJSONFrom(dec); err != nil {
				return wire.In("json", err)
			}
			v.JSON = &value
		default:
			return wire.Unknown(name)
		}
	}
	return nil
}

// validate checks the rules of the fields of LeafOutput, and reports every one that
// is broken.
func (LeafOutput) validate() error {
	return nil
}

// UnmarshalJSONFrom decodes the JSON object of NativeOperation: it refuses a member that
// the type does not have, a required member that is missing, a null, and a
// value of another JSON kind than the member's, naming the member.
func (v *NativeOperation) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = NativeOperation{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "package":
			seen |= 1 << 0
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("package", err)
			}
			v.Package = s
		case "operation":
			seen |= 1 << 1
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("operation", err)
			}
			v.Operation = s
		default:
			return wire.Unknown(name)
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("package")
	}
	if seen&(1<<1) == 0 {
		return wire.Required("operation")
	}
	return nil
}

// validate checks the rules of the fields of NativeOperation, and reports every one that
// is broken.
func (NativeOperation) validate() error {
	return nil
}

// UnmarshalJSONFrom decodes the JSON object of Binding: it refuses a member that
// the type does not have, a required member that is missing, a null, and a
// value of another JSON kind than the member's, naming the member.
func (v *Binding) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = Binding{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "package":
			seen |= 1 << 0
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("package", err)
			}
			v.Package = s
		case "operation":
			seen |= 1 << 1
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("operation", err)
			}
			v.Operation = s
		case "descriptorHash":
			seen |= 1 << 2
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("descriptorHash", err)
			}
			v.DescriptorHash = s
		default:
			return wire.Unknown(name)
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("package")
	}
	if seen&(1<<1) == 0 {
		return wire.Required("operation")
	}
	if seen&(1<<2) == 0 {
		return wire.Required("descriptorHash")
	}
	return nil
}

// validate checks the rules of the fields of Binding, and reports every one that
// is broken.
func (Binding) validate() error {
	return nil
}
