// Code generated by wiregen; DO NOT EDIT.

package exporttest

import (
	"encoding/json/jsontext"
	"encoding/json/v2"

	"github.com/wspl/demi/go/internal/wire"
)

// DecodeChoiceJSONFrom reads a Choice with its owner's codec.
func DecodeChoiceJSONFrom(dec *jsontext.Decoder) (Choice, error) {
	return decodeChoice(dec)
}

// ValidateChoice checks a Choice using its owner's rules.
func ValidateChoice(value Choice) error {
	return validateChoice(value)
}

// DecodeChoiceJSON reads and validates one complete JSON value.
func DecodeChoiceJSON(data []byte) (Choice, error) {
	var value Choice
	err := json.Unmarshal(data, &value, json.WithUnmarshalers(json.UnmarshalFromFunc(func(dec *jsontext.Decoder, v *Choice) error {
		decoded, err := DecodeChoiceJSONFrom(dec)
		if err == nil {
			*v = decoded
		}
		return err
	})))
	if err != nil {
		return value, wire.Refusal(err)
	}
	return value, ValidateChoice(value)
}

// EncodeChoiceJSON validates and encodes a Choice.
func EncodeChoiceJSON(value Choice) ([]byte, error) {
	if err := ValidateChoice(value); err != nil {
		return nil, err
	}
	data, err := json.Marshal(value, json.Deterministic(true))
	if err != nil {
		return nil, wire.Refusal(err)
	}
	return data, nil
}
func (v Mode) validate() error {
	var r wire.Report
	r.OneOf("", string(v), "read", "write")
	return r.Err()
}

// DecodeModeJSONFrom reads a Mode with its owner's codec.
func DecodeModeJSONFrom(dec *jsontext.Decoder) (Mode, error) {
	text, err := wire.ReadString(dec)
	if err != nil {
		return "", err
	}
	value := Mode(text)
	return value, value.validate()
}

// ValidateMode checks a Mode using its owner's rules.
func ValidateMode(value Mode) error {
	return value.validate()
}

// DecodeModeJSON reads and validates one complete JSON value.
func DecodeModeJSON(data []byte) (Mode, error) {
	var value Mode
	err := json.Unmarshal(data, &value, json.WithUnmarshalers(json.UnmarshalFromFunc(func(dec *jsontext.Decoder, v *Mode) error {
		decoded, err := DecodeModeJSONFrom(dec)
		if err == nil {
			*v = decoded
		}
		return err
	})))
	if err != nil {
		return value, wire.Refusal(err)
	}
	return value, ValidateMode(value)
}

// EncodeModeJSON validates and encodes a Mode.
func EncodeModeJSON(value Mode) ([]byte, error) {
	if err := ValidateMode(value); err != nil {
		return nil, err
	}
	data, err := json.Marshal(value, json.Deterministic(true))
	if err != nil {
		return nil, wire.Refusal(err)
	}
	return data, nil
}
