// Code generated by wiregen; DO NOT EDIT.

package exporttest

import (
	"math"

	"github.com/tinylib/msgp/msgp"
	"github.com/wspl/demi/go/internal/wire"
)

// UnmarshalMsgpack reads the structure of one complete Interval value.
func (v *Interval) UnmarshalMsgpack(data []byte) error {
	*v = Interval{}
	fields, err := wire.MPObject(data)
	if err != nil {
		return err
	}
	seen := map[string]bool{}
	for _, field := range fields {
		switch field.Name {
		case "low":
			seen[field.Name] = true
			value, err := (func(data []byte) (int, error) {
				value, err := wire.MPRead(data, msgp.ReadIntBytes)
				return int(value), err
			})(field.Data)
			if err != nil {
				return wire.In(field.Name, err)
			}
			v.Low = value
		case "high":
			seen[field.Name] = true
			value, err := (func(data []byte) (int, error) {
				value, err := wire.MPRead(data, msgp.ReadIntBytes)
				return int(value), err
			})(field.Data)
			if err != nil {
				return wire.In(field.Name, err)
			}
			v.High = value
		default:
			return wire.Unknown(field.Name)
		}
	}
	if !seen["low"] {
		return wire.Required("low")
	}
	if !seen["high"] {
		return wire.Required("high")
	}
	return nil
}

// DecodeIntervalMsgpack reads and validates one complete value.
func DecodeIntervalMsgpack(data []byte) (Interval, error) {
	var value Interval
	if err := value.UnmarshalMsgpack(data); err != nil {
		return value, err
	}
	return value, value.validate()
}

// MarshalMsgpack encodes Interval as a map in declaration order.
func (v Interval) MarshalMsgpack() ([]byte, error) {
	if err := v.validate(); err != nil {
		return nil, err
	}
	count := uint32(2)
	data := msgp.AppendMapHeader(nil, count)
	data = msgp.AppendString(data, "low")
	{
		if v.Low >= 0 {
			data = msgp.AppendUint64(data, uint64(v.Low))
		} else {
			data = msgp.AppendInt64(data, int64(v.Low))
		}
	}
	data = msgp.AppendString(data, "high")
	{
		if v.High >= 0 {
			data = msgp.AppendUint64(data, uint64(v.High))
		} else {
			data = msgp.AppendInt64(data, int64(v.High))
		}
	}
	return data, nil
}

// UnmarshalMsgpack reads the structure of one complete Rounded value.
func (v *Rounded) UnmarshalMsgpack(data []byte) error {
	*v = Rounded{}
	fields, err := wire.MPObject(data)
	if err != nil {
		return err
	}
	seen := map[string]bool{}
	for _, field := range fields {
		switch field.Name {
		case "value":
			seen[field.Name] = true
			value, err := (func(data []byte) (float64, error) {
				value, err := wire.MPFloat(data)
				return float64(value), err
			})(field.Data)
			if err != nil {
				return wire.In(field.Name, err)
			}
			v.Value = value
		default:
			return wire.Unknown(field.Name)
		}
	}
	if !seen["value"] {
		return wire.Required("value")
	}
	return nil
}

// DecodeRoundedMsgpack reads and validates one complete value.
func DecodeRoundedMsgpack(data []byte) (Rounded, error) {
	var value Rounded
	if err := value.UnmarshalMsgpack(data); err != nil {
		return value, err
	}
	return value, value.validate()
}

// MarshalMsgpack encodes Rounded as a map in declaration order.
func (v Rounded) MarshalMsgpack() ([]byte, error) {
	var err error
	v, err = v.normalizeWire()
	if err != nil {
		return nil, err
	}
	if err := v.validate(); err != nil {
		return nil, err
	}
	count := uint32(1)
	data := msgp.AppendMapHeader(nil, count)
	data = msgp.AppendString(data, "value")
	{
		if math.IsNaN(float64(v.Value)) || math.IsInf(float64(v.Value), 0) {
			return nil, &wire.InvalidError{Path: "value", Rule: "expected finite number"}
		}
		data = msgp.AppendFloat64(data, float64(v.Value))
	}
	return data, nil
}
