// Code generated by contractgen; DO NOT EDIT.
package fixture

import (
	"encoding/json"
	"fmt"
	commandwire "github.com/wspl/demi/internal/commandwire"
	"github.com/wspl/demi/internal/contract"
)

func DecodeEmitArgs(data []byte) (EmitArgs, error) { return contract.Decode[EmitArgs](data) }
func (v EmitArgs) Validate() error                 { return contractValidateEmitArgs(v, 0) }
func contractValidateEmitArgs(v EmitArgs, depth int) error {
	if depth > 1000 {
		return fmt.Errorf("validation nesting exceeds 1000")
	}
	if err := contract.Text(string(v.Text), 0, -1, ""); err != nil {
		return contract.At("text", err)
	}
	return nil
}
func (v *EmitArgs) UnmarshalJSON(data []byte) error {
	obj, err := contract.Decode[map[string]json.RawMessage](data)
	if err != nil {
		return err
	}
	var next EmitArgs
	for key := range obj {
		switch key {
		case "text":
		default:
			return contract.At(key, fmt.Errorf("unknown field"))
		}
	}
	{
		raw, ok := obj["text"]
		if !ok {
			return contract.At("text", fmt.Errorf("required field is absent"))
		}
		if ok {
			value, err := contract.Decode[string](raw)
			if err != nil {
				return contract.At("text", err)
			}
			next.Text = value
		}
	}
	if err := next.Validate(); err != nil {
		return err
	}
	*v = next
	return nil
}
func (v EmitArgs) MarshalJSON() ([]byte, error) {
	if err := v.Validate(); err != nil {
		return nil, err
	}
	fields := []contract.Field{}
	fields = append(fields, contract.Field{Name: "text", Value: v.Text})
	return contract.EncodeObject(fields)
}
func EmitArgsJSONSchema() json.RawMessage {
	return json.RawMessage("{\"additionalProperties\":false,\"description\":\"The input of `probe json emit`.\",\"properties\":{\"text\":{\"description\":\"The text to print\",\"type\":\"string\"}},\"required\":[\"text\"],\"title\":\"EmitArgs\",\"type\":\"object\"}")
}
func DecodeEmitted(data []byte) (Emitted, error) { return contract.Decode[Emitted](data) }
func (v Emitted) Validate() error                { return contractValidateEmitted(v, 0) }
func contractValidateEmitted(v Emitted, depth int) error {
	if depth > 1000 {
		return fmt.Errorf("validation nesting exceeds 1000")
	}
	return nil
}
func (v *Emitted) UnmarshalJSON(data []byte) error {
	obj, err := contract.Decode[map[string]json.RawMessage](data)
	if err != nil {
		return err
	}
	var next Emitted
	{
		raw, ok := obj["ok"]
		if !ok {
			return contract.At("ok", fmt.Errorf("required field is absent"))
		}
		if ok {
			value, err := contract.Decode[bool](raw)
			if err != nil {
				return contract.At("ok", err)
			}
			next.Ok = value
		}
	}
	if err := next.Validate(); err != nil {
		return err
	}
	*v = next
	return nil
}
func (v Emitted) MarshalJSON() ([]byte, error) {
	if err := v.Validate(); err != nil {
		return nil, err
	}
	fields := []contract.Field{}
	fields = append(fields, contract.Field{Name: "ok", Value: v.Ok})
	return contract.EncodeObject(fields)
}
func EmittedJSONSchema() json.RawMessage {
	return json.RawMessage("{\"description\":\"What `probe json emit --json` declares it prints.\",\"properties\":{\"ok\":{\"type\":\"boolean\"}},\"required\":[\"ok\"],\"title\":\"Emitted\",\"type\":\"object\"}")
}
func DecodeHoldArgs(data []byte) (HoldArgs, error) { return contract.Decode[HoldArgs](data) }
func (v HoldArgs) Validate() error                 { return contractValidateHoldArgs(v, 0) }
func contractValidateHoldArgs(v HoldArgs, depth int) error {
	if depth > 1000 {
		return fmt.Errorf("validation nesting exceeds 1000")
	}
	return nil
}
func (v *HoldArgs) UnmarshalJSON(data []byte) error {
	obj, err := contract.Decode[map[string]json.RawMessage](data)
	if err != nil {
		return err
	}
	var next HoldArgs
	for key := range obj {
		switch key {
		case "ms":
		default:
			return contract.At(key, fmt.Errorf("unknown field"))
		}
	}
	{
		raw, ok := obj["ms"]
		if !ok {
			return contract.At("ms", fmt.Errorf("required field is absent"))
		}
		if ok {
			value, err := contract.Decode[uint64](raw)
			if err != nil {
				return contract.At("ms", err)
			}
			next.Ms = value
		}
	}
	if err := next.Validate(); err != nil {
		return err
	}
	*v = next
	return nil
}
func (v HoldArgs) MarshalJSON() ([]byte, error) {
	if err := v.Validate(); err != nil {
		return nil, err
	}
	fields := []contract.Field{}
	fields = append(fields, contract.Field{Name: "ms", Value: v.Ms})
	return contract.EncodeObject(fields)
}
func HoldArgsJSONSchema() json.RawMessage {
	return json.RawMessage("{\"additionalProperties\":false,\"description\":\"The input of `probe hold`.\",\"properties\":{\"ms\":{\"description\":\"Milliseconds to wait\",\"format\":\"uint64\",\"minimum\":0,\"type\":\"integer\"}},\"required\":[\"ms\"],\"title\":\"HoldArgs\",\"type\":\"object\"}")
}
func DecodeTodoArgs(data []byte) (TodoArgs, error) { return contract.Decode[TodoArgs](data) }
func (v TodoArgs) Validate() error                 { return contractValidateTodoArgs(v, 0) }
func contractValidateTodoArgs(v TodoArgs, depth int) error {
	if depth > 1000 {
		return fmt.Errorf("validation nesting exceeds 1000")
	}
	if err := contract.Text(string(v.Text), 0, -1, ""); err != nil {
		return contract.At("text", err)
	}
	return nil
}
func (v *TodoArgs) UnmarshalJSON(data []byte) error {
	obj, err := contract.Decode[map[string]json.RawMessage](data)
	if err != nil {
		return err
	}
	var next TodoArgs
	for key := range obj {
		switch key {
		case "text":
		default:
			return contract.At(key, fmt.Errorf("unknown field"))
		}
	}
	{
		raw, ok := obj["text"]
		if !ok {
			return contract.At("text", fmt.Errorf("required field is absent"))
		}
		if ok {
			value, err := contract.Decode[string](raw)
			if err != nil {
				return contract.At("text", err)
			}
			next.Text = value
		}
	}
	if err := next.Validate(); err != nil {
		return err
	}
	*v = next
	return nil
}
func (v TodoArgs) MarshalJSON() ([]byte, error) {
	if err := v.Validate(); err != nil {
		return nil, err
	}
	fields := []contract.Field{}
	fields = append(fields, contract.Field{Name: "text", Value: v.Text})
	return contract.EncodeObject(fields)
}
func TodoArgsJSONSchema() json.RawMessage {
	return json.RawMessage("{\"additionalProperties\":false,\"description\":\"The input of `todo add` and `todo note`.\",\"properties\":{\"text\":{\"description\":\"Todo text\",\"type\":\"string\"}},\"required\":[\"text\"],\"title\":\"TodoArgs\",\"type\":\"object\"}")
}
func DecodeWhereArgs(data []byte) (WhereArgs, error) { return contract.Decode[WhereArgs](data) }
func (v WhereArgs) Validate() error                  { return contractValidateWhereArgs(v, 0) }
func contractValidateWhereArgs(v WhereArgs, depth int) error {
	if depth > 1000 {
		return fmt.Errorf("validation nesting exceeds 1000")
	}
	if v.Label != nil {
		if err := contract.Text(string((*v.Label)), 0, -1, ""); err != nil {
			return contract.At("label", err)
		}
	}
	return nil
}
func (v *WhereArgs) UnmarshalJSON(data []byte) error {
	obj, err := contract.Decode[map[string]json.RawMessage](data)
	if err != nil {
		return err
	}
	var next WhereArgs
	for key := range obj {
		switch key {
		case "label":
		default:
			return contract.At(key, fmt.Errorf("unknown field"))
		}
	}
	{
		raw, ok := obj["label"]
		if ok {
			value, err := func(b []byte) (*string, error) { return contract.Pointer(b, contract.Decode[string]) }(raw)
			if err != nil {
				return contract.At("label", err)
			}
			next.Label = value
		}
	}
	if err := next.Validate(); err != nil {
		return err
	}
	*v = next
	return nil
}
func (v WhereArgs) MarshalJSON() ([]byte, error) {
	if err := v.Validate(); err != nil {
		return nil, err
	}
	fields := []contract.Field{}
	if v.Label != nil {
		fields = append(fields, contract.Field{Name: "label", Value: v.Label})
	}
	return contract.EncodeObject(fields)
}
func WhereArgsJSONSchema() json.RawMessage {
	return json.RawMessage("{\"additionalProperties\":false,\"description\":\"The input of the fixture's `where`, which only its schema declares: the\\nnative operation reads it.\",\"properties\":{\"label\":{\"description\":\"A label the operation reports\",\"type\":\"string\"}},\"title\":\"WhereArgs\",\"type\":\"object\"}")
}
func DecodeWhereReport(data []byte) (WhereReport, error) { return contract.Decode[WhereReport](data) }
func (v WhereReport) Validate() error                    { return contractValidateWhereReport(v, 0) }
func contractValidateWhereReport(v WhereReport, depth int) error {
	if depth > 1000 {
		return fmt.Errorf("validation nesting exceeds 1000")
	}
	if v.Label != nil {
		if err := contract.Text(string((*v.Label)), 0, -1, ""); err != nil {
			return contract.At("label", err)
		}
	}
	if err := v.Context.Validate(); err != nil {
		return contract.At("context", err)
	}
	if err := contract.Text(string(v.CWD), 0, -1, ""); err != nil {
		return contract.At("cwd", err)
	}
	if v.Value != nil {
		if err := contract.Text(string((*v.Value)), 0, -1, ""); err != nil {
			return contract.At("value", err)
		}
	}
	return nil
}
func (v *WhereReport) UnmarshalJSON(data []byte) error {
	obj, err := contract.Decode[map[string]json.RawMessage](data)
	if err != nil {
		return err
	}
	var next WhereReport
	for key := range obj {
		switch key {
		case "label", "context", "cwd", "value":
		default:
			return contract.At(key, fmt.Errorf("unknown field"))
		}
	}
	{
		raw, ok := obj["label"]
		if !ok {
			return contract.At("label", fmt.Errorf("required field is absent"))
		}
		if ok {
			if !contract.IsNull(raw) {
				value, err := func(b []byte) (*string, error) { return contract.Pointer(b, contract.Decode[string]) }(raw)
				if err != nil {
					return contract.At("label", err)
				}
				next.Label = value
			}
		}
	}
	{
		raw, ok := obj["context"]
		if !ok {
			return contract.At("context", fmt.Errorf("required field is absent"))
		}
		if ok {
			value, err := contract.Decode[commandwire.Context](raw)
			if err != nil {
				return contract.At("context", err)
			}
			next.Context = value
		}
	}
	{
		raw, ok := obj["cwd"]
		if !ok {
			return contract.At("cwd", fmt.Errorf("required field is absent"))
		}
		if ok {
			value, err := contract.Decode[string](raw)
			if err != nil {
				return contract.At("cwd", err)
			}
			next.CWD = value
		}
	}
	{
		raw, ok := obj["value"]
		if !ok {
			return contract.At("value", fmt.Errorf("required field is absent"))
		}
		if ok {
			if !contract.IsNull(raw) {
				value, err := func(b []byte) (*string, error) { return contract.Pointer(b, contract.Decode[string]) }(raw)
				if err != nil {
					return contract.At("value", err)
				}
				next.Value = value
			}
		}
	}
	if err := next.Validate(); err != nil {
		return err
	}
	*v = next
	return nil
}
func (v WhereReport) MarshalJSON() ([]byte, error) {
	if err := v.Validate(); err != nil {
		return nil, err
	}
	fields := []contract.Field{}
	fields = append(fields, contract.Field{Name: "label", Value: v.Label})
	fields = append(fields, contract.Field{Name: "context", Value: v.Context})
	fields = append(fields, contract.Field{Name: "cwd", Value: v.CWD})
	fields = append(fields, contract.Field{Name: "value", Value: v.Value})
	return contract.EncodeObject(fields)
}
