cmake_minimum_required(VERSION 3.20)
project(demi_ipc_size C)
set(LIBUV_BUILD_SHARED OFF CACHE BOOL "" FORCE)
set(LIBUV_BUILD_TESTS OFF CACHE BOOL "" FORCE)
set(LIBUV_BUILD_BENCH OFF CACHE BOOL "" FORCE)
add_subdirectory("${CMAKE_CURRENT_SOURCE_DIR}/../../../vendor/txiki.js/deps/libuv" libuv)
add_executable(ipc-uv uv.c)
target_link_libraries(ipc-uv PRIVATE uv_a)
if(UNIX)
    add_executable(ipc-posix posix.c)
    target_link_libraries(ipc-posix PRIVATE pthread)
endif()
