import {
  decodeJwtPayload,
  delay,
  errorCode,
  errorMessage,
  nonEmptyString
} from '@demicodes/utils'
import { z } from 'zod'
import { mkdir, open, readFile, rm } from 'node:fs/promises'
import { homedir } from 'node:os'
import { dirname, join } from 'node:path'
import {
  redactCredentialText,
  reportedStringSchema,
  type ProviderAuthState
} from '@demicodes/provider'
import { writeJsonFileAtomic } from '@demicodes/provider/credentials-pool'

export const CODEX_AUTH_MODES = [
  'apiKey',
  'chatgpt',
  'chatgptAuthTokens',
  'agentIdentity',
  'personalAccessToken',
  'bedrockApiKey',
] as const

export type CodexAuthMode = (typeof CODEX_AUTH_MODES)[number]

/** The ChatGPT tokens of an `auth.json`, as official Codex writes them. */
const codexTokenDataSchema = z.looseObject({
  // A refresh response may hand back the id token as its decoded claims.
  id_token: z.union([z.string(), z.looseObject({})]).nullish(),
  access_token: z.string().nullish(),
  refresh_token: z.string().nullish(),
  account_id: z.string().nullish(),
})

export type CodexTokenData = z.infer<typeof codexTokenDataSchema>

/** The agent identity of an `auth.json`, generated by official Codex. */
const codexAgentIdentitySchema = z.looseObject({
  authorization: z.string().nullish(),
  account_id: z.string().nullish(),
  chatgpt_account_is_fedramp: z.boolean().nullish(),
})

/**
 * Codex's `auth.json`, of which Demi reads the fields below. Every other field
 * survives a decode, because the store rewrites the whole file on refresh and
 * must not drop what a newer Codex wrote.
 */
export const codexAuthDotJsonSchema = z.looseObject({
  auth_mode: z.enum(CODEX_AUTH_MODES).nullish(),
  OPENAI_API_KEY: z.string().nullish(),
  tokens: codexTokenDataSchema.nullish(),
  last_refresh: z.string().nullish(),
  agent_identity: codexAgentIdentitySchema.nullish(),
  personal_access_token: z.string().nullish(),
  bedrock_api_key: z.unknown().optional(),
})

export type CodexAuthDotJson = z.infer<typeof codexAuthDotJsonSchema>

export type CodexResolvedAuth =
  | {
      kind: 'chatgpt'
      mode: 'chatgpt' | 'chatgptAuthTokens'
      accessToken: string
      refreshToken: string | null
      accountId: string
      email: string | null
      isFedrampAccount: boolean
      expiresAt: Date | null
      authFile: string
    }
  | {
      kind: 'apiKey'
      mode: 'apiKey'
      apiKey: string
      authFile: string | null
    }
  | {
      kind: 'personalAccessToken'
      mode: 'personalAccessToken'
      accessToken: string
      accountId: string | null
      authFile: string
    }
  | {
      kind: 'agentIdentity'
      mode: 'agentIdentity'
      authorization: string
      accountId: string
      isFedrampAccount: boolean
      authFile: string
    }

export interface CodexAuthStore {
  status(): Promise<ProviderAuthState>
  resolveAuth(options?: { forceRefresh?: boolean }): Promise<CodexResolvedAuth>
}

export async function codexAuthStatus(
  options: FileCodexAuthStoreOptions = {}
): Promise<ProviderAuthState> {
  return new FileCodexAuthStore(options).status()
}

export interface FileCodexAuthStoreOptions {
  codexHome?: string
  /** Override auth.json path (e.g. demi credential pool entry). */
  authFile?: string
  refresh?: CodexTokenRefresh
  now?: () => Date
  lockRetryDelayMs?: number
  lockTimeoutMs?: number
}

/**
 * The OAuth token endpoint's answer to a refresh. A response without an access
 * token is a failed refresh however it is spelled, so the field is required.
 */
export const refreshTokenResponseSchema = z.looseObject({
  access_token: z.string().min(1),
  refresh_token: z.string().min(1).optional(),
  id_token: z.string().min(1).optional(),
})

export type RefreshTokenResponse = z.infer<typeof refreshTokenResponseSchema>

export type CodexTokenRefresh = (
  refreshToken: string,
  signal?: AbortSignal
) => Promise<RefreshTokenResponse>

/**
 * Codex error text may embed the env-provided API key by name; redact it
 * alongside the standard fields.
 */
const SECRET_FIELD_PATTERNS = ['OPENAI_API_KEY']

export function redactCodexSecretText(text: string): string {
  return redactCredentialText(text, SECRET_FIELD_PATTERNS)
}

const CODEX_OAUTH_CLIENT_ID = 'app_EMoamEEZ73f0CkXaXp7hrann'
const TOKEN_REFRESH_URL = 'https://auth.openai.com/oauth/token'

/** OAuth client id shared by token refresh and device-code login. */
export function codexOauthClientId(): string {
  return process.env.CODEX_APP_SERVER_LOGIN_CLIENT_ID || CODEX_OAUTH_CLIENT_ID
}
const REFRESH_EXPIRY_SKEW_MS = 5 * 60 * 1000
const REFRESH_STALENESS_MS = 8 * 24 * 60 * 60 * 1000

export class FileCodexAuthStore implements CodexAuthStore {
  readonly codexHome: string
  readonly authFile: string

  private readonly refreshImpl: CodexTokenRefresh
  private readonly now: () => Date
  private readonly lockRetryDelayMs: number
  private readonly lockTimeoutMs: number

  constructor(options: FileCodexAuthStoreOptions = {}) {
    this.codexHome = options.codexHome ?? defaultCodexHome()
    this.authFile = options.authFile ?? join(this.codexHome, 'auth.json')
    this.refreshImpl = options.refresh ?? refreshCodexToken
    this.now = options.now ?? (() => new Date())
    this.lockRetryDelayMs = options.lockRetryDelayMs ?? 25
    this.lockTimeoutMs = options.lockTimeoutMs ?? 5_000
  }

  async status(): Promise<ProviderAuthState> {
    try {
      const auth = await this.resolveAuth()
      if (auth.kind === 'chatgpt') {
        return {
          status: 'authenticated',
          accountLabel: auth.email ?? auth.accountId
        }
      }
      if (auth.kind === 'apiKey')
        return {
          status: 'authenticated',
          accountLabel: 'OPENAI_API_KEY'
        }
      if (auth.kind === 'personalAccessToken')
        return {
          status: 'authenticated',
          accountLabel: auth.accountId ?? 'personal access token'
        }
      return { status: 'authenticated', accountLabel: auth.accountId }
    } catch (error) {
      if (error instanceof CodexAuthError && error.code === 'auth_missing')
        return {
        status: 'unauthenticated',
        message: error.message
      }
      if (error instanceof CodexAuthError && error.code === 'auth_unsupported')
        return {
        status: 'error',
        message: error.message
      }
      return {
        status: 'error',
        message: redactCodexSecretText(error instanceof Error
          ? error.message
          : String(error))
      }
    }
  }

  async resolveAuth(
    options: { forceRefresh?: boolean } = {}
  ): Promise<CodexResolvedAuth> {
    const auth = await this.readAuthFile()
    const mode = resolvedAuthMode(auth)

    if (mode === 'bedrockApiKey') {
      throw new CodexAuthError(
        'auth_unsupported',
        'Codex provider does not support Bedrock auth'
      )
    }
    if (mode === 'apiKey') {
      const key = nonEmptyString(auth.OPENAI_API_KEY)
      if (!key)
        throw new CodexAuthError(
          'auth_missing',
          `No OPENAI_API_KEY found in ${this.authFile}`
        )
      return { kind: 'apiKey', mode, apiKey: key, authFile: this.authFile }
    }
    if (mode === 'personalAccessToken') {
      const token = nonEmptyString(auth.personal_access_token)
      if (!token)
        throw new CodexAuthError(
          'auth_missing',
          `No personal access token found in ${this.authFile}`
        )
      const claims = parseChatGptClaims(token)
      return {
        kind: 'personalAccessToken',
        mode,
        accessToken: token,
        accountId: claims.accountId,
        authFile: this.authFile,
      }
    }
    if (mode === 'agentIdentity') {
      return resolveAgentIdentity(auth, this.authFile)
    }

    const chatgpt = resolveChatGptAuthFromFile(auth, this.authFile)
    const lastRefresh = parseDate(auth.last_refresh)
    const shouldRefresh =
      options.forceRefresh === true ||
      expiresWithin(chatgpt.expiresAt, this.now(), REFRESH_EXPIRY_SKEW_MS) ||
      olderThan(lastRefresh, this.now(), REFRESH_STALENESS_MS)

    if (shouldRefresh && chatgpt.refreshToken)
      return this.refreshAndResolve(auth, chatgpt.refreshToken)
    return chatgpt
  }

  private async refreshAndResolve(
    auth: CodexAuthDotJson,
    refreshToken: string
  ): Promise<CodexResolvedAuth> {
    return this.withAuthFileLock(async () => {
      const latest = await this.readAuthFile()
      const latestTokens = latest.tokens
      const latestRefreshToken = nonEmptyString(latestTokens?.refresh_token)
        ?? refreshToken
      const response = await this.refreshImpl(latestRefreshToken)
      const nextTokens: CodexTokenData = {
        ...(latestTokens ?? {}),
        access_token: response.access_token,
        ...(response.id_token ? { id_token: response.id_token } : {}),
        ...(response.refresh_token
          ? { refresh_token: response.refresh_token }
          : {}),
      }
      const nextAuth: CodexAuthDotJson = {
        ...latest,
        auth_mode: latest.auth_mode ?? auth.auth_mode ?? 'chatgpt',
        tokens: nextTokens,
        last_refresh: this.now().toISOString(),
      }
      await writeJsonFileAtomic(this.authFile, nextAuth)
      return resolveChatGptAuthFromFile(nextAuth, this.authFile)
    })
  }

  private async readAuthFile(): Promise<CodexAuthDotJson> {
    let text: string
    try {
      text = await readFile(this.authFile, 'utf8')
    } catch (error) {
      if (errorCode(error) === 'ENOENT') {
        throw new CodexAuthError(
          'auth_missing',
          `Codex auth file not found: ${this.authFile}`
        )
      }
      throw new CodexAuthError(
        'auth_invalid',
        `Failed to read Codex auth file ${this.authFile}: ${redactCodexSecretText(errorMessage(error))}`
      )
    }
    return parseCodexAuthDotJson(
      text,
      `Codex auth file ${this.authFile}`
    )
  }

  private async withAuthFileLock<T>(fn: () => Promise<T>): Promise<T> {
    const lockFile = `${this.authFile}.lock`
    await mkdir(dirname(this.authFile), { recursive: true })
    const started = Date.now()
    let handle: Awaited<ReturnType<typeof open>> | null = null
    while (!handle) {
      try {
        handle = await open(lockFile, 'wx', 0o600)
      } catch (error) {
        if (errorCode(error) !== 'EEXIST'
          || Date.now() - started > this.lockTimeoutMs) {
          throw new CodexAuthError(
            'auth_lock_failed',
            `Failed to lock Codex auth file: ${redactCodexSecretText(errorMessage(error))}`
          )
        }
        await delay(this.lockRetryDelayMs)
      }
    }

    try {
      return await fn()
    } finally {
      await handle.close().catch(() => undefined)
      await rm(lockFile, { force: true }).catch(() => undefined)
    }
  }
}

export class StaticCodexAuthStore implements CodexAuthStore {
  constructor(private readonly auth: CodexResolvedAuth) {}

  async status(): Promise<ProviderAuthState> {
    return { status: 'authenticated', accountLabel: this.auth.kind }
  }

  async resolveAuth(): Promise<CodexResolvedAuth> {
    return this.auth
  }
}

export class CodexAuthError extends Error {
  constructor(
    readonly code:
      | 'auth_missing'
      | 'auth_invalid'
      | 'auth_unsupported'
      | 'auth_refresh_failed'
      | 'auth_login_failed'
      | 'auth_lock_failed',
    message: string,
  ) {
    super(message)
    this.name = 'CodexAuthError'
  }
}

export function defaultCodexHome(): string {
  return process.env.CODEX_HOME
    && process.env.CODEX_HOME.trim() ? process.env.CODEX_HOME : join(
    homedir(),
    '.codex'
  )
}

export function resolvedAuthMode(auth: CodexAuthDotJson): CodexAuthMode {
  if (auth.auth_mode)
    return auth.auth_mode
  if (auth.personal_access_token)
    return 'personalAccessToken'
  if (auth.bedrock_api_key)
    return 'bedrockApiKey'
  if (auth.OPENAI_API_KEY)
    return 'apiKey'
  if (auth.agent_identity)
    return 'agentIdentity'
  return 'chatgpt'
}

/**
 * A claim Demi only labels the account with. The signature is not verified and
 * the backend is what accepts or rejects the token, so a claim of the wrong
 * type reads as absent rather than failing an otherwise usable login.
 */
const claimFlagSchema = z.boolean().optional().catch(undefined)

/** The ChatGPT claims Demi reads from an access or personal-access token. */
const chatGptClaimsSchema = z.looseObject({
  // Expiry only decides when to refresh early; an unreadable one means the
  // store refreshes on the vendor's 401 instead.
  exp: z.number().optional().catch(undefined),
  email: reportedStringSchema,
  'https://api.openai.com/auth': z.looseObject({
    chatgpt_account_id: reportedStringSchema,
    chatgpt_account_is_fedramp: claimFlagSchema,
  }).optional().catch(undefined),
  'https://api.openai.com/profile': z.looseObject({
    email: reportedStringSchema,
  }).optional().catch(undefined),
})

/** The id token's claims, either as a token or already decoded by Codex. */
const idTokenClaimsSchema = z.looseObject({
  chatgpt_account_id: reportedStringSchema,
  email: reportedStringSchema,
  chatgpt_account_is_fedramp: claimFlagSchema,
})

export interface CodexAccountClaims {
  accountId: string | null
  email: string | null
  isFedrampAccount: boolean
}

const NO_CLAIMS: CodexAccountClaims = {
  accountId: null,
  email: null,
  isFedrampAccount: false,
}

export function parseJwtExpiration(jwt: string): Date | null {
  const payload = decodeJwtPayload(jwt)
  if (payload === null)
    return null
  const exp = chatGptClaimsSchema.parse(payload).exp
  return exp === undefined ? null : new Date(exp * 1000)
}

export function parseChatGptClaims(jwt: string): CodexAccountClaims {
  const payload = decodeJwtPayload(jwt)
  // A token Demi cannot read carries no claims; the backend still decides
  // whether the token itself is good.
  if (payload === null)
    return NO_CLAIMS
  const claims = chatGptClaimsSchema.parse(payload)
  const auth = claims['https://api.openai.com/auth']
  const profile = claims['https://api.openai.com/profile']
  return {
    accountId: auth?.chatgpt_account_id ?? null,
    email: claims.email ?? profile?.email ?? null,
    isFedrampAccount: auth?.chatgpt_account_is_fedramp === true,
  }
}

export function parseIdTokenClaims(
  idToken: CodexTokenData['id_token']
): CodexAccountClaims {
  if (typeof idToken === 'string')
    return parseChatGptClaims(idToken)
  if (!idToken)
    return NO_CLAIMS
  const claims = idTokenClaimsSchema.parse(idToken)
  return {
    accountId: claims.chatgpt_account_id ?? null,
    email: claims.email ?? null,
    isFedrampAccount: claims.chatgpt_account_is_fedramp === true,
  }
}

export async function refreshCodexToken(
  refreshToken: string,
  signal?: AbortSignal
): Promise<RefreshTokenResponse> {
  const response = await fetch(TOKEN_REFRESH_URL, {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({
      client_id: codexOauthClientId(),
      grant_type: 'refresh_token',
      refresh_token: refreshToken,
    }),
    signal,
  })
  if (!response.ok) {
    throw new CodexAuthError(
      'auth_refresh_failed',
      `Codex token refresh failed with HTTP ${response.status}`
    )
  }
  return refreshTokenResponseSchema.parse(await response.json())
}

/**
 * Decodes stored Codex auth material. `what` names the source in the error a
 * malformed file or payload raises; corrupt material is reported, never
 * repaired.
 */
export function parseCodexAuthDotJson(
  text: string,
  what: string
): CodexAuthDotJson {
  let value: unknown
  try {
    value = JSON.parse(text)
  } catch {
    throw new CodexAuthError('auth_invalid', `${what} is not valid JSON`)
  }
  const auth = codexAuthDotJsonSchema.safeParse(value)
  if (!auth.success) {
    throw new CodexAuthError(
      'auth_invalid',
      `${what} is malformed: ${redactCodexSecretText(z.prettifyError(auth.error))}`,
    )
  }
  return auth.data
}


/** The ChatGPT auth an `auth.json` holds, before any refresh decision. */
function resolveChatGptAuthFromFile(
  auth: CodexAuthDotJson,
  authFile: string
): Extract<CodexResolvedAuth, { kind: 'chatgpt' }> {
  const tokens = auth.tokens
  if (!tokens)
    throw new CodexAuthError(
      'auth_missing',
      `No ChatGPT tokens found in ${authFile}`
    )
  const accessToken = nonEmptyString(tokens.access_token)
  if (!accessToken)
    throw new CodexAuthError(
      'auth_missing',
      `No ChatGPT access token found in ${authFile}`
    )
  const claims = parseChatGptClaims(accessToken)
  const idClaims = parseIdTokenClaims(tokens.id_token)
  const accountId = nonEmptyString(tokens.account_id) ?? claims.accountId
    ?? idClaims.accountId
  if (!accountId)
    throw new CodexAuthError(
      'auth_missing',
      `No ChatGPT account id found in ${authFile}`
    )
  return {
    kind: 'chatgpt',
    mode: resolvedAuthMode(auth) === 'chatgptAuthTokens'
      ? 'chatgptAuthTokens'
      : 'chatgpt',
    accessToken,
    refreshToken: nonEmptyString(tokens.refresh_token) ?? null,
    accountId,
    email: idClaims.email ?? claims.email,
    isFedrampAccount: idClaims.isFedrampAccount || claims.isFedrampAccount,
    expiresAt: parseJwtExpiration(accessToken),
    authFile,
  }
}

function resolveAgentIdentity(
  auth: CodexAuthDotJson,
  authFile: string
): CodexResolvedAuth {
  const value = auth.agent_identity
  const authorization = nonEmptyString(value?.authorization)
  const accountId = nonEmptyString(value?.account_id)
  if (!authorization || !accountId) {
    throw new CodexAuthError(
      'auth_unsupported',
      'Codex agent identity auth requires an authorization header generated by official Codex',
    )
  }
  return {
    kind: 'agentIdentity',
    mode: 'agentIdentity',
    authorization,
    accountId,
    isFedrampAccount: value?.chatgpt_account_is_fedramp === true,
    authFile,
  }
}

function expiresWithin(
  expiresAt: Date | null,
  now: Date,
  skewMs: number
): boolean {
  return expiresAt !== null && expiresAt.getTime() - now.getTime() <= skewMs
}

function olderThan(value: Date | null, now: Date, ageMs: number): boolean {
  return value !== null && now.getTime() - value.getTime() >= ageMs
}

function parseDate(value: unknown): Date | null {
  if (typeof value !== 'string' || !value)
    return null
  const ms = Date.parse(value)
  return Number.isFinite(ms) ? new Date(ms) : null
}

