// Code generated by contractgen; DO NOT EDIT.

package packedonly

import (
	"fmt"
	"github.com/wspl/demi/internal/contract"
)

func (v Value) Validate() error { return contractValidateValue(v, 0) }
func contractValidateValue(v Value, depth int) error {
	if depth > 1000 {
		return fmt.Errorf("validation nesting exceeds 1000")
	}
	if err := contract.Text(string(v.Text), 0, -1, ""); err != nil {
		return contract.At("text", err)
	}
	return nil
}
func DecodeValueMsgpack(data []byte) (Value, error) { return contract.DecodeMsgpack[Value](data) }
func (v *Value) UnmarshalMsgpack(data []byte) error {
	obj, err := contract.MsgpackObject(data)
	if err != nil {
		return err
	}
	var next Value
	{
		raw, present := obj["text"]
		delete(obj, "text")
		if !present {
			return contract.At("text", fmt.Errorf("required field is absent"))
		}
		if present {
			value, err := contract.DecodeMsgpack[string](raw)
			if err != nil {
				return contract.At("text", err)
			}
			next.Text = value
		}
	}
	for key := range obj {
		return contract.At(key, fmt.Errorf("unknown field"))
	}
	if err := next.Validate(); err != nil {
		return err
	}
	*v = next
	return nil
}
func (v Value) MarshalMsgpack() ([]byte, error) {
	if err := v.Validate(); err != nil {
		return nil, err
	}
	fields := []contract.Field{}
	fields = append(fields, contract.Field{Name: "text", Value: v.Text})
	return contract.EncodeMsgpackObject(fields)
}
