// Code generated by wiregen; DO NOT EDIT.

package webapi

import (
	"encoding/json/jsontext"
	"encoding/json/v2"
	"fmt"
	"maps"
	"slices"

	"github.com/wspl/demi/go/agentproto"
	"github.com/wspl/demi/go/core"
	"github.com/wspl/demi/go/internal/wire"
)

// decodeConversationTarget decodes the JSON object of a ConversationTarget, whichever variant it is.
func decodeConversationTarget(dec *jsontext.Decoder) (ConversationTarget, error) {
	raw, err := wire.ReadObject(dec)
	if err != nil {
		return nil, err
	}
	tag, err := wire.Tag(raw, "kind")
	if err != nil {
		return nil, err
	}
	switch tag {
	case "cloud":
		var v ConversationTargetCloud
		if err := v.UnmarshalJSONFrom(wire.NewDecoder(raw)); err != nil {
			return nil, err
		}
		return v, nil
	case "device":
		var v ConversationTargetDevice
		if err := v.UnmarshalJSONFrom(wire.NewDecoder(raw)); err != nil {
			return nil, err
		}
		return v, nil
	case "workspace":
		var v ConversationTargetWorkspace
		if err := v.UnmarshalJSONFrom(wire.NewDecoder(raw)); err != nil {
			return nil, err
		}
		return v, nil
	}
	return nil, wire.UnknownTag("kind", "cloud", "device", "workspace")
}

// validateConversationTarget checks the rules of the variant that v is.
func validateConversationTarget(v ConversationTarget) error {
	switch v := v.(type) {
	case nil:
		return wire.Required("")
	case ConversationTargetCloud:
		return v.validate()
	case *ConversationTargetCloud:
		if v == nil {
			return fmt.Errorf("a nil %T is not a variant of ConversationTarget", v)
		}
		return v.validate()
	case ConversationTargetDevice:
		return v.validate()
	case *ConversationTargetDevice:
		if v == nil {
			return fmt.Errorf("a nil %T is not a variant of ConversationTarget", v)
		}
		return v.validate()
	case ConversationTargetWorkspace:
		return v.validate()
	case *ConversationTargetWorkspace:
		if v == nil {
			return fmt.Errorf("a nil %T is not a variant of ConversationTarget", v)
		}
		return v.validate()
	}
	return fmt.Errorf("%T is not a variant of ConversationTarget", v)
}

// UnmarshalJSONFrom decodes the JSON object of ConversationTargetCloud: it refuses a member that
// the type does not have, a required member that is missing, a null, and a
// value of another JSON kind than the member's, naming the member.
func (v *ConversationTargetCloud) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = ConversationTargetCloud{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "kind":
			seen |= 1 << 0
			tag, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("kind", err)
			}
			if tag != "cloud" {
				return wire.UnknownTag("kind", "cloud")
			}
		case "path":
			if wire.IsNull(dec) {
				return wire.In("path", wire.Null())
			}
			var value string
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("path", err)
			}
			value = s
			v.Path = &value
		default:
			return wire.Unknown(name)
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("kind")
	}
	return nil
}

// MarshalJSONTo encodes ConversationTargetCloud as a JSON object that starts with its tag.
func (v ConversationTargetCloud) MarshalJSONTo(enc *jsontext.Encoder) error {
	return json.MarshalEncode(enc, struct {
		Tag  string  `json:"kind"`
		Path *string `json:"path,omitzero"`
	}{"cloud", v.Path})
}

// validate checks the rules of the fields of ConversationTargetCloud, and reports every one that
// is broken.
func (v ConversationTargetCloud) validate() error {
	var r wire.Report
	if v.Path != nil {
		r.Bytes("path", (*v.Path), wire.AtLeast(1))
		r.Pattern("path", (*v.Path), ConversationTargetPathPattern)
	}
	return r.Err()
}

// UnmarshalJSONFrom decodes the JSON object of ConversationTargetDevice: it refuses a member that
// the type does not have, a required member that is missing, a null, and a
// value of another JSON kind than the member's, naming the member.
func (v *ConversationTargetDevice) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = ConversationTargetDevice{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "kind":
			seen |= 1 << 0
			tag, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("kind", err)
			}
			if tag != "device" {
				return wire.UnknownTag("kind", "device")
			}
		case "deviceId":
			seen |= 1 << 1
			if err := v.DeviceID.UnmarshalJSONFrom(dec); err != nil {
				return wire.In("deviceId", err)
			}
		case "path":
			seen |= 1 << 2
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("path", err)
			}
			v.Path = s
		default:
			return wire.Unknown(name)
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("kind")
	}
	if seen&(1<<1) == 0 {
		return wire.Required("deviceId")
	}
	if seen&(1<<2) == 0 {
		return wire.Required("path")
	}
	return nil
}

// MarshalJSONTo encodes ConversationTargetDevice as a JSON object that starts with its tag.
func (v ConversationTargetDevice) MarshalJSONTo(enc *jsontext.Encoder) error {
	return json.MarshalEncode(enc, struct {
		Tag      string   `json:"kind"`
		DeviceID DeviceID `json:"deviceId"`
		Path     string   `json:"path"`
	}{"device", v.DeviceID, v.Path})
}

// validate checks the rules of the fields of ConversationTargetDevice, and reports every one that
// is broken.
func (v ConversationTargetDevice) validate() error {
	var r wire.Report
	r.Check("deviceId", Validate(v.DeviceID))
	r.Bytes("path", v.Path, wire.AtLeast(1))
	return r.Err()
}

// UnmarshalJSONFrom decodes the JSON object of ConversationTargetWorkspace: it refuses a member that
// the type does not have, a required member that is missing, a null, and a
// value of another JSON kind than the member's, naming the member.
func (v *ConversationTargetWorkspace) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = ConversationTargetWorkspace{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "kind":
			seen |= 1 << 0
			tag, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("kind", err)
			}
			if tag != "workspace" {
				return wire.UnknownTag("kind", "workspace")
			}
		case "workspaceId":
			seen |= 1 << 1
			if err := v.WorkspaceID.UnmarshalJSONFrom(dec); err != nil {
				return wire.In("workspaceId", err)
			}
		default:
			return wire.Unknown(name)
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("kind")
	}
	if seen&(1<<1) == 0 {
		return wire.Required("workspaceId")
	}
	return nil
}

// MarshalJSONTo encodes ConversationTargetWorkspace as a JSON object that starts with its tag.
func (v ConversationTargetWorkspace) MarshalJSONTo(enc *jsontext.Encoder) error {
	return json.MarshalEncode(enc, struct {
		Tag         string      `json:"kind"`
		WorkspaceID WorkspaceID `json:"workspaceId"`
	}{"workspace", v.WorkspaceID})
}

// validate checks the rules of the fields of ConversationTargetWorkspace, and reports every one that
// is broken.
func (v ConversationTargetWorkspace) validate() error {
	var r wire.Report
	r.Check("workspaceId", Validate(v.WorkspaceID))
	return r.Err()
}

// UnmarshalJSONFrom decodes the JSON object of CreateConversation: it refuses a member that
// the type does not have, a required member that is missing, a null, and a
// value of another JSON kind than the member's, naming the member.
func (v *CreateConversation) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = CreateConversation{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "id":
			seen |= 1 << 0
			if err := v.ID.UnmarshalJSONFrom(dec); err != nil {
				return wire.In("id", err)
			}
		default:
			return wire.Unknown(name)
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("id")
	}
	return nil
}

// validate checks the rules of the fields of CreateConversation, and reports every one that
// is broken.
func (v CreateConversation) validate() error {
	var r wire.Report
	r.Check("id", Validate(v.ID))
	return r.Err()
}

// UnmarshalJSONFrom decodes the JSON object of ConversationSummary: it ignores a member that
// the type does not have, and refuses a required member that is missing, a
// null, and a value of another JSON kind than the member's, naming the member.
func (v *ConversationSummary) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = ConversationSummary{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "id":
			seen |= 1 << 0
			if err := v.ID.UnmarshalJSONFrom(dec); err != nil {
				return wire.In("id", err)
			}
		case "title":
			seen |= 1 << 1
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("title", err)
			}
			v.Title = s
		case "archived":
			seen |= 1 << 2
			b, err := wire.ReadBool(dec)
			if err != nil {
				return wire.In("archived", err)
			}
			v.Archived = b
		case "pinned":
			seen |= 1 << 3
			b, err := wire.ReadBool(dec)
			if err != nil {
				return wire.In("pinned", err)
			}
			v.Pinned = b
		case "readRevision":
			seen |= 1 << 4
			n, err := wire.ReadUint(dec, 64)
			if err != nil {
				return wire.In("readRevision", err)
			}
			v.ReadRevision = n
		case "target":
			seen |= 1 << 5
			u, err := decodeConversationTarget(dec)
			if err != nil {
				return wire.In("target", err)
			}
			v.Target = u
		case "contextVersion":
			seen |= 1 << 6
			n, err := wire.ReadUint(dec, 64)
			if err != nil {
				return wire.In("contextVersion", err)
			}
			v.ContextVersion = n
		case "model":
			seen |= 1 << 7
			if wire.IsNull(dec) {
				if _, err := dec.ReadToken(); err != nil {
					return wire.In("model", err)
				}
			} else {
				var value ModelSettings
				if err := value.UnmarshalJSONFrom(dec); err != nil {
					return wire.In("model", err)
				}
				v.Model = &value
			}
		case "createdAt":
			seen |= 1 << 8
			if err := v.CreatedAt.UnmarshalJSONFrom(dec); err != nil {
				return wire.In("createdAt", err)
			}
		case "updatedAt":
			seen |= 1 << 9
			if err := v.UpdatedAt.UnmarshalJSONFrom(dec); err != nil {
				return wire.In("updatedAt", err)
			}
		case "cwd":
			seen |= 1 << 10
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("cwd", err)
			}
			v.Cwd = s
		case "status":
			seen |= 1 << 11
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("status", err)
			}
			v.Status = ConversationStatus(s)
		case "revision":
			seen |= 1 << 12
			n, err := wire.ReadUint(dec, 64)
			if err != nil {
				return wire.In("revision", err)
			}
			v.Revision = n
		case "unread":
			seen |= 1 << 13
			b, err := wire.ReadBool(dec)
			if err != nil {
				return wire.In("unread", err)
			}
			v.Unread = b
		case "titleCurrent":
			seen |= 1 << 14
			b, err := wire.ReadBool(dec)
			if err != nil {
				return wire.In("titleCurrent", err)
			}
			v.TitleCurrent = b
		case "titleGenerating":
			seen |= 1 << 15
			b, err := wire.ReadBool(dec)
			if err != nil {
				return wire.In("titleGenerating", err)
			}
			v.TitleGenerating = b
		case "draftRevision":
			seen |= 1 << 16
			n, err := wire.ReadUint(dec, 64)
			if err != nil {
				return wire.In("draftRevision", err)
			}
			v.DraftRevision = n
		default:
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("id")
	}
	if seen&(1<<1) == 0 {
		return wire.Required("title")
	}
	if seen&(1<<2) == 0 {
		return wire.Required("archived")
	}
	if seen&(1<<3) == 0 {
		return wire.Required("pinned")
	}
	if seen&(1<<4) == 0 {
		return wire.Required("readRevision")
	}
	if seen&(1<<5) == 0 {
		return wire.Required("target")
	}
	if seen&(1<<6) == 0 {
		return wire.Required("contextVersion")
	}
	if seen&(1<<7) == 0 {
		return wire.Required("model")
	}
	if seen&(1<<8) == 0 {
		return wire.Required("createdAt")
	}
	if seen&(1<<9) == 0 {
		return wire.Required("updatedAt")
	}
	if seen&(1<<10) == 0 {
		return wire.Required("cwd")
	}
	if seen&(1<<11) == 0 {
		return wire.Required("status")
	}
	if seen&(1<<12) == 0 {
		return wire.Required("revision")
	}
	if seen&(1<<13) == 0 {
		return wire.Required("unread")
	}
	if seen&(1<<14) == 0 {
		return wire.Required("titleCurrent")
	}
	if seen&(1<<15) == 0 {
		return wire.Required("titleGenerating")
	}
	if seen&(1<<16) == 0 {
		return wire.Required("draftRevision")
	}
	return nil
}

// validate checks the rules of the fields of ConversationSummary, and reports every one that
// is broken.
func (v ConversationSummary) validate() error {
	var r wire.Report
	r.Check("id", Validate(v.ID))
	r.Uint("readRevision", uint64(v.ReadRevision), wire.AtMost(9007199254740991))
	r.Nest("target", validateConversationTarget(v.Target))
	r.Uint("contextVersion", uint64(v.ContextVersion), wire.AtMost(9007199254740991))
	if v.Model != nil {
		r.Nest("model", (*v.Model).validate())
	}
	r.Check("createdAt", core.Validate(v.CreatedAt))
	r.Check("updatedAt", core.Validate(v.UpdatedAt))
	r.OneOf("status", string(v.Status), "running", "compacting", "interrupted", "error", "stopped", "completed", "idle")
	r.Uint("revision", uint64(v.Revision), wire.AtMost(9007199254740991))
	r.Uint("draftRevision", uint64(v.DraftRevision), wire.AtMost(9007199254740991))
	return r.Err()
}

// UnmarshalJSONFrom decodes the JSON object of ModelSettings: it refuses a member that
// the type does not have, a required member that is missing, a null, and a
// value of another JSON kind than the member's, naming the member.
func (v *ModelSettings) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = ModelSettings{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "providerId":
			seen |= 1 << 0
			if err := v.ProviderID.UnmarshalJSONFrom(dec); err != nil {
				return wire.In("providerId", err)
			}
		case "modelId":
			seen |= 1 << 1
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("modelId", err)
			}
			v.ModelID = s
		case "thinkingEffort":
			seen |= 1 << 2
			if wire.IsNull(dec) {
				if _, err := dec.ReadToken(); err != nil {
					return wire.In("thinkingEffort", err)
				}
			} else {
				var value string
				s, err := wire.ReadString(dec)
				if err != nil {
					return wire.In("thinkingEffort", err)
				}
				value = s
				v.ThinkingEffort = &value
			}
		case "serviceTierId":
			seen |= 1 << 3
			if wire.IsNull(dec) {
				if _, err := dec.ReadToken(); err != nil {
					return wire.In("serviceTierId", err)
				}
			} else {
				var value string
				s, err := wire.ReadString(dec)
				if err != nil {
					return wire.In("serviceTierId", err)
				}
				value = s
				v.ServiceTierID = &value
			}
		default:
			return wire.Unknown(name)
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("providerId")
	}
	if seen&(1<<1) == 0 {
		return wire.Required("modelId")
	}
	if seen&(1<<2) == 0 {
		return wire.Required("thinkingEffort")
	}
	if seen&(1<<3) == 0 {
		return wire.Required("serviceTierId")
	}
	return nil
}

// validate checks the rules of the fields of ModelSettings, and reports every one that
// is broken.
func (v ModelSettings) validate() error {
	var r wire.Report
	r.Check("providerId", Validate(v.ProviderID))
	r.Chars("modelId", v.ModelID, wire.AtLeast(1))
	return r.Err()
}

// UnmarshalJSONFrom decodes the JSON object of ConversationAnswer: it ignores a member that
// the type does not have, and refuses a required member that is missing, a
// null, and a value of another JSON kind than the member's, naming the member.
func (v *ConversationAnswer) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = ConversationAnswer{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "conversation":
			seen |= 1 << 0
			if err := v.Conversation.UnmarshalJSONFrom(dec); err != nil {
				return wire.In("conversation", err)
			}
		default:
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("conversation")
	}
	return nil
}

// validate checks the rules of the fields of ConversationAnswer, and reports every one that
// is broken.
func (v ConversationAnswer) validate() error {
	var r wire.Report
	r.Nest("conversation", v.Conversation.validate())
	return r.Err()
}

// UnmarshalJSONFrom decodes the JSON object of Conversations: it ignores a member that
// the type does not have, and refuses a required member that is missing, a
// null, and a value of another JSON kind than the member's, naming the member.
func (v *Conversations) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = Conversations{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "conversations":
			seen |= 1 << 0
			if err := wire.BeginArray(dec); err != nil {
				return wire.In("conversations", err)
			}
			items0 := []ConversationSummary{}
			for {
				more, err := wire.NextElement(dec)
				if err != nil {
					return wire.In("conversations", err)
				}
				if !more {
					break
				}
				var element0 ConversationSummary
				{
					if err := element0.UnmarshalJSONFrom(dec); err != nil {
						return wire.In("conversations", wire.In(wire.Index(len(items0)), err))
					}
				}
				items0 = append(items0, element0)
			}
			v.Conversations = items0
		default:
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("conversations")
	}
	return nil
}

// validate checks the rules of the fields of Conversations, and reports every one that
// is broken.
func (v Conversations) validate() error {
	var r wire.Report
	{
		var group0 wire.Report
		for i, e := range v.Conversations {
			group0.Nest(wire.Index(i), e.validate())
		}
		r.Nest("conversations", group0.Err())
	}
	return r.Err()
}

// UnmarshalJSONFrom decodes the JSON object of ReadRequest: it refuses a member that
// the type does not have, a required member that is missing, a null, and a
// value of another JSON kind than the member's, naming the member.
func (v *ReadRequest) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = ReadRequest{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "revision":
			seen |= 1 << 0
			n, err := wire.ReadUint(dec, 64)
			if err != nil {
				return wire.In("revision", err)
			}
			v.Revision = n
		default:
			return wire.Unknown(name)
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("revision")
	}
	return nil
}

// validate checks the rules of the fields of ReadRequest, and reports every one that
// is broken.
func (v ReadRequest) validate() error {
	var r wire.Report
	r.Uint("revision", uint64(v.Revision), wire.AtMost(9007199254740991))
	return r.Err()
}

// UnmarshalJSONFrom decodes the JSON object of Transcript: it ignores a member that
// the type does not have, and refuses a required member that is missing, a
// null, and a value of another JSON kind than the member's, naming the member.
func (v *Transcript) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = Transcript{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "blocks":
			seen |= 1 << 0
			if err := wire.BeginArray(dec); err != nil {
				return wire.In("blocks", err)
			}
			items0 := []core.Block{}
			for {
				more, err := wire.NextElement(dec)
				if err != nil {
					return wire.In("blocks", err)
				}
				if !more {
					break
				}
				var element0 core.Block
				{
					u, err := core.DecodeBlockJSONFrom(dec)
					if err != nil {
						return wire.In("blocks", wire.In(wire.Index(len(items0)), err))
					}
					element0 = u
				}
				items0 = append(items0, element0)
			}
			v.Blocks = items0
		case "failures":
			if wire.IsNull(dec) {
				return wire.In("failures", wire.Null())
			}
			var value map[string]core.ProviderFailureFacts
			if err := wire.BeginObject(dec); err != nil {
				return wire.In("failures", err)
			}
			entries0 := map[string]core.ProviderFailureFacts{}
			for {
				key0, more, err := wire.NextMember(dec)
				if err != nil {
					return wire.In("failures", err)
				}
				if !more {
					break
				}
				var element0 core.ProviderFailureFacts
				{
					if err := element0.UnmarshalJSONFrom(dec); err != nil {
						return wire.In("failures", wire.In(wire.Key(key0), err))
					}
				}
				entries0[key0] = element0
			}
			value = entries0
			v.Failures = &value
		case "subagents":
			seen |= 1 << 2
			if err := wire.BeginArray(dec); err != nil {
				return wire.In("subagents", err)
			}
			items0 := []SubagentHistory{}
			for {
				more, err := wire.NextElement(dec)
				if err != nil {
					return wire.In("subagents", err)
				}
				if !more {
					break
				}
				var element0 SubagentHistory
				{
					if err := element0.UnmarshalJSONFrom(dec); err != nil {
						return wire.In("subagents", wire.In(wire.Index(len(items0)), err))
					}
				}
				items0 = append(items0, element0)
			}
			v.Subagents = items0
		default:
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("blocks")
	}
	if seen&(1<<2) == 0 {
		return wire.Required("subagents")
	}
	return nil
}

// validate checks the rules of the fields of Transcript, and reports every one that
// is broken.
func (v Transcript) validate() error {
	var r wire.Report
	{
		var group0 wire.Report
		for i, e := range v.Blocks {
			var item0 wire.Report
			item0.Check("", core.Validate(e))
			group0.Nest(wire.Index(i), item0.Err())
		}
		r.Nest("blocks", group0.Err())
	}
	if v.Failures != nil {
		{
			var group0 wire.Report
			for _, k := range slices.Sorted(maps.Keys((*v.Failures))) {
				var key0 wire.Report
				key0.Chars("", k, wire.AtLeast(1))
				group0.Nest(wire.Key(k), key0.Err())
				e := (*v.Failures)[k]
				var item0 wire.Report
				item0.Check("", core.Validate(e))
				group0.Nest(wire.Key(k), item0.Err())
			}
			r.Nest("failures", group0.Err())
		}
	}
	{
		var group0 wire.Report
		for i, e := range v.Subagents {
			group0.Nest(wire.Index(i), e.validate())
		}
		r.Nest("subagents", group0.Err())
	}
	return r.Err()
}

// UnmarshalJSONFrom decodes the JSON object of SubagentHistory: it ignores a member that
// the type does not have, and refuses a required member that is missing, a
// null, and a value of another JSON kind than the member's, naming the member.
func (v *SubagentHistory) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = SubagentHistory{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "subagent":
			seen |= 1 << 0
			if err := v.Subagent.UnmarshalJSONFrom(dec); err != nil {
				return wire.In("subagent", err)
			}
		case "blocks":
			seen |= 1 << 1
			if err := wire.BeginArray(dec); err != nil {
				return wire.In("blocks", err)
			}
			items0 := []core.Block{}
			for {
				more, err := wire.NextElement(dec)
				if err != nil {
					return wire.In("blocks", err)
				}
				if !more {
					break
				}
				var element0 core.Block
				{
					u, err := core.DecodeBlockJSONFrom(dec)
					if err != nil {
						return wire.In("blocks", wire.In(wire.Index(len(items0)), err))
					}
					element0 = u
				}
				items0 = append(items0, element0)
			}
			v.Blocks = items0
		case "failures":
			if wire.IsNull(dec) {
				return wire.In("failures", wire.Null())
			}
			var value map[string]core.ProviderFailureFacts
			if err := wire.BeginObject(dec); err != nil {
				return wire.In("failures", err)
			}
			entries0 := map[string]core.ProviderFailureFacts{}
			for {
				key0, more, err := wire.NextMember(dec)
				if err != nil {
					return wire.In("failures", err)
				}
				if !more {
					break
				}
				var element0 core.ProviderFailureFacts
				{
					if err := element0.UnmarshalJSONFrom(dec); err != nil {
						return wire.In("failures", wire.In(wire.Key(key0), err))
					}
				}
				entries0[key0] = element0
			}
			value = entries0
			v.Failures = &value
		default:
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("subagent")
	}
	if seen&(1<<1) == 0 {
		return wire.Required("blocks")
	}
	return nil
}

// validate checks the rules of the fields of SubagentHistory, and reports every one that
// is broken.
func (v SubagentHistory) validate() error {
	var r wire.Report
	r.Check("subagent", agentproto.Validate(v.Subagent))
	{
		var group0 wire.Report
		for i, e := range v.Blocks {
			var item0 wire.Report
			item0.Check("", core.Validate(e))
			group0.Nest(wire.Index(i), item0.Err())
		}
		r.Nest("blocks", group0.Err())
	}
	if v.Failures != nil {
		{
			var group0 wire.Report
			for _, k := range slices.Sorted(maps.Keys((*v.Failures))) {
				var key0 wire.Report
				key0.Chars("", k, wire.AtLeast(1))
				group0.Nest(wire.Key(k), key0.Err())
				e := (*v.Failures)[k]
				var item0 wire.Report
				item0.Check("", core.Validate(e))
				group0.Nest(wire.Key(k), item0.Err())
			}
			r.Nest("failures", group0.Err())
		}
	}
	return r.Err()
}

// UnmarshalJSONFrom decodes the JSON object of ConversationPatch: it refuses a member that
// the type does not have, a required member that is missing, a null, and a
// value of another JSON kind than the member's, naming the member.
func (v *ConversationPatch) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = ConversationPatch{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "title":
			if wire.IsNull(dec) {
				return wire.In("title", wire.Null())
			}
			var value Trimmed
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("title", err)
			}
			value = NewTrimmed(s)
			v.Title = &value
		case "archived":
			if wire.IsNull(dec) {
				return wire.In("archived", wire.Null())
			}
			var value bool
			b, err := wire.ReadBool(dec)
			if err != nil {
				return wire.In("archived", err)
			}
			value = b
			v.Archived = &value
		case "pinned":
			if wire.IsNull(dec) {
				return wire.In("pinned", wire.Null())
			}
			var value bool
			b, err := wire.ReadBool(dec)
			if err != nil {
				return wire.In("pinned", err)
			}
			value = b
			v.Pinned = &value
		case "model":
			if wire.IsNull(dec) {
				return wire.In("model", wire.Null())
			}
			var value ModelChoice
			if err := value.UnmarshalJSONFrom(dec); err != nil {
				return wire.In("model", err)
			}
			v.Model = &value
		case "thinkingEffort":
			var value *string
			if dec.PeekKind() == 'n' {
				if _, err := dec.ReadToken(); err != nil {
					return wire.In("thinkingEffort", err)
				}
				value = nil
			} else {
				var pointed string
				s, err := wire.ReadString(dec)
				if err != nil {
					return wire.In("thinkingEffort", err)
				}
				pointed = s
				value = &pointed
			}
			v.ThinkingEffort = &value
		case "serviceTierId":
			var value *string
			if dec.PeekKind() == 'n' {
				if _, err := dec.ReadToken(); err != nil {
					return wire.In("serviceTierId", err)
				}
				value = nil
			} else {
				var pointed string
				s, err := wire.ReadString(dec)
				if err != nil {
					return wire.In("serviceTierId", err)
				}
				pointed = s
				value = &pointed
			}
			v.ServiceTierID = &value
		case "target":
			if wire.IsNull(dec) {
				return wire.In("target", wire.Null())
			}
			var value ConversationTarget
			u, err := decodeConversationTarget(dec)
			if err != nil {
				return wire.In("target", err)
			}
			value = u
			v.Target = &value
		default:
			return wire.Unknown(name)
		}
	}
	return nil
}

// validate checks the rules of the fields of ConversationPatch, and reports every one that
// is broken.
func (v ConversationPatch) validate() error {
	var r wire.Report
	if v.Title != nil {
		r.Chars("title", string((*v.Title)), wire.Between(1, 256))
		r.Check("title", Validate((*v.Title)))
	}
	if v.Model != nil {
		r.Nest("model", (*v.Model).validate())
	}
	if v.ThinkingEffort != nil {
		if (*v.ThinkingEffort) != nil {
			r.Chars("thinkingEffort", (*(*v.ThinkingEffort)), wire.AtLeast(1))
		}
	}
	if v.ServiceTierID != nil {
		if (*v.ServiceTierID) != nil {
			r.Chars("serviceTierId", (*(*v.ServiceTierID)), wire.AtLeast(1))
		}
	}
	if v.Target != nil {
		r.Nest("target", validateConversationTarget((*v.Target)))
	}
	return r.Err()
}

// UnmarshalJSONFrom decodes the JSON object of ModelChoice: it refuses a member that
// the type does not have, a required member that is missing, a null, and a
// value of another JSON kind than the member's, naming the member.
func (v *ModelChoice) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = ModelChoice{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "providerId":
			seen |= 1 << 0
			if err := v.ProviderID.UnmarshalJSONFrom(dec); err != nil {
				return wire.In("providerId", err)
			}
		case "modelId":
			seen |= 1 << 1
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("modelId", err)
			}
			v.ModelID = s
		default:
			return wire.Unknown(name)
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("providerId")
	}
	if seen&(1<<1) == 0 {
		return wire.Required("modelId")
	}
	return nil
}

// validate checks the rules of the fields of ModelChoice, and reports every one that
// is broken.
func (v ModelChoice) validate() error {
	var r wire.Report
	r.Check("providerId", Validate(v.ProviderID))
	r.Chars("modelId", v.ModelID, wire.AtLeast(1))
	return r.Err()
}

// decodeFieldResult decodes the JSON object of a FieldResult, whichever variant it is.
func decodeFieldResult(dec *jsontext.Decoder) (FieldResult, error) {
	raw, err := wire.ReadObject(dec)
	if err != nil {
		return nil, err
	}
	tag, err := wire.Tag(raw, "status")
	if err != nil {
		return nil, err
	}
	switch tag {
	case "applied":
		var v FieldResultApplied
		if err := v.UnmarshalJSONFrom(wire.NewDecoder(raw)); err != nil {
			return nil, err
		}
		return v, nil
	case "failed":
		var v FieldResultFailed
		if err := v.UnmarshalJSONFrom(wire.NewDecoder(raw)); err != nil {
			return nil, err
		}
		return v, nil
	}
	return nil, wire.UnknownTag("status", "applied", "failed")
}

// validateFieldResult checks the rules of the variant that v is.
func validateFieldResult(v FieldResult) error {
	switch v := v.(type) {
	case nil:
		return wire.Required("")
	case FieldResultApplied:
		return v.validate()
	case *FieldResultApplied:
		if v == nil {
			return fmt.Errorf("a nil %T is not a variant of FieldResult", v)
		}
		return v.validate()
	case FieldResultFailed:
		return v.validate()
	case *FieldResultFailed:
		if v == nil {
			return fmt.Errorf("a nil %T is not a variant of FieldResult", v)
		}
		return v.validate()
	}
	return fmt.Errorf("%T is not a variant of FieldResult", v)
}

// UnmarshalJSONFrom decodes the JSON object of FieldResultApplied: it ignores a member that
// the type does not have, and refuses a required member that is missing, a
// null, and a value of another JSON kind than the member's, naming the member.
func (v *FieldResultApplied) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = FieldResultApplied{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "status":
			seen |= 1 << 0
			tag, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("status", err)
			}
			if tag != "applied" {
				return wire.UnknownTag("status", "applied")
			}
		case "field":
			seen |= 1 << 1
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("field", err)
			}
			v.Field = PatchField(s)
		default:
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("status")
	}
	if seen&(1<<1) == 0 {
		return wire.Required("field")
	}
	return nil
}

// MarshalJSONTo encodes FieldResultApplied as a JSON object that starts with its tag.
func (v FieldResultApplied) MarshalJSONTo(enc *jsontext.Encoder) error {
	return json.MarshalEncode(enc, struct {
		Tag   string     `json:"status"`
		Field PatchField `json:"field"`
	}{"applied", v.Field})
}

// validate checks the rules of the fields of FieldResultApplied, and reports every one that
// is broken.
func (v FieldResultApplied) validate() error {
	var r wire.Report
	r.OneOf("field", string(v.Field), "title", "archived", "pinned", "model", "thinking_effort", "service_tier_id", "target")
	return r.Err()
}

// UnmarshalJSONFrom decodes the JSON object of FieldResultFailed: it ignores a member that
// the type does not have, and refuses a required member that is missing, a
// null, and a value of another JSON kind than the member's, naming the member.
func (v *FieldResultFailed) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = FieldResultFailed{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "status":
			seen |= 1 << 0
			tag, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("status", err)
			}
			if tag != "failed" {
				return wire.UnknownTag("status", "failed")
			}
		case "field":
			seen |= 1 << 1
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("field", err)
			}
			v.Field = PatchField(s)
		case "code":
			seen |= 1 << 2
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("code", err)
			}
			v.Code = ErrorCode(s)
		case "message":
			seen |= 1 << 3
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("message", err)
			}
			v.Message = s
		case "httpStatus":
			seen |= 1 << 4
			n, err := wire.ReadUint(dec, 16)
			if err != nil {
				return wire.In("httpStatus", err)
			}
			v.HTTPStatus = uint16(n)
		default:
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("status")
	}
	if seen&(1<<1) == 0 {
		return wire.Required("field")
	}
	if seen&(1<<2) == 0 {
		return wire.Required("code")
	}
	if seen&(1<<3) == 0 {
		return wire.Required("message")
	}
	if seen&(1<<4) == 0 {
		return wire.Required("httpStatus")
	}
	return nil
}

// MarshalJSONTo encodes FieldResultFailed as a JSON object that starts with its tag.
func (v FieldResultFailed) MarshalJSONTo(enc *jsontext.Encoder) error {
	return json.MarshalEncode(enc, struct {
		Tag        string     `json:"status"`
		Field      PatchField `json:"field"`
		Code       ErrorCode  `json:"code"`
		Message    string     `json:"message"`
		HTTPStatus uint16     `json:"httpStatus"`
	}{"failed", v.Field, v.Code, v.Message, v.HTTPStatus})
}

// validate checks the rules of the fields of FieldResultFailed, and reports every one that
// is broken.
func (v FieldResultFailed) validate() error {
	var r wire.Report
	r.OneOf("field", string(v.Field), "title", "archived", "pinned", "model", "thinking_effort", "service_tier_id", "target")
	r.OneOf("code", string(v.Code), "unauthenticated", "not_found", "invalid_body", "too_large", "internal_error", "backend_closing", "already_set_up", "invalid_credentials", "too_many_attempts", "email_taken", "invalid_code", "mail_unavailable", "mail_failed", "invalid_query", "forbidden", "provider_not_found", "model_not_found", "setting_unavailable", "model_not_selected", "provider_busy", "provider_exists", "unknown_provider_type", "unknown_vendor", "subscription_only", "accounts_unsupported", "no_login_flow", "login_not_found", "account_not_found", "active_account", "token_import_failed", "quota_requires_inference", "quota_unavailable", "catalog_unavailable", "rate_limited", "device_not_found", "device_in_use", "device_offline", "log_unreadable", "conversation_not_found", "conversation_archived", "conversation_busy", "host_not_attached", "host_stopped", "cloud_unavailable", "cloud_resetting", "cloud_capacity", "cloud_crash_loop", "fs_error", "file_changed", "is_directory", "file_exists", "protected_path", "transfer_stalled", "file_too_large", "not_text", "directory_too_large", "changes_timeout", "not_repository", "changes_failed", "host_operation_failed", "forbidden_origin", "unknown_stream", "upgrade_required", "stream_failed", "id_unavailable", "invalid_revision", "invalid_frame", "frame_delivery_failed", "turn_in_flight", "workspace_not_found", "workspace_in_use", "invalid_order", "user_not_found", "tab_not_found", "browser_failed", "expose_not_found", "expose_unavailable", "host_is_main", "name_taken", "target_conflict", "operation_failed", "fork_conflict", "invalid_fork_target", "no_messages", "upload_not_found", "draft_changed")
	return r.Err()
}

// UnmarshalJSONFrom decodes the JSON object of ConversationUpdate: it ignores a member that
// the type does not have, and refuses a required member that is missing, a
// null, and a value of another JSON kind than the member's, naming the member.
func (v *ConversationUpdate) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = ConversationUpdate{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "conversation":
			seen |= 1 << 0
			if err := v.Conversation.UnmarshalJSONFrom(dec); err != nil {
				return wire.In("conversation", err)
			}
		case "results":
			seen |= 1 << 1
			if err := wire.BeginArray(dec); err != nil {
				return wire.In("results", err)
			}
			items0 := []FieldResult{}
			for {
				more, err := wire.NextElement(dec)
				if err != nil {
					return wire.In("results", err)
				}
				if !more {
					break
				}
				var element0 FieldResult
				{
					u, err := decodeFieldResult(dec)
					if err != nil {
						return wire.In("results", wire.In(wire.Index(len(items0)), err))
					}
					element0 = u
				}
				items0 = append(items0, element0)
			}
			v.Results = items0
		default:
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("conversation")
	}
	if seen&(1<<1) == 0 {
		return wire.Required("results")
	}
	return nil
}

// validate checks the rules of the fields of ConversationUpdate, and reports every one that
// is broken.
func (v ConversationUpdate) validate() error {
	var r wire.Report
	r.Nest("conversation", v.Conversation.validate())
	{
		var group0 wire.Report
		for i, e := range v.Results {
			group0.Nest(wire.Index(i), validateFieldResult(e))
		}
		r.Nest("results", group0.Err())
	}
	return r.Err()
}

// UnmarshalJSONFrom decodes the JSON object of ConversationBatch: it refuses a member that
// the type does not have, a required member that is missing, a null, and a
// value of another JSON kind than the member's, naming the member.
func (v *ConversationBatch) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = ConversationBatch{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "items":
			seen |= 1 << 0
			if err := wire.BeginArray(dec); err != nil {
				return wire.In("items", err)
			}
			items0 := []BatchItem{}
			for {
				more, err := wire.NextElement(dec)
				if err != nil {
					return wire.In("items", err)
				}
				if !more {
					break
				}
				var element0 BatchItem
				{
					if err := element0.UnmarshalJSONFrom(dec); err != nil {
						return wire.In("items", wire.In(wire.Index(len(items0)), err))
					}
				}
				items0 = append(items0, element0)
			}
			v.Items = items0
		default:
			return wire.Unknown(name)
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("items")
	}
	return nil
}

// validate checks the rules of the fields of ConversationBatch, and reports every one that
// is broken.
func (v ConversationBatch) validate() error {
	var r wire.Report
	r.Items("items", len(v.Items), wire.Between(1, 100))
	{
		var group0 wire.Report
		for i, e := range v.Items {
			group0.Nest(wire.Index(i), e.validate())
		}
		r.Nest("items", group0.Err())
	}
	return r.Err()
}

// UnmarshalJSONFrom decodes the JSON object of BatchItem: it refuses a member that
// the type does not have, a required member that is missing, a null, and a
// value of another JSON kind than the member's, naming the member.
func (v *BatchItem) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = BatchItem{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "id":
			seen |= 1 << 0
			if err := v.ID.UnmarshalJSONFrom(dec); err != nil {
				return wire.In("id", err)
			}
		case "patch":
			seen |= 1 << 1
			if err := v.Patch.UnmarshalJSONFrom(dec); err != nil {
				return wire.In("patch", err)
			}
		default:
			return wire.Unknown(name)
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("id")
	}
	if seen&(1<<1) == 0 {
		return wire.Required("patch")
	}
	return nil
}

// validate checks the rules of the fields of BatchItem, and reports every one that
// is broken.
func (v BatchItem) validate() error {
	var r wire.Report
	r.Check("id", Validate(v.ID))
	r.Nest("patch", v.Patch.validate())
	return r.Err()
}

// UnmarshalJSONFrom decodes the JSON object of BatchAnswer: it ignores a member that
// the type does not have, and refuses a required member that is missing, a
// null, and a value of another JSON kind than the member's, naming the member.
func (v *BatchAnswer) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = BatchAnswer{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "results":
			seen |= 1 << 0
			if err := wire.BeginArray(dec); err != nil {
				return wire.In("results", err)
			}
			items0 := []BatchResult{}
			for {
				more, err := wire.NextElement(dec)
				if err != nil {
					return wire.In("results", err)
				}
				if !more {
					break
				}
				var element0 BatchResult
				{
					u, err := decodeBatchResult(dec)
					if err != nil {
						return wire.In("results", wire.In(wire.Index(len(items0)), err))
					}
					element0 = u
				}
				items0 = append(items0, element0)
			}
			v.Results = items0
		default:
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("results")
	}
	return nil
}

// validate checks the rules of the fields of BatchAnswer, and reports every one that
// is broken.
func (v BatchAnswer) validate() error {
	var r wire.Report
	{
		var group0 wire.Report
		for i, e := range v.Results {
			group0.Nest(wire.Index(i), validateBatchResult(e))
		}
		r.Nest("results", group0.Err())
	}
	return r.Err()
}

// decodeBatchResult decodes the JSON object of a BatchResult, whichever variant it is.
func decodeBatchResult(dec *jsontext.Decoder) (BatchResult, error) {
	raw, err := wire.ReadObject(dec)
	if err != nil {
		return nil, err
	}
	tag, err := wire.Tag(raw, "status")
	if err != nil {
		return nil, err
	}
	switch tag {
	case "updated":
		var v BatchResultUpdated
		if err := v.UnmarshalJSONFrom(wire.NewDecoder(raw)); err != nil {
			return nil, err
		}
		return v, nil
	case "refused":
		var v BatchResultRefused
		if err := v.UnmarshalJSONFrom(wire.NewDecoder(raw)); err != nil {
			return nil, err
		}
		return v, nil
	}
	return nil, wire.UnknownTag("status", "updated", "refused")
}

// validateBatchResult checks the rules of the variant that v is.
func validateBatchResult(v BatchResult) error {
	switch v := v.(type) {
	case nil:
		return wire.Required("")
	case BatchResultUpdated:
		return v.validate()
	case *BatchResultUpdated:
		if v == nil {
			return fmt.Errorf("a nil %T is not a variant of BatchResult", v)
		}
		return v.validate()
	case BatchResultRefused:
		return v.validate()
	case *BatchResultRefused:
		if v == nil {
			return fmt.Errorf("a nil %T is not a variant of BatchResult", v)
		}
		return v.validate()
	}
	return fmt.Errorf("%T is not a variant of BatchResult", v)
}

// UnmarshalJSONFrom decodes the JSON object of BatchResultUpdated: it ignores a member that
// the type does not have, and refuses a required member that is missing, a
// null, and a value of another JSON kind than the member's, naming the member.
func (v *BatchResultUpdated) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = BatchResultUpdated{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "status":
			seen |= 1 << 0
			tag, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("status", err)
			}
			if tag != "updated" {
				return wire.UnknownTag("status", "updated")
			}
		case "id":
			seen |= 1 << 1
			if err := v.ID.UnmarshalJSONFrom(dec); err != nil {
				return wire.In("id", err)
			}
		case "conversation":
			seen |= 1 << 2
			if err := v.Conversation.UnmarshalJSONFrom(dec); err != nil {
				return wire.In("conversation", err)
			}
		case "results":
			seen |= 1 << 3
			if err := wire.BeginArray(dec); err != nil {
				return wire.In("results", err)
			}
			items0 := []FieldResult{}
			for {
				more, err := wire.NextElement(dec)
				if err != nil {
					return wire.In("results", err)
				}
				if !more {
					break
				}
				var element0 FieldResult
				{
					u, err := decodeFieldResult(dec)
					if err != nil {
						return wire.In("results", wire.In(wire.Index(len(items0)), err))
					}
					element0 = u
				}
				items0 = append(items0, element0)
			}
			v.Results = items0
		default:
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("status")
	}
	if seen&(1<<1) == 0 {
		return wire.Required("id")
	}
	if seen&(1<<2) == 0 {
		return wire.Required("conversation")
	}
	if seen&(1<<3) == 0 {
		return wire.Required("results")
	}
	return nil
}

// MarshalJSONTo encodes BatchResultUpdated as a JSON object that starts with its tag.
func (v BatchResultUpdated) MarshalJSONTo(enc *jsontext.Encoder) error {
	return json.MarshalEncode(enc, struct {
		Tag          string              `json:"status"`
		ID           ConversationID      `json:"id"`
		Conversation ConversationSummary `json:"conversation"`
		Results      []FieldResult       `json:"results"`
	}{"updated", v.ID, v.Conversation, v.Results})
}

// validate checks the rules of the fields of BatchResultUpdated, and reports every one that
// is broken.
func (v BatchResultUpdated) validate() error {
	var r wire.Report
	r.Check("id", Validate(v.ID))
	r.Nest("conversation", v.Conversation.validate())
	{
		var group0 wire.Report
		for i, e := range v.Results {
			group0.Nest(wire.Index(i), validateFieldResult(e))
		}
		r.Nest("results", group0.Err())
	}
	return r.Err()
}

// UnmarshalJSONFrom decodes the JSON object of BatchResultRefused: it ignores a member that
// the type does not have, and refuses a required member that is missing, a
// null, and a value of another JSON kind than the member's, naming the member.
func (v *BatchResultRefused) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = BatchResultRefused{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "status":
			seen |= 1 << 0
			tag, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("status", err)
			}
			if tag != "refused" {
				return wire.UnknownTag("status", "refused")
			}
		case "id":
			seen |= 1 << 1
			if err := v.ID.UnmarshalJSONFrom(dec); err != nil {
				return wire.In("id", err)
			}
		case "code":
			seen |= 1 << 2
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("code", err)
			}
			v.Code = ErrorCode(s)
		case "message":
			seen |= 1 << 3
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("message", err)
			}
			v.Message = s
		default:
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("status")
	}
	if seen&(1<<1) == 0 {
		return wire.Required("id")
	}
	if seen&(1<<2) == 0 {
		return wire.Required("code")
	}
	if seen&(1<<3) == 0 {
		return wire.Required("message")
	}
	return nil
}

// MarshalJSONTo encodes BatchResultRefused as a JSON object that starts with its tag.
func (v BatchResultRefused) MarshalJSONTo(enc *jsontext.Encoder) error {
	return json.MarshalEncode(enc, struct {
		Tag     string         `json:"status"`
		ID      ConversationID `json:"id"`
		Code    ErrorCode      `json:"code"`
		Message string         `json:"message"`
	}{"refused", v.ID, v.Code, v.Message})
}

// validate checks the rules of the fields of BatchResultRefused, and reports every one that
// is broken.
func (v BatchResultRefused) validate() error {
	var r wire.Report
	r.Check("id", Validate(v.ID))
	r.OneOf("code", string(v.Code), "unauthenticated", "not_found", "invalid_body", "too_large", "internal_error", "backend_closing", "already_set_up", "invalid_credentials", "too_many_attempts", "email_taken", "invalid_code", "mail_unavailable", "mail_failed", "invalid_query", "forbidden", "provider_not_found", "model_not_found", "setting_unavailable", "model_not_selected", "provider_busy", "provider_exists", "unknown_provider_type", "unknown_vendor", "subscription_only", "accounts_unsupported", "no_login_flow", "login_not_found", "account_not_found", "active_account", "token_import_failed", "quota_requires_inference", "quota_unavailable", "catalog_unavailable", "rate_limited", "device_not_found", "device_in_use", "device_offline", "log_unreadable", "conversation_not_found", "conversation_archived", "conversation_busy", "host_not_attached", "host_stopped", "cloud_unavailable", "cloud_resetting", "cloud_capacity", "cloud_crash_loop", "fs_error", "file_changed", "is_directory", "file_exists", "protected_path", "transfer_stalled", "file_too_large", "not_text", "directory_too_large", "changes_timeout", "not_repository", "changes_failed", "host_operation_failed", "forbidden_origin", "unknown_stream", "upgrade_required", "stream_failed", "id_unavailable", "invalid_revision", "invalid_frame", "frame_delivery_failed", "turn_in_flight", "workspace_not_found", "workspace_in_use", "invalid_order", "user_not_found", "tab_not_found", "browser_failed", "expose_not_found", "expose_unavailable", "host_is_main", "name_taken", "target_conflict", "operation_failed", "fork_conflict", "invalid_fork_target", "no_messages", "upload_not_found", "draft_changed")
	return r.Err()
}

// UnmarshalJSONFrom decodes the JSON object of ForkRequest: it refuses a member that
// the type does not have, a required member that is missing, a null, and a
// value of another JSON kind than the member's, naming the member.
func (v *ForkRequest) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = ForkRequest{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "id":
			seen |= 1 << 0
			if err := v.ID.UnmarshalJSONFrom(dec); err != nil {
				return wire.In("id", err)
			}
		case "blockId":
			seen |= 1 << 1
			if err := v.BlockID.UnmarshalJSONFrom(dec); err != nil {
				return wire.In("blockId", err)
			}
		default:
			return wire.Unknown(name)
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("id")
	}
	if seen&(1<<1) == 0 {
		return wire.Required("blockId")
	}
	return nil
}

// validate checks the rules of the fields of ForkRequest, and reports every one that
// is broken.
func (v ForkRequest) validate() error {
	var r wire.Report
	r.Check("id", Validate(v.ID))
	r.Check("blockId", core.Validate(v.BlockID))
	return r.Err()
}

// UnmarshalJSONFrom decodes the JSON object of ForkAnswer: it ignores a member that
// the type does not have, and refuses a required member that is missing, a
// null, and a value of another JSON kind than the member's, naming the member.
func (v *ForkAnswer) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = ForkAnswer{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "conversation":
			seen |= 1 << 0
			if err := v.Conversation.UnmarshalJSONFrom(dec); err != nil {
				return wire.In("conversation", err)
			}
		default:
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("conversation")
	}
	return nil
}

// validate checks the rules of the fields of ForkAnswer, and reports every one that
// is broken.
func (v ForkAnswer) validate() error {
	var r wire.Report
	r.Nest("conversation", v.Conversation.validate())
	return r.Err()
}
