// Code generated by wiregen; DO NOT EDIT.

package webapi

import (
	"encoding/json/jsontext"

	"github.com/wspl/demi/go/core"
	"github.com/wspl/demi/go/internal/wire"
)

// UnmarshalJSONFrom decodes the JSON object of AttachedHost: it ignores a member that
// the type does not have, and refuses a required member that is missing, a
// null, and a value of another JSON kind than the member's, naming the member.
func (v *AttachedHost) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = AttachedHost{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "deviceId":
			seen |= 1 << 0
			if err := v.DeviceID.UnmarshalJSONFrom(dec); err != nil {
				return wire.In("deviceId", err)
			}
		case "name":
			seen |= 1 << 1
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("name", err)
			}
			v.Name = s
		case "cwd":
			seen |= 1 << 2
			if wire.IsNull(dec) {
				if _, err := dec.ReadToken(); err != nil {
					return wire.In("cwd", err)
				}
			} else {
				var value string
				s, err := wire.ReadString(dec)
				if err != nil {
					return wire.In("cwd", err)
				}
				value = s
				v.Cwd = &value
			}
		case "online":
			seen |= 1 << 3
			b, err := wire.ReadBool(dec)
			if err != nil {
				return wire.In("online", err)
			}
			v.Online = b
		case "attachedAt":
			seen |= 1 << 4
			if err := v.AttachedAt.UnmarshalJSONFrom(dec); err != nil {
				return wire.In("attachedAt", err)
			}
		default:
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("deviceId")
	}
	if seen&(1<<1) == 0 {
		return wire.Required("name")
	}
	if seen&(1<<2) == 0 {
		return wire.Required("cwd")
	}
	if seen&(1<<3) == 0 {
		return wire.Required("online")
	}
	if seen&(1<<4) == 0 {
		return wire.Required("attachedAt")
	}
	return nil
}

// validate checks the rules of the fields of AttachedHost, and reports every one that
// is broken.
func (v AttachedHost) validate() error {
	var r wire.Report
	r.Check("deviceId", Validate(v.DeviceID))
	r.Check("attachedAt", core.Validate(v.AttachedAt))
	return r.Err()
}

// UnmarshalJSONFrom decodes the JSON object of AttachedHosts: it ignores a member that
// the type does not have, and refuses a required member that is missing, a
// null, and a value of another JSON kind than the member's, naming the member.
func (v *AttachedHosts) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = AttachedHosts{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "hosts":
			seen |= 1 << 0
			if err := wire.BeginArray(dec); err != nil {
				return wire.In("hosts", err)
			}
			items0 := []AttachedHost{}
			for {
				more, err := wire.NextElement(dec)
				if err != nil {
					return wire.In("hosts", err)
				}
				if !more {
					break
				}
				var element0 AttachedHost
				{
					if err := element0.UnmarshalJSONFrom(dec); err != nil {
						return wire.In("hosts", wire.In(wire.Index(len(items0)), err))
					}
				}
				items0 = append(items0, element0)
			}
			v.Hosts = items0
		default:
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("hosts")
	}
	return nil
}

// validate checks the rules of the fields of AttachedHosts, and reports every one that
// is broken.
func (v AttachedHosts) validate() error {
	var r wire.Report
	{
		var group0 wire.Report
		for i, e := range v.Hosts {
			group0.Nest(wire.Index(i), e.validate())
		}
		r.Nest("hosts", group0.Err())
	}
	return r.Err()
}

// UnmarshalJSONFrom decodes the JSON object of AttachHost: it refuses a member that
// the type does not have, a required member that is missing, a null, and a
// value of another JSON kind than the member's, naming the member.
func (v *AttachHost) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = AttachHost{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "deviceId":
			seen |= 1 << 0
			if err := v.DeviceID.UnmarshalJSONFrom(dec); err != nil {
				return wire.In("deviceId", err)
			}
		default:
			return wire.Unknown(name)
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("deviceId")
	}
	return nil
}

// validate checks the rules of the fields of AttachHost, and reports every one that
// is broken.
func (v AttachHost) validate() error {
	var r wire.Report
	r.Check("deviceId", Validate(v.DeviceID))
	return r.Err()
}

// UnmarshalJSONFrom decodes the JSON object of RenameHost: it refuses a member that
// the type does not have, a required member that is missing, a null, and a
// value of another JSON kind than the member's, naming the member.
func (v *RenameHost) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = RenameHost{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "name":
			seen |= 1 << 0
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("name", err)
			}
			v.Name = NewTrimmed(s)
		default:
			return wire.Unknown(name)
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("name")
	}
	return nil
}

// validate checks the rules of the fields of RenameHost, and reports every one that
// is broken.
func (v RenameHost) validate() error {
	var r wire.Report
	r.Chars("name", string(v.Name), wire.Between(1, 64))
	r.Check("name", Validate(v.Name))
	return r.Err()
}
