// Code generated by wiregen; DO NOT EDIT.

package featuretest

import (
	"encoding/json/jsontext"
	"encoding/json/v2"

	"github.com/wspl/demi/go/internal/wire"
)

// ValidateEnvelope checks a Envelope using its owner's rules.
func ValidateEnvelope(value Envelope) error {
	return value.validate()
}

// DecodeEnvelopeJSON reads and validates one complete JSON value.
func DecodeEnvelopeJSON(data []byte) (Envelope, error) {
	var value Envelope
	err := json.Unmarshal(data, &value)
	if err != nil {
		return value, wire.Refusal(err)
	}
	return value, ValidateEnvelope(value)
}

// EncodeEnvelopeJSON validates and encodes a Envelope.
func EncodeEnvelopeJSON(value Envelope) ([]byte, error) {
	if err := ValidateEnvelope(value); err != nil {
		return nil, err
	}
	data, err := json.Marshal(value, json.Deterministic(true))
	if err != nil {
		return nil, wire.Refusal(err)
	}
	return data, nil
}

// ValidateEvent checks a Event using its owner's rules.
func ValidateEvent(value Event) error {
	return validateEvent(value)
}

// DecodeEventJSON reads and validates one complete JSON value.
func DecodeEventJSON(data []byte) (Event, error) {
	var value Event
	err := json.Unmarshal(data, &value, json.WithUnmarshalers(json.UnmarshalFromFunc(func(dec *jsontext.Decoder, v *Event) error {
		decoded, err := DecodeEventJSONFrom(dec)
		if err == nil {
			*v = decoded
		}
		return err
	})))
	if err != nil {
		return value, wire.Refusal(err)
	}
	return value, ValidateEvent(value)
}

// EncodeEventJSON validates and encodes a Event.
func EncodeEventJSON(value Event) ([]byte, error) {
	if err := ValidateEvent(value); err != nil {
		return nil, err
	}
	data, err := json.Marshal(value, json.Deterministic(true))
	if err != nil {
		return nil, wire.Refusal(err)
	}
	return data, nil
}

// ValidateForeign checks a Foreign using its owner's rules.
func ValidateForeign(value Foreign) error {
	return value.validate()
}

// DecodeForeignJSON reads and validates one complete JSON value.
func DecodeForeignJSON(data []byte) (Foreign, error) {
	var value Foreign
	err := json.Unmarshal(data, &value)
	if err != nil {
		return value, wire.Refusal(err)
	}
	return value, ValidateForeign(value)
}

// EncodeForeignJSON validates and encodes a Foreign.
func EncodeForeignJSON(value Foreign) ([]byte, error) {
	if err := ValidateForeign(value); err != nil {
		return nil, err
	}
	data, err := json.Marshal(value, json.Deterministic(true))
	if err != nil {
		return nil, wire.Refusal(err)
	}
	return data, nil
}

// ValidatePatch checks a Patch using its owner's rules.
func ValidatePatch(value Patch) error {
	return value.validate()
}

// DecodePatchJSON reads and validates one complete JSON value.
func DecodePatchJSON(data []byte) (Patch, error) {
	var value Patch
	err := json.Unmarshal(data, &value)
	if err != nil {
		return value, wire.Refusal(err)
	}
	return value, ValidatePatch(value)
}

// EncodePatchJSON validates and encodes a Patch.
func EncodePatchJSON(value Patch) ([]byte, error) {
	if err := ValidatePatch(value); err != nil {
		return nil, err
	}
	data, err := json.Marshal(value, json.Deterministic(true))
	if err != nil {
		return nil, wire.Refusal(err)
	}
	return data, nil
}

// ValidateReasoning checks a Reasoning using its owner's rules.
func ValidateReasoning(value Reasoning) error {
	return value.validate()
}

// DecodeReasoningJSON reads and validates one complete JSON value.
func DecodeReasoningJSON(data []byte) (Reasoning, error) {
	var value Reasoning
	err := json.Unmarshal(data, &value)
	if err != nil {
		return value, wire.Refusal(err)
	}
	return value, ValidateReasoning(value)
}

// EncodeReasoningJSON validates and encodes a Reasoning.
func EncodeReasoningJSON(value Reasoning) ([]byte, error) {
	if err := ValidateReasoning(value); err != nil {
		return nil, err
	}
	data, err := json.Marshal(value, json.Deterministic(true))
	if err != nil {
		return nil, wire.Refusal(err)
	}
	return data, nil
}

// ValidateReplay checks a Replay using its owner's rules.
func ValidateReplay(value Replay) error {
	return validateReplay(value)
}

// DecodeReplayJSON reads and validates one complete JSON value.
func DecodeReplayJSON(data []byte) (Replay, error) {
	var value Replay
	err := json.Unmarshal(data, &value, json.WithUnmarshalers(json.UnmarshalFromFunc(func(dec *jsontext.Decoder, v *Replay) error {
		decoded, err := DecodeReplayJSONFrom(dec)
		if err == nil {
			*v = decoded
		}
		return err
	})))
	if err != nil {
		return value, wire.Refusal(err)
	}
	return value, ValidateReplay(value)
}

// EncodeReplayJSON validates and encodes a Replay.
func EncodeReplayJSON(value Replay) ([]byte, error) {
	if err := ValidateReplay(value); err != nil {
		return nil, err
	}
	data, err := json.Marshal(value, json.Deterministic(true))
	if err != nil {
		return nil, wire.Refusal(err)
	}
	return data, nil
}

// ValidateSyntaxEnvelope checks a SyntaxEnvelope using its owner's rules.
func ValidateSyntaxEnvelope(value SyntaxEnvelope) error {
	return value.validate()
}

// DecodeSyntaxEnvelopeJSON reads and validates one complete JSON value.
func DecodeSyntaxEnvelopeJSON(data []byte) (SyntaxEnvelope, error) {
	var value SyntaxEnvelope
	err := json.Unmarshal(data, &value)
	if err != nil {
		return value, wire.Refusal(err)
	}
	return value, ValidateSyntaxEnvelope(value)
}

// EncodeSyntaxEnvelopeJSON validates and encodes a SyntaxEnvelope.
func EncodeSyntaxEnvelopeJSON(value SyntaxEnvelope) ([]byte, error) {
	if err := ValidateSyntaxEnvelope(value); err != nil {
		return nil, err
	}
	data, err := json.Marshal(value, json.Deterministic(true))
	if err != nil {
		return nil, wire.Refusal(err)
	}
	return data, nil
}

// ValidateTimed checks a Timed using its owner's rules.
func ValidateTimed(value Timed) error {
	return value.validate()
}

// DecodeTimedJSON reads and validates one complete JSON value.
func DecodeTimedJSON(data []byte) (Timed, error) {
	var value Timed
	err := json.Unmarshal(data, &value)
	if err != nil {
		return value, wire.Refusal(err)
	}
	return value, ValidateTimed(value)
}

// EncodeTimedJSON validates and encodes a Timed.
func EncodeTimedJSON(value Timed) ([]byte, error) {
	if err := ValidateTimed(value); err != nil {
		return nil, err
	}
	data, err := json.Marshal(value, json.Deterministic(true))
	if err != nil {
		return nil, wire.Refusal(err)
	}
	return data, nil
}
