// Code generated by wiregen; DO NOT EDIT.

package featuretest

import (
	"encoding/json/jsontext"
	"encoding/json/v2"
	"maps"
	"slices"
	"unicode/utf8"

	"github.com/tinylib/msgp/msgp"
	"github.com/wspl/demi/go/internal/wire"
	exporttest "github.com/wspl/demi/go/internal/wiregen/exporttest"
)

// UnmarshalMsgpack reads the structure of one complete Patch value.
func (v *Patch) UnmarshalMsgpack(data []byte) error {
	*v = Patch{}
	fields, err := wire.MPObject(data)
	if err != nil {
		return err
	}
	seen := map[string]bool{}
	for _, field := range fields {
		switch field.Name {
		case "usage":
			seen[field.Name] = true
			if msgp.IsNil(field.Data) {
				continue
			}
			value, err := (func(data []byte) (Usage, error) {
				var v Usage
				err := v.UnmarshalMsgpack(data)
				return v, err
			})(field.Data)
			if err != nil {
				return wire.In(field.Name, err)
			}
			v.Usage = &value
		case "setting":
			seen[field.Name] = true
			value, err := (func(data []byte) (*string, error) {
				return wire.MPNullable(data, func(data []byte) (string, error) {
					value, err := wire.MPString(data)
					return string(value), err
				})
			})(field.Data)
			if err != nil {
				return wire.In(field.Name, err)
			}
			v.Setting = &value
		case "forkable":
			seen[field.Name] = true
			value, err := (func(data []byte) (bool, error) {
				value, err := wire.MPRead(data, msgp.ReadBoolBytes)
				return bool(value), err
			})(field.Data)
			if err != nil {
				return wire.In(field.Name, err)
			}
			v.Forkable = value
		default:
			return wire.Unknown(field.Name)
		}
	}
	return nil
}

// DecodePatchMsgpack reads and validates one complete value.
func DecodePatchMsgpack(data []byte) (Patch, error) {
	var value Patch
	if err := value.UnmarshalMsgpack(data); err != nil {
		return value, err
	}
	return value, value.validate()
}

// MarshalMsgpack encodes Patch as a map in declaration order.
func (v Patch) MarshalMsgpack() ([]byte, error) {
	if err := v.validate(); err != nil {
		return nil, err
	}
	count := uint32(3)
	if v.Usage == nil {
		count--
	}
	if v.Setting == nil {
		count--
	}
	if !v.Forkable {
		count--
	}
	data := msgp.AppendMapHeader(nil, count)
	if v.Usage != nil {
		data = msgp.AppendString(data, "usage")
		{
			if v.Usage == nil {
				data = msgp.AppendNil(data)
			} else {
				encoded, err := (*v.Usage).MarshalMsgpack()
				if err != nil {
					return nil, wire.In("usage", err)
				}
				data = append(data, encoded...)
			}
		}
	}
	if v.Setting != nil {
		data = msgp.AppendString(data, "setting")
		{
			if v.Setting == nil {
				data = msgp.AppendNil(data)
			} else {
				if (*v.Setting) == nil {
					data = msgp.AppendNil(data)
				} else {
					if !utf8.ValidString(string((*(*v.Setting)))) {
						return nil, &wire.InvalidError{Path: "setting", Rule: "invalid UTF-8"}
					}
					data = msgp.AppendString(data, string((*(*v.Setting))))
				}
			}
		}
	}
	if v.Forkable {
		data = msgp.AppendString(data, "forkable")
		{
			data = msgp.AppendBool(data, bool(v.Forkable))
		}
	}
	return data, nil
}

// UnmarshalMsgpack reads the structure of one complete Usage value.
func (v *Usage) UnmarshalMsgpack(data []byte) error {
	*v = Usage{}
	fields, err := wire.MPObject(data)
	if err != nil {
		return err
	}
	seen := map[string]bool{}
	for _, field := range fields {
		switch field.Name {
		case "tokens":
			seen[field.Name] = true
			value, err := (func(data []byte) (uint64, error) {
				value, err := wire.MPRead(data, msgp.ReadUint64Bytes)
				return uint64(value), err
			})(field.Data)
			if err != nil {
				return wire.In(field.Name, err)
			}
			v.Tokens = value
		default:
			return wire.Unknown(field.Name)
		}
	}
	if !seen["tokens"] {
		return wire.Required("tokens")
	}
	return nil
}

// DecodeUsageMsgpack reads and validates one complete value.
func DecodeUsageMsgpack(data []byte) (Usage, error) {
	var value Usage
	if err := value.UnmarshalMsgpack(data); err != nil {
		return value, err
	}
	return value, value.validate()
}

// MarshalMsgpack encodes Usage as a map in declaration order.
func (v Usage) MarshalMsgpack() ([]byte, error) {
	if err := v.validate(); err != nil {
		return nil, err
	}
	count := uint32(1)
	data := msgp.AppendMapHeader(nil, count)
	data = msgp.AppendString(data, "tokens")
	{
		data = msgp.AppendUint64(data, uint64(v.Tokens))
	}
	return data, nil
}

// UnmarshalMsgpack reads the structure of one complete Reasoning value.
func (v *Reasoning) UnmarshalMsgpack(data []byte) error {
	*v = Reasoning{}
	fields, err := wire.MPObject(data)
	if err != nil {
		return err
	}
	seen := map[string]bool{}
	for _, field := range fields {
		switch field.Name {
		case "id":
			seen[field.Name] = true
			value, err := (func(data []byte) (string, error) {
				value, err := wire.MPString(data)
				return string(value), err
			})(field.Data)
			if err != nil {
				return wire.In(field.Name, err)
			}
			v.ID = value
		case "hidden":
			seen[field.Name] = true
			value, err := (func(data []byte) (bool, error) {
				value, err := wire.MPRead(data, msgp.ReadBoolBytes)
				return bool(value), err
			})(field.Data)
			if err != nil {
				return wire.In(field.Name, err)
			}
			v.Hidden = value
		default:
			raw, err := wire.MPJSON(field.Data)
			if err != nil {
				return wire.In(field.Name, err)
			}
			v.Extra = append(v.Extra, wire.Member{Name: field.Name, Value: raw})
		}
	}
	if !seen["id"] {
		return wire.Required("id")
	}
	return nil
}

// DecodeReasoningMsgpack reads and validates one complete value.
func DecodeReasoningMsgpack(data []byte) (Reasoning, error) {
	var value Reasoning
	if err := value.UnmarshalMsgpack(data); err != nil {
		return value, err
	}
	return value, value.validate()
}

// MarshalMsgpack encodes Reasoning as a map in declaration order.
func (v Reasoning) MarshalMsgpack() ([]byte, error) {
	if err := v.validate(); err != nil {
		return nil, err
	}
	count := uint32(2)
	count += uint32(len(v.Extra))
	if !v.Hidden {
		count--
	}
	data := msgp.AppendMapHeader(nil, count)
	data = msgp.AppendString(data, "id")
	{
		if !utf8.ValidString(string(v.ID)) {
			return nil, &wire.InvalidError{Path: "id", Rule: "invalid UTF-8"}
		}
		data = msgp.AppendString(data, string(v.ID))
	}
	if v.Hidden {
		data = msgp.AppendString(data, "hidden")
		{
			data = msgp.AppendBool(data, bool(v.Hidden))
		}
	}
	for _, member := range v.Extra {
		data = msgp.AppendString(data, member.Name)
		raw, err := wire.JSONMsgpack(member.Value)
		if err != nil {
			return nil, wire.In(member.Name, err)
		}
		data = append(data, raw...)
	}
	return data, nil
}

// DecodeEventJSONFrom reads the union using its owner's JSON codec.
func DecodeEventJSONFrom(dec *jsontext.Decoder) (Event, error) { return decodeEvent(dec) }

// DecodeEventMsgpack decodes and checks one variant of Event.
func DecodeEventMsgpack(data []byte) (Event, error) {
	value, err := decodeEventMsgpack(data)
	if err != nil {
		return nil, err
	}
	return value, validateEvent(value)
}
func decodeEventMsgpack(data []byte) (Event, error) {
	fields, err := wire.MPObject(data)
	if err != nil {
		return nil, err
	}
	var tag string
	found := false
	for _, field := range fields {
		if field.Name == "type" {
			tag, err = wire.MPString(field.Data)
			if err != nil {
				return nil, wire.In("type", err)
			}
			found = true
		}
	}
	if !found {
		return nil, wire.Required("type")
	}
	switch tag {
	case "changed":
		var value Changed
		if err := value.UnmarshalMsgpack(data); err != nil {
			return nil, err
		}
		return value, nil
	}
	return nil, wire.UnknownTag("type", "changed")
}

// EncodeEventMsgpack checks and encodes the selected variant.
func EncodeEventMsgpack(value Event) ([]byte, error) {
	if err := validateEvent(value); err != nil {
		return nil, err
	}
	switch value := value.(type) {
	case Changed:
		return value.MarshalMsgpack()
	case *Changed:
		return value.MarshalMsgpack()
	}
	return nil, wire.NoVariant("Changed")
}

// UnmarshalMsgpack reads the structure of one complete Changed value.
func (v *Changed) UnmarshalMsgpack(data []byte) error {
	*v = Changed{}
	fields, err := wire.MPObject(data)
	if err != nil {
		return err
	}
	seen := map[string]bool{}
	tagSeen := false
	for _, field := range fields {
		switch field.Name {
		case "type":
			tagSeen = true
			tag, err := wire.MPString(field.Data)
			if err != nil {
				return wire.In("type", err)
			}
			if tag != "changed" {
				return wire.UnknownTag("type", "changed")
			}
		case "low":
			seen[field.Name] = true
			value, err := (func(data []byte) (int64, error) {
				value, err := wire.MPRead(data, msgp.ReadInt64Bytes)
				return int64(value), err
			})(field.Data)
			if err != nil {
				return wire.In(field.Name, err)
			}
			v.Low = value
		case "high":
			seen[field.Name] = true
			value, err := (func(data []byte) (int64, error) {
				value, err := wire.MPRead(data, msgp.ReadInt64Bytes)
				return int64(value), err
			})(field.Data)
			if err != nil {
				return wire.In(field.Name, err)
			}
			v.High = value
		default:
			return wire.Unknown(field.Name)
		}
	}
	if !tagSeen {
		return wire.Required("type")
	}
	if !seen["low"] {
		return wire.Required("low")
	}
	if !seen["high"] {
		return wire.Required("high")
	}
	return nil
}

// DecodeChangedMsgpack reads and validates one complete value.
func DecodeChangedMsgpack(data []byte) (Changed, error) {
	var value Changed
	if err := value.UnmarshalMsgpack(data); err != nil {
		return value, err
	}
	return value, value.validate()
}

// MarshalMsgpack encodes Changed as a map in declaration order.
func (v Changed) MarshalMsgpack() ([]byte, error) {
	if err := v.validate(); err != nil {
		return nil, err
	}
	count := uint32(3)
	data := msgp.AppendMapHeader(nil, count)
	data = msgp.AppendString(data, "type")
	data = msgp.AppendString(data, "changed")
	data = msgp.AppendString(data, "low")
	{
		if v.Low >= 0 {
			data = msgp.AppendUint64(data, uint64(v.Low))
		} else {
			data = msgp.AppendInt64(data, int64(v.Low))
		}
	}
	data = msgp.AppendString(data, "high")
	{
		if v.High >= 0 {
			data = msgp.AppendUint64(data, uint64(v.High))
		} else {
			data = msgp.AppendInt64(data, int64(v.High))
		}
	}
	return data, nil
}

// DecodeReplayJSONFrom reads the union using its owner's JSON codec.
func DecodeReplayJSONFrom(dec *jsontext.Decoder) (Replay, error) { return decodeReplay(dec) }

// DecodeReplayMsgpack decodes and checks one variant of Replay.
func DecodeReplayMsgpack(data []byte) (Replay, error) {
	value, err := decodeReplayMsgpack(data)
	if err != nil {
		return nil, err
	}
	return value, validateReplay(value)
}
func decodeReplayMsgpack(data []byte) (Replay, error) {
	fields, err := wire.MPObject(data)
	if err != nil {
		return nil, err
	}
	var tag string
	found := false
	for _, field := range fields {
		if field.Name == "kind" {
			tag, err = wire.MPString(field.Data)
			if err != nil {
				return nil, wire.In("kind", err)
			}
			found = true
		}
	}
	if !found {
		return nil, wire.Required("kind")
	}
	switch tag {
	case "reasoning":
		var value ReplayReasoning
		if err := value.UnmarshalMsgpack(data); err != nil {
			return nil, err
		}
		return value, nil
	}
	return nil, wire.UnknownTag("kind", "reasoning")
}

// EncodeReplayMsgpack checks and encodes the selected variant.
func EncodeReplayMsgpack(value Replay) ([]byte, error) {
	if err := validateReplay(value); err != nil {
		return nil, err
	}
	switch value := value.(type) {
	case ReplayReasoning:
		return value.MarshalMsgpack()
	case *ReplayReasoning:
		return value.MarshalMsgpack()
	}
	return nil, wire.NoVariant("ReplayReasoning")
}

// UnmarshalMsgpack reads the structure of one complete ReplayReasoning value.
func (v *ReplayReasoning) UnmarshalMsgpack(data []byte) error {
	*v = ReplayReasoning{}
	content, err := wire.MPAdjacent(data, "kind", "data", "reasoning")
	if err != nil {
		return err
	}
	return wire.NestIn("data", v.unmarshalMsgpackContent(content))
}
func (v *ReplayReasoning) unmarshalMsgpackContent(data []byte) error {
	fields, err := wire.MPObject(data)
	if err != nil {
		return err
	}
	seen := map[string]bool{}
	for _, field := range fields {
		switch field.Name {
		case "id":
			seen[field.Name] = true
			value, err := (func(data []byte) (string, error) {
				value, err := wire.MPString(data)
				return string(value), err
			})(field.Data)
			if err != nil {
				return wire.In(field.Name, err)
			}
			v.ID = value
		default:
			raw, err := wire.MPJSON(field.Data)
			if err != nil {
				return wire.In(field.Name, err)
			}
			v.Extra = append(v.Extra, wire.Member{Name: field.Name, Value: raw})
		}
	}
	if !seen["id"] {
		return wire.Required("id")
	}
	return nil
}

// DecodeReplayReasoningMsgpack reads and validates one complete value.
func DecodeReplayReasoningMsgpack(data []byte) (ReplayReasoning, error) {
	var value ReplayReasoning
	if err := value.UnmarshalMsgpack(data); err != nil {
		return value, err
	}
	return value, value.validate()
}

// MarshalMsgpack encodes ReplayReasoning as a map in declaration order.
func (v ReplayReasoning) MarshalMsgpack() ([]byte, error) {
	if err := v.validate(); err != nil {
		return nil, err
	}
	count := uint32(1)
	count += uint32(len(v.Extra))
	data := msgp.AppendMapHeader(nil, count)
	data = msgp.AppendString(data, "id")
	{
		if !utf8.ValidString(string(v.ID)) {
			return nil, &wire.InvalidError{Path: "id", Rule: "invalid UTF-8"}
		}
		data = msgp.AppendString(data, string(v.ID))
	}
	for _, member := range v.Extra {
		data = msgp.AppendString(data, member.Name)
		raw, err := wire.JSONMsgpack(member.Value)
		if err != nil {
			return nil, wire.In(member.Name, err)
		}
		data = append(data, raw...)
	}
	envelope := msgp.AppendMapHeader(nil, 2)
	envelope = msgp.AppendString(envelope, "kind")
	envelope = msgp.AppendString(envelope, "reasoning")
	envelope = msgp.AppendString(envelope, "data")
	return append(envelope, data...), nil
}

// UnmarshalMsgpack reads the structure of one complete Embedded value.
func (v *Embedded) UnmarshalMsgpack(data []byte) error {
	*v = Embedded{}
	fields, err := wire.MPObject(data)
	if err != nil {
		return err
	}
	seen := map[string]bool{}
	var embedInterval []wire.MPMember
	for _, field := range fields {
		switch field.Name {
		case "low":
			seen[field.Name] = true
			embedInterval = append(embedInterval, field)
		case "high":
			seen[field.Name] = true
			embedInterval = append(embedInterval, field)
		case "label":
			seen[field.Name] = true
			value, err := (func(data []byte) (Trimmed, error) {
				var v Trimmed
				raw, err := wire.MPJSON(data)
				if err != nil {
					return v, err
				}
				err = json.Unmarshal(raw, &v)
				if err != nil {
					return v, wire.Refusal(err)
				}
				return v, nil
			})(field.Data)
			if err != nil {
				return wire.In(field.Name, err)
			}
			v.Label = value
		default:
			return wire.Unknown(field.Name)
		}
	}
	if !seen["low"] {
		return wire.Required("low")
	}
	if !seen["high"] {
		return wire.Required("high")
	}
	if !seen["label"] {
		return wire.Required("label")
	}
	{
		raw := msgp.AppendMapHeader(nil, uint32(len(embedInterval)))
		for _, field := range embedInterval {
			raw = msgp.AppendString(raw, field.Name)
			raw = append(raw, field.Data...)
		}
		if err := v.Interval.UnmarshalMsgpack(raw); err != nil {
			return err
		}
	}
	return nil
}

// DecodeEmbeddedMsgpack reads and validates one complete value.
func DecodeEmbeddedMsgpack(data []byte) (Embedded, error) {
	var value Embedded
	if err := value.UnmarshalMsgpack(data); err != nil {
		return value, err
	}
	return value, value.validate()
}

// MarshalMsgpack encodes Embedded as a map in declaration order.
func (v Embedded) MarshalMsgpack() ([]byte, error) {
	if err := v.validate(); err != nil {
		return nil, err
	}
	count := uint32(1)
	embeddedInterval, err := v.Interval.MarshalMsgpack()
	if err != nil {
		return nil, err
	}
	embeddedCountInterval, embeddedInterval, err := msgp.ReadMapHeaderBytes(embeddedInterval)
	if err != nil {
		return nil, err
	}
	count += embeddedCountInterval
	data := msgp.AppendMapHeader(nil, count)
	data = append(data, embeddedInterval...)
	data = msgp.AppendString(data, "label")
	{
		if !utf8.ValidString(string(v.Label)) {
			return nil, &wire.InvalidError{Path: "label", Rule: "invalid UTF-8"}
		}
		data = msgp.AppendString(data, string(v.Label))
	}
	return data, nil
}

// UnmarshalMsgpack reads the structure of one complete Measured value.
func (v *Measured) UnmarshalMsgpack(data []byte) error {
	*v = Measured{}
	fields, err := wire.MPObject(data)
	if err != nil {
		return err
	}
	seen := map[string]bool{}
	var embedRounded []wire.MPMember
	for _, field := range fields {
		switch field.Name {
		case "value":
			seen[field.Name] = true
			embedRounded = append(embedRounded, field)
		case "unit":
			seen[field.Name] = true
			value, err := (func(data []byte) (string, error) {
				value, err := wire.MPString(data)
				return string(value), err
			})(field.Data)
			if err != nil {
				return wire.In(field.Name, err)
			}
			v.Unit = value
		default:
			return wire.Unknown(field.Name)
		}
	}
	if !seen["value"] {
		return wire.Required("value")
	}
	if !seen["unit"] {
		return wire.Required("unit")
	}
	{
		raw := msgp.AppendMapHeader(nil, uint32(len(embedRounded)))
		for _, field := range embedRounded {
			raw = msgp.AppendString(raw, field.Name)
			raw = append(raw, field.Data...)
		}
		if err := v.Rounded.UnmarshalMsgpack(raw); err != nil {
			return err
		}
	}
	return nil
}

// DecodeMeasuredMsgpack reads and validates one complete value.
func DecodeMeasuredMsgpack(data []byte) (Measured, error) {
	var value Measured
	if err := value.UnmarshalMsgpack(data); err != nil {
		return value, err
	}
	return value, value.validate()
}

// MarshalMsgpack encodes Measured as a map in declaration order.
func (v Measured) MarshalMsgpack() ([]byte, error) {
	if err := v.validate(); err != nil {
		return nil, err
	}
	count := uint32(1)
	embeddedRounded, err := v.Rounded.MarshalMsgpack()
	if err != nil {
		return nil, err
	}
	embeddedCountRounded, embeddedRounded, err := msgp.ReadMapHeaderBytes(embeddedRounded)
	if err != nil {
		return nil, err
	}
	count += embeddedCountRounded
	data := msgp.AppendMapHeader(nil, count)
	data = append(data, embeddedRounded...)
	data = msgp.AppendString(data, "unit")
	{
		if !utf8.ValidString(string(v.Unit)) {
			return nil, &wire.InvalidError{Path: "unit", Rule: "invalid UTF-8"}
		}
		data = msgp.AppendString(data, string(v.Unit))
	}
	return data, nil
}

// UnmarshalMsgpack reads the structure of one complete Containers value.
func (v *Containers) UnmarshalMsgpack(data []byte) error {
	*v = Containers{}
	fields, err := wire.MPObject(data)
	if err != nil {
		return err
	}
	seen := map[string]bool{}
	for _, field := range fields {
		switch field.Name {
		case "map":
			seen[field.Name] = true
			value, err := (func(data []byte) (exporttest.Intervals, error) {
				return wire.MPMap[string](data, func(data []byte) (exporttest.Interval, error) {
					var v exporttest.Interval
					err := v.UnmarshalMsgpack(data)
					return v, err
				})
			})(field.Data)
			if err != nil {
				return wire.In(field.Name, err)
			}
			v.Map = value
		case "list":
			seen[field.Name] = true
			value, err := (func(data []byte) (exporttest.IntervalList, error) {
				return wire.MPArray(data, func(data []byte) (exporttest.Interval, error) {
					var v exporttest.Interval
					err := v.UnmarshalMsgpack(data)
					return v, err
				})
			})(field.Data)
			if err != nil {
				return wire.In(field.Name, err)
			}
			v.List = value
		default:
			return wire.Unknown(field.Name)
		}
	}
	if !seen["map"] {
		return wire.Required("map")
	}
	if !seen["list"] {
		return wire.Required("list")
	}
	return nil
}

// DecodeContainersMsgpack reads and validates one complete value.
func DecodeContainersMsgpack(data []byte) (Containers, error) {
	var value Containers
	if err := value.UnmarshalMsgpack(data); err != nil {
		return value, err
	}
	return value, value.validate()
}

// MarshalMsgpack encodes Containers as a map in declaration order.
func (v Containers) MarshalMsgpack() ([]byte, error) {
	if err := v.validate(); err != nil {
		return nil, err
	}
	count := uint32(2)
	data := msgp.AppendMapHeader(nil, count)
	data = msgp.AppendString(data, "map")
	{
		data = msgp.AppendMapHeader(data, uint32(len(v.Map)))
		for _, key := range slices.Sorted(maps.Keys(v.Map)) {
			if !utf8.ValidString(string(key)) {
				return nil, &wire.InvalidError{Path: "map", Rule: "invalid UTF-8 map key"}
			}
			data = msgp.AppendString(data, string(key))
			item := v.Map[key]
			itemPath := wire.Prefix("map", wire.Key(string(key)))
			_ = itemPath
			encoded, err := item.MarshalMsgpack()
			if err != nil {
				return nil, wire.In(itemPath, err)
			}
			data = append(data, encoded...)
		}
	}
	data = msgp.AppendString(data, "list")
	{
		data = msgp.AppendArrayHeader(data, uint32(len(v.List)))
		for index, item := range v.List {
			itemPath := wire.Prefix("list", wire.Index(index))
			_ = itemPath
			encoded, err := item.MarshalMsgpack()
			if err != nil {
				return nil, wire.In(itemPath, err)
			}
			data = append(data, encoded...)
		}
	}
	return data, nil
}
