// Code generated by wiregen; DO NOT EDIT.

package machinesproto

import (
	"encoding/json/jsontext"

	"github.com/wspl/demi/go/internal/wire"
)

// UnmarshalJSONFrom decodes the JSON object of ImageState: it refuses a member that
// the type does not have, a required member that is missing, a null, and a
// value of another JSON kind than the member's, naming the member.
func (v *ImageState) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = ImageState{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "generation":
			seen |= 1 << 0
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("generation", err)
			}
			v.Generation = GenerationID(s)
		case "baseVersion":
			seen |= 1 << 1
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("baseVersion", err)
			}
			v.BaseVersion = BaseVersion(s)
		case "resetId":
			seen |= 1 << 2
			if wire.IsNull(dec) {
				if _, err := dec.ReadToken(); err != nil {
					return wire.In("resetId", err)
				}
			} else {
				var value string
				s, err := wire.ReadString(dec)
				if err != nil {
					return wire.In("resetId", err)
				}
				value = s
				v.ResetID = &value
			}
		case "systemBytes":
			seen |= 1 << 3
			n, err := wire.ReadUint(dec, 64)
			if err != nil {
				return wire.In("systemBytes", err)
			}
			v.SystemBytes = n
		case "homeBytes":
			seen |= 1 << 4
			n, err := wire.ReadUint(dec, 64)
			if err != nil {
				return wire.In("homeBytes", err)
			}
			v.HomeBytes = n
		default:
			return wire.Unknown(name)
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("generation")
	}
	if seen&(1<<1) == 0 {
		return wire.Required("baseVersion")
	}
	if seen&(1<<2) == 0 {
		return wire.Required("resetId")
	}
	if seen&(1<<3) == 0 {
		return wire.Required("systemBytes")
	}
	if seen&(1<<4) == 0 {
		return wire.Required("homeBytes")
	}
	return nil
}

// validate checks the rules of the fields of ImageState, and reports every one that
// is broken.
func (v ImageState) validate() error {
	var r wire.Report
	r.Pattern("generation", string(v.Generation), imageName)
	r.Pattern("baseVersion", string(v.BaseVersion), imageName)
	r.Uint("systemBytes", uint64(v.SystemBytes), wire.AtLeast(1))
	r.Uint("homeBytes", uint64(v.HomeBytes), wire.AtLeast(1))
	return r.Err()
}
