// Code generated by contractgen; DO NOT EDIT.
package codecs

import (
	"encoding/json"
	"fmt"
	"github.com/wspl/demi/internal/contract"
	runnerwire "github.com/wspl/demi/internal/runnerwire"
)

func DecodeAddress(data []byte) (Address, error) { return contract.Decode[Address](data) }
func (v Address) Validate() error                { return contractValidateAddress(v, 0) }
func contractValidateAddress(v Address, depth int) error {
	if depth > 1000 {
		return fmt.Errorf("validation nesting exceeds 1000")
	}
	return nil
}
func (v *Address) UnmarshalJSON(data []byte) error {
	obj, err := contract.Decode[map[string]json.RawMessage](data)
	if err != nil {
		return err
	}
	var next Address
	for key := range obj {
		switch key {
		case "url":
		default:
			return contract.At(key, fmt.Errorf("unknown field"))
		}
	}
	{
		raw, ok := obj["url"]
		if !ok {
			return contract.At("url", fmt.Errorf("required field is absent"))
		}
		if ok {
			value, err := contract.Decode[runnerwire.BackendURL](raw)
			if err != nil {
				return contract.At("url", err)
			}
			next.URL = value
		}
	}
	if err := next.Validate(); err != nil {
		return err
	}
	*v = next
	return nil
}
func (v Address) MarshalJSON() ([]byte, error) {
	if err := v.Validate(); err != nil {
		return nil, err
	}
	fields := []contract.Field{}
	fields = append(fields, contract.Field{Name: "url", Value: v.URL})
	return contract.EncodeObject(fields)
}
func DecodeEmpty(data []byte) (Empty, error) { return contract.Decode[Empty](data) }
func (v Empty) Validate() error              { return contractValidateEmpty(v, 0) }
func contractValidateEmpty(v Empty, depth int) error {
	if depth > 1000 {
		return fmt.Errorf("validation nesting exceeds 1000")
	}
	return nil
}
func (v *Empty) UnmarshalJSON(data []byte) error {
	_, err := contract.Decode[map[string]json.RawMessage](data)
	if err != nil {
		return err
	}
	var next Empty
	if err := next.Validate(); err != nil {
		return err
	}
	*v = next
	return nil
}
func (v Empty) MarshalJSON() ([]byte, error) {
	if err := v.Validate(); err != nil {
		return nil, err
	}
	fields := []contract.Field{}
	return contract.EncodeObject(fields)
}
func DecodeEnvelope(data []byte) (Envelope, error) { return contract.Decode[Envelope](data) }
func (v Envelope) Validate() error                 { return contractValidateEnvelope(v, 0) }
func contractValidateEnvelope(v Envelope, depth int) error {
	if depth > 1000 {
		return fmt.Errorf("validation nesting exceeds 1000")
	}
	return nil
}
func (v *Envelope) UnmarshalJSON(data []byte) error {
	obj, err := contract.Decode[map[string]json.RawMessage](data)
	if err != nil {
		return err
	}
	var next Envelope
	for key := range obj {
		switch key {
		case "value":
		default:
			return contract.At(key, fmt.Errorf("unknown field"))
		}
	}
	{
		raw, ok := obj["value"]
		if !ok {
			return contract.At("value", fmt.Errorf("required field is absent"))
		}
		if ok {
			value, err := contract.Decode[Private](raw)
			if err != nil {
				return contract.At("value", err)
			}
			next.Value = value
		}
	}
	if err := next.Validate(); err != nil {
		return err
	}
	*v = next
	return nil
}
func (v Envelope) MarshalJSON() ([]byte, error) {
	if err := v.Validate(); err != nil {
		return nil, err
	}
	fields := []contract.Field{}
	fields = append(fields, contract.Field{Name: "value", Value: v.Value})
	return contract.EncodeObject(fields)
}
func DecodeWake(data []byte) (Wake, error) { return contract.Decode[Wake](data) }
func (v Wake) Validate() error             { return contractValidateWake(v, 0) }
func contractValidateWake(v Wake, depth int) error {
	if depth > 1000 {
		return fmt.Errorf("validation nesting exceeds 1000")
	}
	return nil
}
func (v *Wake) UnmarshalJSON(data []byte) error {
	obj, err := contract.Decode[map[string]json.RawMessage](data)
	if err != nil {
		return err
	}
	var next Wake
	for key := range obj {
		switch key {
		case "boot":
		default:
			return contract.At(key, fmt.Errorf("unknown field"))
		}
	}
	{
		raw, ok := obj["boot"]
		if !ok {
			return contract.At("boot", fmt.Errorf("required field is absent"))
		}
		if ok {
			value, err := contract.Decode[runnerwire.ManagedBoot](raw)
			if err != nil {
				return contract.At("boot", err)
			}
			next.Boot = value
		}
	}
	if err := next.Validate(); err != nil {
		return err
	}
	*v = next
	return nil
}
func (v Wake) MarshalJSON() ([]byte, error) {
	if err := v.Validate(); err != nil {
		return nil, err
	}
	fields := []contract.Field{}
	fields = append(fields, contract.Field{Name: "boot", Value: v.Boot})
	return contract.EncodeObject(fields)
}
func DecodeEmptyMsgpack(data []byte) (Empty, error) { return contract.DecodeMsgpack[Empty](data) }
func (v *Empty) UnmarshalMsgpack(data []byte) error {
	_, err := contract.MsgpackObject(data)
	if err != nil {
		return err
	}
	var next Empty
	if err := next.Validate(); err != nil {
		return err
	}
	*v = next
	return nil
}
func (v Empty) MarshalMsgpack() ([]byte, error) {
	if err := v.Validate(); err != nil {
		return nil, err
	}
	fields := []contract.Field{}
	return contract.EncodeMsgpackObject(fields)
}
func DecodeEnvelopeMsgpack(data []byte) (Envelope, error) {
	return contract.DecodeMsgpack[Envelope](data)
}
func (v *Envelope) UnmarshalMsgpack(data []byte) error {
	obj, err := contract.MsgpackObject(data)
	if err != nil {
		return err
	}
	var next Envelope
	{
		raw, present := obj["value"]
		delete(obj, "value")
		if !present {
			return contract.At("value", fmt.Errorf("required field is absent"))
		}
		if present {
			value, err := contract.DecodeMsgpack[Private](raw)
			if err != nil {
				return contract.At("value", err)
			}
			next.Value = value
		}
	}
	for key := range obj {
		return contract.At(key, fmt.Errorf("unknown field"))
	}
	if err := next.Validate(); err != nil {
		return err
	}
	*v = next
	return nil
}
func (v Envelope) MarshalMsgpack() ([]byte, error) {
	if err := v.Validate(); err != nil {
		return nil, err
	}
	fields := []contract.Field{}
	fields = append(fields, contract.Field{Name: "value", Value: v.Value})
	return contract.EncodeMsgpackObject(fields)
}
