// Code generated by wiregen; DO NOT EDIT.

package machines

import (
	"encoding/json/jsontext"

	"github.com/wspl/demi/go/internal/wire"
)

// UnmarshalJSONFrom decodes the JSON object of namespaceOwner: it refuses a member that
// the type does not have, a required member that is missing, a null, and a
// value of another JSON kind than the member's, naming the member.
func (v *namespaceOwner) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = namespaceOwner{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "dataDir":
			seen |= 1 << 0
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("dataDir", err)
			}
			v.DataDir = s
		default:
			return wire.Unknown(name)
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("dataDir")
	}
	return nil
}

// validate checks the rules of the fields of namespaceOwner, and reports every one that
// is broken.
func (namespaceOwner) validate() error {
	return nil
}
