// Builds `llms-full.txt` — the complete Demi documentation inlined into one file
// for LLM ingestion. Run with `bun run llms`. Edit the source markdown (README,
// guides, specs), not the generated output.
import { readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')

// Order matters: overview first, then how-tos, then the deeper reference specs.
const sections: Array<{ title: string; path: string }> = [
  { title: 'Overview', path: 'README.md' },
  { title: 'Guide: Add a Provider', path: 'docs/guides/add-a-provider.md' },
  { title: 'Guide: Implement a Host', path: 'docs/guides/implement-a-host.md' },
  { title: 'Guide: Embed the UI', path: 'docs/guides/embed-the-ui.md' },
  { title: 'Reference: Package Boundaries', path: 'docs/package-boundaries.md' },
  { title: 'Reference: Shell & Yield Control', path: 'docs/shell-yield-control-plan.md' },
  { title: 'Reference: Tool Rendering Spec', path: 'docs/tool-rendering-spec.md' },
  { title: 'Contributing', path: 'CONTRIBUTING.md' },
]

const header = [
  '# Demi — full documentation',
  '',
  '> Generated by `scripts/build-llms.ts` (run `bun run llms`). Do not edit by hand —',
  '> edit the source markdown listed below. This file inlines the complete Demi',
  '> documentation for LLM ingestion; `llms.txt` is the curated index.',
  '',
].join('\n')

const blocks: string[] = [header]
for (const { title, path } of sections) {
  const body = (await readFile(resolve(repoRoot, path), 'utf8')).trim()
  blocks.push([`---`, '', `# ${title}`, `<!-- source: ${path} -->`, '', body].join('\n'))
}

await writeFile(resolve(repoRoot, 'llms-full.txt'), `${blocks.join('\n\n')}\n`, 'utf8')

const lines = blocks.join('\n\n').split('\n').length
process.stdout.write(`Wrote llms-full.txt (${sections.length} sections, ${lines} lines)\n`)
