// Code generated by wiregen; DO NOT EDIT.

package grokbuild

import (
	"encoding/json/jsontext"

	"github.com/wspl/demi/go/internal/wire"
	"github.com/wspl/demi/go/provider"
)

// UnmarshalJSONFrom decodes the JSON object of deviceCode: it ignores a member that
// the type does not have, and refuses a required member that is missing, a
// null, and a value of another JSON kind than the member's, naming the member.
func (v *deviceCode) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = deviceCode{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "device_code":
			seen |= 1 << 0
			if err := v.DeviceCode.UnmarshalJSONFrom(dec); err != nil {
				return wire.In("device_code", err)
			}
		case "user_code":
			seen |= 1 << 1
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("user_code", err)
			}
			v.UserCode = s
		case "verification_uri":
			if wire.IsNull(dec) {
				if _, err := dec.ReadToken(); err != nil {
					return wire.In("verification_uri", err)
				}
			} else {
				var value string
				s, err := wire.ReadString(dec)
				if err != nil {
					return wire.In("verification_uri", err)
				}
				value = s
				v.VerificationURI = &value
			}
		case "verification_uri_complete":
			if wire.IsNull(dec) {
				if _, err := dec.ReadToken(); err != nil {
					return wire.In("verification_uri_complete", err)
				}
			} else {
				var value string
				s, err := wire.ReadString(dec)
				if err != nil {
					return wire.In("verification_uri_complete", err)
				}
				value = s
				v.VerificationURIComplete = &value
			}
		case "interval":
			if wire.IsNull(dec) {
				if _, err := dec.ReadToken(); err != nil {
					return wire.In("interval", err)
				}
			} else {
				var value provider.PollInterval
				if err := value.UnmarshalJSONFrom(dec); err != nil {
					return wire.In("interval", err)
				}
				v.Interval = &value
			}
		default:
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("device_code")
	}
	if seen&(1<<1) == 0 {
		return wire.Required("user_code")
	}
	return nil
}

// validate checks the rules of the fields of deviceCode, and reports every one that
// is broken.
func (v deviceCode) validate() error {
	var r wire.Report
	r.Check("device_code", provider.Validate(v.DeviceCode))
	r.Check("user_code", userCode(v.UserCode))
	if v.VerificationURI != nil {
		r.Check("verification_uri", verificationURI((*v.VerificationURI)))
	}
	if v.VerificationURIComplete != nil {
		r.Check("verification_uri_complete", verificationURI((*v.VerificationURIComplete)))
	}
	if v.Interval != nil {
		r.Check("interval", provider.Validate((*v.Interval)))
	}
	return r.Err()
}

// UnmarshalJSONFrom decodes the JSON object of tokenRefusal: it ignores a member that
// the type does not have, and refuses a required member that is missing, a
// null, and a value of another JSON kind than the member's, naming the member.
func (v *tokenRefusal) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = tokenRefusal{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "error":
			if wire.IsNull(dec) {
				if _, err := dec.ReadToken(); err != nil {
					return wire.In("error", err)
				}
			} else {
				var value provider.ReportedString
				if err := value.UnmarshalJSONFrom(dec); err != nil {
					return wire.In("error", err)
				}
				v.Error = &value
			}
		default:
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
	return nil
}

// validate checks the rules of the fields of tokenRefusal, and reports every one that
// is broken.
func (v tokenRefusal) validate() error {
	var r wire.Report
	if v.Error != nil {
		r.Check("error", provider.Validate((*v.Error)))
	}
	return r.Err()
}

// UnmarshalJSONFrom decodes the JSON object of userAnswer: it ignores a member that
// the type does not have, and refuses a required member that is missing, a
// null, and a value of another JSON kind than the member's, naming the member.
func (v *userAnswer) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = userAnswer{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "userId":
			if wire.IsNull(dec) {
				if _, err := dec.ReadToken(); err != nil {
					return wire.In("userId", err)
				}
			} else {
				var value provider.ReportedString
				if err := value.UnmarshalJSONFrom(dec); err != nil {
					return wire.In("userId", err)
				}
				v.UserID = &value
			}
		case "user_id":
			if wire.IsNull(dec) {
				if _, err := dec.ReadToken(); err != nil {
					return wire.In("user_id", err)
				}
			} else {
				var value provider.ReportedString
				if err := value.UnmarshalJSONFrom(dec); err != nil {
					return wire.In("user_id", err)
				}
				v.UserIDSnake = &value
			}
		case "principalType":
			if wire.IsNull(dec) {
				if _, err := dec.ReadToken(); err != nil {
					return wire.In("principalType", err)
				}
			} else {
				var value provider.ReportedString
				if err := value.UnmarshalJSONFrom(dec); err != nil {
					return wire.In("principalType", err)
				}
				v.PrincipalType = &value
			}
		case "principal_type":
			if wire.IsNull(dec) {
				if _, err := dec.ReadToken(); err != nil {
					return wire.In("principal_type", err)
				}
			} else {
				var value provider.ReportedString
				if err := value.UnmarshalJSONFrom(dec); err != nil {
					return wire.In("principal_type", err)
				}
				v.PrincipalTypeSnake = &value
			}
		case "principalId":
			if wire.IsNull(dec) {
				if _, err := dec.ReadToken(); err != nil {
					return wire.In("principalId", err)
				}
			} else {
				var value provider.ReportedString
				if err := value.UnmarshalJSONFrom(dec); err != nil {
					return wire.In("principalId", err)
				}
				v.PrincipalID = &value
			}
		case "principal_id":
			if wire.IsNull(dec) {
				if _, err := dec.ReadToken(); err != nil {
					return wire.In("principal_id", err)
				}
			} else {
				var value provider.ReportedString
				if err := value.UnmarshalJSONFrom(dec); err != nil {
					return wire.In("principal_id", err)
				}
				v.PrincipalIDSnake = &value
			}
		case "email":
			if wire.IsNull(dec) {
				if _, err := dec.ReadToken(); err != nil {
					return wire.In("email", err)
				}
			} else {
				var value provider.ReportedString
				if err := value.UnmarshalJSONFrom(dec); err != nil {
					return wire.In("email", err)
				}
				v.Email = &value
			}
		default:
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
	return nil
}

// validate checks the rules of the fields of userAnswer, and reports every one that
// is broken.
func (v userAnswer) validate() error {
	var r wire.Report
	if v.UserID != nil {
		r.Check("userId", provider.Validate((*v.UserID)))
	}
	if v.UserIDSnake != nil {
		r.Check("user_id", provider.Validate((*v.UserIDSnake)))
	}
	if v.PrincipalType != nil {
		r.Check("principalType", provider.Validate((*v.PrincipalType)))
	}
	if v.PrincipalTypeSnake != nil {
		r.Check("principal_type", provider.Validate((*v.PrincipalTypeSnake)))
	}
	if v.PrincipalID != nil {
		r.Check("principalId", provider.Validate((*v.PrincipalID)))
	}
	if v.PrincipalIDSnake != nil {
		r.Check("principal_id", provider.Validate((*v.PrincipalIDSnake)))
	}
	if v.Email != nil {
		r.Check("email", provider.Validate((*v.Email)))
	}
	return r.Err()
}
