// Code generated by contractgen; DO NOT EDIT.
package session

import (
	"encoding/json"
	"fmt"
	"github.com/wspl/demi/internal/contract"
)

func DecodeExecution(data []byte) (Execution, error) { return contract.Decode[Execution](data) }
func (v Execution) Validate() error                  { return contractValidateExecution(v, 0) }
func contractValidateExecution(v Execution, depth int) error {
	if depth > 1000 {
		return fmt.Errorf("validation nesting exceeds 1000")
	}
	switch string(v) {
	case "idle", "provider_streaming", "tool_executing", "compacting", "finalizing", "pending_yield":
	default:
		return contract.At("", fmt.Errorf("unknown value"))
	}
	if err := contract.Text(string(v), 0, -1, ""); err != nil {
		return contract.At("", err)
	}
	return nil
}
func (v *Execution) UnmarshalJSON(data []byte) error {
	value, err := contract.Decode[string](data)
	if err != nil {
		return err
	}
	next := Execution(value)
	if err := next.Validate(); err != nil {
		return err
	}
	*v = next
	return nil
}
func (v Execution) MarshalJSON() ([]byte, error) {
	if err := v.Validate(); err != nil {
		return nil, err
	}
	return contract.EncodeJSON(string(v))
}
func ExecutionJSONSchema() json.RawMessage {
	return json.RawMessage("{\"description\":\"What a session is doing, as a supervisor observes it (`subagents.md`\\n§ `demi agent show`); not the phase that `phase` frames carry.\",\"enum\":[\"idle\",\"provider_streaming\",\"tool_executing\",\"compacting\",\"finalizing\",\"pending_yield\"],\"title\":\"Execution\",\"type\":\"string\"}")
}
