// Code generated by contractgen; DO NOT EDIT.
package presence

import (
	"encoding/json"
	"fmt"
	"github.com/wspl/demi/internal/contract"
	runnerwire "github.com/wspl/demi/internal/runnerwire"
)

func DecodeDefaults(data []byte) (Defaults, error) { return contract.Decode[Defaults](data) }
func (v Defaults) Validate() error                 { return contractValidateDefaults(v, 0) }
func contractValidateDefaults(v Defaults, depth int) error {
	if depth > 1000 {
		return fmt.Errorf("validation nesting exceeds 1000")
	}
	for i, item := range v.Items {
		_ = i
		_ = item
		if err := contract.Text(string(item), 0, -1, ""); err != nil {
			return contract.At(fmt.Sprintf("%s[%d]", "items", i), err)
		}
	}
	if len(v.Items) > 2 {
		return contract.At("items", fmt.Errorf("too many items"))
	}
	{
		collection := v.Labels
		if collection == nil {
			collection = make(Labels, 0)
		}
		if err := contractValidateLabels(collection, depth+1); err != nil {
			return contract.At("labels", err)
		}
	}
	if v.Count > 10 {
		return contract.At("count", fmt.Errorf("outside numeric bounds"))
	}
	if err := contract.Text(string(v.Text), 0, 4, ""); err != nil {
		return contract.At("text", err)
	}
	return nil
}
func (v *Defaults) UnmarshalJSON(data []byte) error {
	obj, err := contract.Decode[map[string]json.RawMessage](data)
	if err != nil {
		return err
	}
	var next Defaults
	for key := range obj {
		switch key {
		case "items", "labels", "enabled", "count", "text":
		default:
			return contract.At(key, fmt.Errorf("unknown field"))
		}
	}
	next.Items = make([]string, 0)
	{
		raw, ok := obj["items"]
		if ok {
			value, err := func(b []byte) ([]string, error) { return contract.List(b, contract.Decode[string]) }(raw)
			if err != nil {
				return contract.At("items", err)
			}
			next.Items = value
		}
	}
	next.Labels = make(Labels, 0)
	{
		raw, ok := obj["labels"]
		if ok {
			value, err := contract.Decode[Labels](raw)
			if err != nil {
				return contract.At("labels", err)
			}
			next.Labels = value
		}
	}
	{
		raw, ok := obj["enabled"]
		if ok {
			value, err := contract.Decode[bool](raw)
			if err != nil {
				return contract.At("enabled", err)
			}
			next.Enabled = value
		}
	}
	{
		raw, ok := obj["count"]
		if ok {
			value, err := contract.Decode[uint32](raw)
			if err != nil {
				return contract.At("count", err)
			}
			next.Count = value
		}
	}
	{
		raw, ok := obj["text"]
		if ok {
			value, err := contract.Decode[string](raw)
			if err != nil {
				return contract.At("text", err)
			}
			next.Text = value
		}
	}
	if err := next.Validate(); err != nil {
		return err
	}
	*v = next
	return nil
}
func (v Defaults) MarshalJSON() ([]byte, error) {
	if v.Items == nil {
		v.Items = make([]string, 0)
	}
	if v.Labels == nil {
		v.Labels = make(Labels, 0)
	}
	if err := v.Validate(); err != nil {
		return nil, err
	}
	fields := []contract.Field{}
	fields = append(fields, contract.Field{Name: "items", Value: v.Items})
	fields = append(fields, contract.Field{Name: "labels", Value: v.Labels})
	fields = append(fields, contract.Field{Name: "enabled", Value: v.Enabled})
	fields = append(fields, contract.Field{Name: "count", Value: v.Count})
	fields = append(fields, contract.Field{Name: "text", Value: v.Text})
	return contract.EncodeObject(fields)
}
func DefaultsJSONSchema() json.RawMessage {
	return json.RawMessage("{\"additionalProperties\":false,\"properties\":{\"items\":{\"type\":\"array\",\"items\":{\"type\":\"string\"},\"maxItems\":2,\"default\":[]},\"labels\":{\"type\":\"object\",\"additionalProperties\":{\"type\":\"string\"},\"default\":{}},\"enabled\":{\"type\":\"boolean\",\"default\":false},\"count\":{\"type\":\"integer\",\"format\":\"uint32\",\"minimum\":0,\"maximum\":10,\"default\":0},\"text\":{\"type\":\"string\",\"maxLength\":4,\"default\":\"\"}},\"title\":\"Defaults\",\"type\":\"object\"}")
}
func DefaultsPluginJSONSchema() json.RawMessage {
	return json.RawMessage("{\"$defs\":{\"Labels\":{\"type\":\"object\",\"additionalProperties\":{\"type\":\"string\"}}},\"additionalProperties\":false,\"properties\":{\"items\":{\"type\":\"array\",\"items\":{\"type\":\"string\"},\"maxItems\":2,\"default\":[]},\"labels\":{\"$ref\":\"#/$defs/Labels\",\"default\":{}},\"enabled\":{\"type\":\"boolean\",\"default\":false},\"count\":{\"type\":\"integer\",\"format\":\"uint32\",\"minimum\":0,\"maximum\":10,\"default\":0},\"text\":{\"type\":\"string\",\"maxLength\":4,\"default\":\"\"}},\"title\":\"Defaults\",\"type\":\"object\"}")
}
func DecodeInstallEnvelope(data []byte) (InstallEnvelope, error) {
	return contract.Decode[InstallEnvelope](data)
}
func (v InstallEnvelope) Validate() error { return contractValidateInstallEnvelope(v, 0) }
func contractValidateInstallEnvelope(v InstallEnvelope, depth int) error {
	if depth > 1000 {
		return fmt.Errorf("validation nesting exceeds 1000")
	}
	if err := v.Install.Validate(); err != nil {
		return contract.At("install", err)
	}
	return nil
}
func (v *InstallEnvelope) UnmarshalJSON(data []byte) error {
	obj, err := contract.Decode[map[string]json.RawMessage](data)
	if err != nil {
		return err
	}
	var next InstallEnvelope
	for key := range obj {
		switch key {
		case "install":
		default:
			return contract.At(key, fmt.Errorf("unknown field"))
		}
	}
	{
		raw, ok := obj["install"]
		if !ok {
			return contract.At("install", fmt.Errorf("required field is absent"))
		}
		if ok {
			value, err := contract.Decode[runnerwire.Install](raw)
			if err != nil {
				return contract.At("install", err)
			}
			next.Install = value
		}
	}
	if err := next.Validate(); err != nil {
		return err
	}
	*v = next
	return nil
}
func (v InstallEnvelope) MarshalJSON() ([]byte, error) {
	if err := v.Validate(); err != nil {
		return nil, err
	}
	fields := []contract.Field{}
	fields = append(fields, contract.Field{Name: "install", Value: v.Install})
	return contract.EncodeObject(fields)
}
func InstallEnvelopeJSONSchema() json.RawMessage {
	return json.RawMessage("{\"additionalProperties\":false,\"properties\":{\"install\":{\"type\":\"object\",\"additionalProperties\":false,\"properties\":{\"package\":{\"type\":\"string\",\"description\":\"The package, such as `demi.browser`.\",\"minLength\":1,\"maxLength\":200},\"name\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":100},\"version\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":100},\"phase\":{\"type\":\"string\",\"enum\":[\"download\",\"unpack\"],\"description\":\"Where an install is: downloading the artifact, or unpacking a\\nresource's archive.\"},\"done\":{\"type\":\"integer\",\"format\":\"uint64\",\"minimum\":0,\"maximum\":9007199254740991},\"total\":{\"type\":\"integer\",\"format\":\"uint64\",\"minimum\":1,\"maximum\":9007199254740991}},\"required\":[\"package\",\"name\",\"version\",\"phase\",\"done\",\"total\"],\"description\":\"One artifact being installed for a command package: its line's name and\\nits version, such as `Chrome for Testing` and `153.0.8010.36`, and how\\nfar it is, in bytes of its size.\"}},\"required\":[\"install\"],\"title\":\"InstallEnvelope\",\"type\":\"object\"}")
}
func InstallEnvelopePluginJSONSchema() json.RawMessage {
	return json.RawMessage("{\"$defs\":{\"Install\":{\"type\":\"object\",\"additionalProperties\":false,\"properties\":{\"package\":{\"type\":\"string\",\"description\":\"The package, such as `demi.browser`.\",\"minLength\":1,\"maxLength\":200},\"name\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":100},\"version\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":100},\"phase\":{\"$ref\":\"#/$defs/InstallPhase\"},\"done\":{\"type\":\"integer\",\"format\":\"uint64\",\"minimum\":0,\"maximum\":9007199254740991},\"total\":{\"type\":\"integer\",\"format\":\"uint64\",\"minimum\":1,\"maximum\":9007199254740991}},\"required\":[\"package\",\"name\",\"version\",\"phase\",\"done\",\"total\"],\"description\":\"One artifact being installed for a command package: its line's name and\\nits version, such as `Chrome for Testing` and `153.0.8010.36`, and how\\nfar it is, in bytes of its size.\"},\"InstallPhase\":{\"type\":\"string\",\"enum\":[\"download\",\"unpack\"],\"description\":\"Where an install is: downloading the artifact, or unpacking a\\nresource's archive.\"}},\"additionalProperties\":false,\"properties\":{\"install\":{\"$ref\":\"#/$defs/Install\"}},\"required\":[\"install\"],\"title\":\"InstallEnvelope\",\"type\":\"object\"}")
}
func DecodeLabels(data []byte) (Labels, error) { return contract.Decode[Labels](data) }
func (v Labels) Validate() error               { return contractValidateLabels(v, 0) }
func contractValidateLabels(v Labels, depth int) error {
	if depth > 1000 {
		return fmt.Errorf("validation nesting exceeds 1000")
	}
	if v == nil {
		return contract.At("", fmt.Errorf("required record is nil"))
	}
	for key, item := range v {
		_ = item
		if err := contract.Text(key, 0, -1, ""); err != nil {
			return contract.At("", err)
		}
		if err := contract.Text(string(item), 0, -1, ""); err != nil {
			return contract.At(fmt.Sprintf("%s[%q]", "", key), err)
		}
	}
	return nil
}
func (v *Labels) UnmarshalJSON(data []byte) error {
	value, err := func(b []byte) (map[string]string, error) { return contract.Record(b, contract.Decode[string], false) }(data)
	if err != nil {
		return err
	}
	next := Labels(value)
	if err := next.Validate(); err != nil {
		return err
	}
	*v = next
	return nil
}
func (v Labels) MarshalJSON() ([]byte, error) {
	if err := v.Validate(); err != nil {
		return nil, err
	}
	return contract.EncodeJSON(map[string]string(v))
}
func DecodePatch(data []byte) (Patch, error) { return contract.Decode[Patch](data) }
func (v Patch) Validate() error              { return contractValidatePatch(v, 0) }
func contractValidatePatch(v Patch, depth int) error {
	if depth > 1000 {
		return fmt.Errorf("validation nesting exceeds 1000")
	}
	if v.Option != nil {
		if err := contract.Text(string((*v.Option)), 0, 4, ""); err != nil {
			return contract.At("option", err)
		}
	}
	if v.Double != nil {
		if (*v.Double) != nil {
			if err := contract.Text(string((*(*v.Double))), 0, 4, ""); err != nil {
				return contract.At("double", err)
			}
		}
	}
	if v.Items != nil {
		if (*v.Items) != nil {
			if (*(*v.Items)) == nil {
				return contract.At("items", fmt.Errorf("required array is nil"))
			}
			for i, item := range *(*v.Items) {
				_ = i
				_ = item
				if err := contract.Text(string(item), 0, -1, ""); err != nil {
					return contract.At(fmt.Sprintf("%s[%d]", "items", i), err)
				}
			}
		}
	}
	return nil
}
func (v *Patch) UnmarshalJSON(data []byte) error {
	obj, err := contract.Decode[map[string]json.RawMessage](data)
	if err != nil {
		return err
	}
	var next Patch
	for key := range obj {
		switch key {
		case "option", "double", "items":
		default:
			return contract.At(key, fmt.Errorf("unknown field"))
		}
	}
	{
		raw, ok := obj["option"]
		if ok {
			if !contract.IsNull(raw) {
				value, err := func(b []byte) (*string, error) { return contract.Pointer(b, contract.Decode[string]) }(raw)
				if err != nil {
					return contract.At("option", err)
				}
				next.Option = value
			}
		}
	}
	{
		raw, ok := obj["double"]
		if ok {
			if contract.IsNull(raw) {
				next.Double = new(*string)
			} else {
				value, err := func(b []byte) (**string, error) {
					return contract.Pointer(b, func(b []byte) (*string, error) { return contract.Pointer(b, contract.Decode[string]) })
				}(raw)
				if err != nil {
					return contract.At("double", err)
				}
				next.Double = value
			}
		}
	}
	{
		raw, ok := obj["items"]
		if ok {
			if contract.IsNull(raw) {
				next.Items = new(*[]string)
			} else {
				value, err := func(b []byte) (**[]string, error) {
					return contract.Pointer(b, func(b []byte) (*[]string, error) {
						return contract.Pointer(b, func(b []byte) ([]string, error) { return contract.List(b, contract.Decode[string]) })
					})
				}(raw)
				if err != nil {
					return contract.At("items", err)
				}
				next.Items = value
			}
		}
	}
	if err := next.Validate(); err != nil {
		return err
	}
	*v = next
	return nil
}
func (v Patch) MarshalJSON() ([]byte, error) {
	if err := v.Validate(); err != nil {
		return nil, err
	}
	fields := []contract.Field{}
	if v.Option != nil {
		fields = append(fields, contract.Field{Name: "option", Value: v.Option})
	}
	if v.Double != nil {
		fields = append(fields, contract.Field{Name: "double", Value: v.Double})
	}
	if v.Items != nil {
		fields = append(fields, contract.Field{Name: "items", Value: v.Items})
	}
	return contract.EncodeObject(fields)
}
func PatchJSONSchema() json.RawMessage {
	return json.RawMessage("{\"additionalProperties\":false,\"properties\":{\"option\":{\"type\":[\"string\",\"null\"],\"maxLength\":4},\"double\":{\"type\":[\"string\",\"null\"],\"maxLength\":4},\"items\":{\"type\":[\"array\",\"null\"],\"items\":{\"type\":\"string\"}}},\"title\":\"Patch\",\"type\":\"object\"}")
}
func PatchPluginJSONSchema() json.RawMessage {
	return json.RawMessage("{\"additionalProperties\":false,\"properties\":{\"option\":{\"type\":[\"string\",\"null\"],\"maxLength\":4},\"double\":{\"type\":[\"string\",\"null\"],\"maxLength\":4},\"items\":{\"type\":[\"array\",\"null\"],\"items\":{\"type\":\"string\"}}},\"title\":\"Patch\",\"type\":\"object\"}")
}
func DecodeTimestampPatch(data []byte) (TimestampPatch, error) {
	return contract.Decode[TimestampPatch](data)
}
func (v TimestampPatch) Validate() error { return contractValidateTimestampPatch(v, 0) }
func contractValidateTimestampPatch(v TimestampPatch, depth int) error {
	if depth > 1000 {
		return fmt.Errorf("validation nesting exceeds 1000")
	}
	if v.At != nil {
		if (*v.At) != nil {
			if err := contract.Timestamp(string((*(*v.At)))); err != nil {
				return contract.At("at", err)
			}
			if err := contract.Text(string((*(*v.At))), 0, -1, ""); err != nil {
				return contract.At("at", err)
			}
		}
	}
	return nil
}
func (v *TimestampPatch) UnmarshalJSON(data []byte) error {
	obj, err := contract.Decode[map[string]json.RawMessage](data)
	if err != nil {
		return err
	}
	var next TimestampPatch
	for key := range obj {
		switch key {
		case "at":
		default:
			return contract.At(key, fmt.Errorf("unknown field"))
		}
	}
	{
		raw, ok := obj["at"]
		if ok {
			if contract.IsNull(raw) {
				next.At = new(*string)
			} else {
				value, err := func(b []byte) (**string, error) {
					return contract.Pointer(b, func(b []byte) (*string, error) { return contract.Pointer(b, contract.Decode[string]) })
				}(raw)
				if err != nil {
					return contract.At("at", err)
				}
				next.At = value
			}
		}
	}
	if err := next.Validate(); err != nil {
		return err
	}
	*v = next
	return nil
}
func (v TimestampPatch) MarshalJSON() ([]byte, error) {
	if err := v.Validate(); err != nil {
		return nil, err
	}
	fields := []contract.Field{}
	if v.At != nil {
		fields = append(fields, contract.Field{Name: "at", Value: v.At})
	}
	return contract.EncodeObject(fields)
}
func DecodeDefaultsMsgpack(data []byte) (Defaults, error) {
	return contract.DecodeMsgpack[Defaults](data)
}
func (v *Defaults) UnmarshalMsgpack(data []byte) error {
	obj, err := contract.MsgpackObject(data)
	if err != nil {
		return err
	}
	var next Defaults
	next.Items = make([]string, 0)
	{
		raw, present := obj["items"]
		delete(obj, "items")
		if present {
			value, err := func(b []byte) ([]string, error) { return contract.MsgpackList(b, contract.DecodeMsgpack[string]) }(raw)
			if err != nil {
				return contract.At("items", err)
			}
			next.Items = value
		}
	}
	next.Labels = make(Labels, 0)
	{
		raw, present := obj["labels"]
		delete(obj, "labels")
		if present {
			value, err := contract.DecodeMsgpack[Labels](raw)
			if err != nil {
				return contract.At("labels", err)
			}
			next.Labels = value
		}
	}
	{
		raw, present := obj["enabled"]
		delete(obj, "enabled")
		if present {
			value, err := contract.DecodeMsgpack[bool](raw)
			if err != nil {
				return contract.At("enabled", err)
			}
			next.Enabled = value
		}
	}
	{
		raw, present := obj["count"]
		delete(obj, "count")
		if present {
			value, err := contract.DecodeMsgpack[uint32](raw)
			if err != nil {
				return contract.At("count", err)
			}
			next.Count = value
		}
	}
	{
		raw, present := obj["text"]
		delete(obj, "text")
		if present {
			value, err := contract.DecodeMsgpack[string](raw)
			if err != nil {
				return contract.At("text", err)
			}
			next.Text = value
		}
	}
	for key := range obj {
		return contract.At(key, fmt.Errorf("unknown field"))
	}
	if err := next.Validate(); err != nil {
		return err
	}
	*v = next
	return nil
}
func (v Defaults) MarshalMsgpack() ([]byte, error) {
	if v.Items == nil {
		v.Items = make([]string, 0)
	}
	if v.Labels == nil {
		v.Labels = make(Labels, 0)
	}
	if err := v.Validate(); err != nil {
		return nil, err
	}
	fields := []contract.Field{}
	fields = append(fields, contract.Field{Name: "items", Value: v.Items})
	fields = append(fields, contract.Field{Name: "labels", Value: v.Labels})
	fields = append(fields, contract.Field{Name: "enabled", Value: v.Enabled})
	fields = append(fields, contract.Field{Name: "count", Value: v.Count})
	fields = append(fields, contract.Field{Name: "text", Value: v.Text})
	return contract.EncodeMsgpackObject(fields)
}
func DecodeLabelsMsgpack(data []byte) (Labels, error) { return contract.DecodeMsgpack[Labels](data) }
func (v *Labels) UnmarshalMsgpack(data []byte) error {
	value, err := func(b []byte) (map[string]string, error) {
		return contract.MsgpackRecord(b, contract.DecodeMsgpack[string], false)
	}(data)
	if err != nil {
		return err
	}
	next := Labels(value)
	if err := next.Validate(); err != nil {
		return err
	}
	*v = next
	return nil
}
func (v Labels) MarshalMsgpack() ([]byte, error) {
	if err := v.Validate(); err != nil {
		return nil, err
	}
	return contract.EncodeMsgpack(map[string]string(v))
}
func DecodePatchMsgpack(data []byte) (Patch, error) { return contract.DecodeMsgpack[Patch](data) }
func (v *Patch) UnmarshalMsgpack(data []byte) error {
	obj, err := contract.MsgpackObject(data)
	if err != nil {
		return err
	}
	var next Patch
	{
		raw, present := obj["option"]
		delete(obj, "option")
		if present {
			if !contract.MsgpackNull(raw) {
				value, err := func(b []byte) (*string, error) { return contract.Pointer(b, contract.DecodeMsgpack[string]) }(raw)
				if err != nil {
					return contract.At("option", err)
				}
				next.Option = value
			}
		}
	}
	{
		raw, present := obj["double"]
		delete(obj, "double")
		if present {
			if contract.MsgpackNull(raw) {
				next.Double = new(*string)
			} else {
				value, err := func(b []byte) (**string, error) {
					return contract.Pointer(b, func(b []byte) (*string, error) { return contract.Pointer(b, contract.DecodeMsgpack[string]) })
				}(raw)
				if err != nil {
					return contract.At("double", err)
				}
				next.Double = value
			}
		}
	}
	{
		raw, present := obj["items"]
		delete(obj, "items")
		if present {
			if contract.MsgpackNull(raw) {
				next.Items = new(*[]string)
			} else {
				value, err := func(b []byte) (**[]string, error) {
					return contract.Pointer(b, func(b []byte) (*[]string, error) {
						return contract.Pointer(b, func(b []byte) ([]string, error) { return contract.MsgpackList(b, contract.DecodeMsgpack[string]) })
					})
				}(raw)
				if err != nil {
					return contract.At("items", err)
				}
				next.Items = value
			}
		}
	}
	for key := range obj {
		return contract.At(key, fmt.Errorf("unknown field"))
	}
	if err := next.Validate(); err != nil {
		return err
	}
	*v = next
	return nil
}
func (v Patch) MarshalMsgpack() ([]byte, error) {
	if err := v.Validate(); err != nil {
		return nil, err
	}
	fields := []contract.Field{}
	if v.Option != nil {
		fields = append(fields, contract.Field{Name: "option", Value: v.Option})
	}
	if v.Double != nil {
		fields = append(fields, contract.Field{Name: "double", Value: v.Double})
	}
	if v.Items != nil {
		fields = append(fields, contract.Field{Name: "items", Value: v.Items})
	}
	return contract.EncodeMsgpackObject(fields)
}
func DecodeTimestampPatchMsgpack(data []byte) (TimestampPatch, error) {
	return contract.DecodeMsgpack[TimestampPatch](data)
}
func (v *TimestampPatch) UnmarshalMsgpack(data []byte) error {
	obj, err := contract.MsgpackObject(data)
	if err != nil {
		return err
	}
	var next TimestampPatch
	{
		raw, present := obj["at"]
		delete(obj, "at")
		if present {
			if contract.MsgpackNull(raw) {
				next.At = new(*string)
			} else {
				value, err := func(b []byte) (**string, error) {
					return contract.Pointer(b, func(b []byte) (*string, error) {
						return contract.Pointer(b, func(b []byte) (string, error) { v, err := contract.MsgpackTimestamp(b); return string(v), err })
					})
				}(raw)
				if err != nil {
					return contract.At("at", err)
				}
				next.At = value
			}
		}
	}
	for key := range obj {
		return contract.At(key, fmt.Errorf("unknown field"))
	}
	if err := next.Validate(); err != nil {
		return err
	}
	*v = next
	return nil
}
func (v TimestampPatch) MarshalMsgpack() ([]byte, error) {
	if err := v.Validate(); err != nil {
		return nil, err
	}
	fields := []contract.Field{}
	if v.At != nil {
		var timestampAt any
		if v.At != nil {
			if (*v.At) != nil {
				timestampAt = contract.MsgpackTimestampValue((*(*v.At)))
			}
		}
		fields = append(fields, contract.Field{Name: "at", Value: timestampAt})
	}
	return contract.EncodeMsgpackObject(fields)
}
