// Code generated by wiregen; DO NOT EDIT.

package testfixture

import (
	"encoding/json/jsontext"

	"github.com/wspl/demi/go/internal/wire"
)

// UnmarshalJSONFrom decodes the JSON object of Tokens: it refuses a member that
// the type does not have, a required member that is missing, a null, and a
// value of another JSON kind than the member's, naming the member.
func (v *Tokens) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = Tokens{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "access":
			seen |= 1 << 0
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("access", err)
			}
			v.Access = s
		case "refresh":
			seen |= 1 << 1
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("refresh", err)
			}
			v.Refresh = s
		default:
			return wire.Unknown(name)
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("access")
	}
	if seen&(1<<1) == 0 {
		return wire.Required("refresh")
	}
	return nil
}

// validate checks the rules of the fields of Tokens, and reports every one that
// is broken.
func (Tokens) validate() error {
	return nil
}

// UnmarshalJSONFrom decodes the JSON object of Event: it ignores a member that
// the type does not have, and refuses a required member that is missing, a
// null, and a value of another JSON kind than the member's, naming the member.
func (v *Event) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = Event{}
	if err := wire.BeginObject(dec); err != nil {
		return err
	}
	var seen uint64
	for {
		name, more, err := wire.NextMember(dec)
		if err != nil {
			return err
		}
		if !more {
			break
		}
		switch name {
		case "index":
			seen |= 1 << 0
			n, err := wire.ReadUint(dec, 32)
			if err != nil {
				return wire.In("index", err)
			}
			v.Index = uint32(n)
		case "text":
			seen |= 1 << 1
			s, err := wire.ReadString(dec)
			if err != nil {
				return wire.In("text", err)
			}
			v.Text = s
		default:
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
	if seen&(1<<0) == 0 {
		return wire.Required("index")
	}
	if seen&(1<<1) == 0 {
		return wire.Required("text")
	}
	return nil
}

// validate checks the rules of the fields of Event, and reports every one that
// is broken.
func (Event) validate() error {
	return nil
}
